### ISSUE TITLE
[Global setting] Shadow setting ratio

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1007]
### Observation

**Shadow offset and blur for smaller and larger elements**
- [ ] Systematically adjust the shadow offset and blur from larger screen to small screens. Let's start with a 60% ratio and stress test from there. We can see where smaller values don't need the systematic change so we should have a threshold of when to start to do the math. Let's pair and discuss if you pick this issue.
- [ ] Have a threshold for not changing the ratio on smaller values

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
