### ISSUE TITLE
Wrong label key in translations

### ISSUE THREAD

**Issue by baldurh** [Shopify/dawn#101]
While translating this theme to Icelandic I noticed an error in the collection view:

![image](https://user-images.githubusercontent.com/1823617/124502187-83cb7b80-ddb2-11eb-8c4d-a627793af797.png)

I noticed in the translation view this
![image](https://user-images.githubusercontent.com/1823617/124501968-0f90d800-ddb2-11eb-9a7a-f5bf8c1a07b3.png)

`Showing {{ count }} of {{ total }} products`

But looking at the `en.default.json` I saw this string
`Showing {{ product_count }} of {{ count }} products`

And using those variable names works fine.

Now, I’m not sure from where the wrong string is coming from as I was not able to find it in any file in the theme.

**Comment by chrisberthe** [comment]
Hey @baldurh can you confirm what version of Dawn you're using?

**Comment by baldurh** [comment]
@chrisberthe I’ve just fetched the latest upstream and checked again. This is the same in the latest version.

**Comment by chrisberthe** [comment]
Unfortunately I can't seem to replicate this. I see `Showing {{ product_count }} of {{ count }} products` in the code with the latest Dawn version. Is there any possibility the version that's on your store is not version `1.0.0`?

**Comment by tyleralsbury** [comment]
> Now, I’m not sure from where the wrong string is coming from as I was not able to find it in any file in the theme.

I just looked through the theme and can confirm that I don't see any instances of `Showing {{ count }} of {{ total }} products`.  I only see `Showing {{ product_count }} of {{ count }} products` and its corresponding translations.
