### ISSUE TITLE
[Global setting] Investigate Border thickness and opacity 0 behaviour

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1017]
### Context

1. The border width [could still occupy invisible physical](https://screenshot.click/21-12-dvrmi-10646.png) space and change the display of the section when opacity is set to  `0`.

   The implementation is not consistent across elements such as:

   - [Buttons](https://screenshot.click/21-12-xb7oj-2wdia.png), Inputs and Variant pills
   - Image banner [content box](https://screenshot.click/21-12-6pawg-mtdmu.png)

2. The border opacity is not always in theory a Border with a see through "opacity", it is a Border **color** opacity which [sometimes feels opaque on the background and other times not](https://screenshot.click/21-12-4nahi-urodl.png). The application should be predictable and intentional. 

There is a great opportunity for applying this rule on all components but we need to test this outcome on buttons and inputs to stress test the predictability of the setting behaviour and validate the success of the visual aesthetic outcome.  ([Video recording](https://screenshot.click/21-12-r6jnx-9x3uw.mp4))

**Notes:**
- >  That's an interesting one to me because if the opacity is 0 but the width is not, it makes sense to me that it would occupy space. If we're talking about it from the perspective of "what CSS does", it makes perfect sense. -  Tyler https://github.com/Shopify/dawn/pull/1003#issuecomment-992564298
- i.e. Image with text: Content container was adding the stroke inside the container, media was adding the stroke outside giving the visual ability to space out the shadow underneath the element.

**Comment by melissaperreault** [comment]
Parked question:
- Do we want to make sure to have a coherent behaviour until we take the time to fix this?
https://github.com/Shopify/dawn/pull/1003#issuecomment-993129321

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
