### ISSUE TITLE
Collapsible content section: Apply global settings

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1043]
**Describe the change needed**

Collapsible content needs an update to have it's content tweaked accordingly to the general settings added: 

- media border/shadow
- general padding
- content container border/shadow

This is a follow up to #956 

![](https://screenshot.click/21-12-3eago-untsv.png)

**Comment by tyleralsbury** [comment]
I would split this work in two.

The media stuff is very easy - it can be done really quickly by adding a single class @martinamarien 

The content stuff has considerations based on where the content background is applied.

**Comment by ludoboludo** [comment]
For the media stuff whoever ends up looking into it should test with a png with a transparent background and some media shadow: https://github.com/Shopify/dawn/pull/1220#discussion_r788061036
