### ISSUE TITLE
New color scheme setting for Interactive Media Controls 

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1051]
#### Internal Figma reference

Color scheme for Interactive media controls

 To add the setting to have a consistent color for: (Zoom badges, Video buttons, Video badges, 3D model badges, 3D model controls, and 3D model buttons). - TBD if this is required if color update is shipping or not.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
