### ISSUE TITLE
Border radius max value messing with content

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1060]
**Describe the current behavior**

When setting the border-radius to its max value, `72px`, some of the content can look not as expected.

**Describe the expected behavior**

Whatever the value chosen, the content looks always good.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.5.0

**Possible solution**

Either look into a max value that's lower or look into the layout issues and fix them 1 by 1.

**Additional context/screenshots**
- [Video on multicolumn section](https://screenshot.click/21-12-66u1v-2fpnh.mp4)
- [Collage section](https://screenshot.click/21-12-9jk87-zb18t.png)
- [Contact us page](https://screenshot.click/21-12-fqsi6-k393o.png)
- [Cart note](https://screenshot.click/21-12-oqsu9-z4eni.png)

I might have missed some as well.

**Comment by nicklepine** [comment]
We've adjusted the maximum radius values to solve for this.
