### ISSUE TITLE
Contact form section to use content-containers class

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1063]
**Describe the current behavior**

The section isn't getting any border styling from the global settings. 

**Describe the expected behavior**

Let's add the styling to it.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.5.0

**Possible solution**

We might need to do a bit more than just adding the class on the container. We might need another wrapper for the form on which we would then apply the styling. 

**Additional context/screenshots**
Original comment: https://github.com/Shopify/dawn/pull/1050#pullrequestreview-838043212

[screenshot](https://screenshot.click/21-12-nspfd-xjlox.png)

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
