### ISSUE TITLE
Slideshow Section: Apply Global Media Settings

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1068]
- [ ] The slideshow section should inherit the media setting styles

![image](https://user-images.githubusercontent.com/8127145/147157608-0ead88bb-4801-46cd-a2a5-c71759cfdff2.png)

**Comment by melissaperreault** [comment]
## UX task

- [ ] Before doing any dev work, let's plan and discuss the further implication, expectations, and conditions/rules about Slideshow’s media inheriting `Media` settings and the relationship with `Content containers` settings.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
