### ISSUE TITLE
Pagination spacing issue

### ISSUE THREAD

**Issue by danielvan** [Shopify/dawn#1103]
**Describe the current behavior**
The spacing between the pagination and the footer seems to have disappeared in some of our working examples.
https://screenshot.click/06-53-6h8c3-a0lly.png

**Describe the expected behavior**
The default bottom padding/margin should be consistent or similar to what the current Dawn version uses.
https://screenshot.click/06-44-9sldg-egriy.png

**Version information (Dawn, browsers and operating systems)**
- Chrome Version 96.0.4664.110
- macOS Version 12.1

**Possible solution**
Set the default bottom margin/padding to be consistent with current version of Dawn.

**Comment by nicklepine** [comment]
This is a duplicate from #1039 . Closing.
