### ISSUE TITLE
Collapsible Content Block: Padding around caret icon

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1104]
**Describe the current behavior**
There doesn't seem to be enough padding around the collapsible caret icon on collapsible content block. 

**Describe the expected behavior**
Add a bit of padding so this doesn't blend into longer labels. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.5.0

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/8127145/148396210-49538ad8-ed97-43d0-bac3-ecf6855cbe75.png)

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
