### ISSUE TITLE
Video: Videos and their cover image are not respecting media global styles

### ISSUE THREAD

**Issue by duygukalaycioglu** [Shopify/dawn#1117]
Video section: 
 
 When adding a video section to the theme, the cover image and the video do not inherit the media global styling. It seems like the borders are appearing behind the cover image and video file. 
 
 Video recording: https://screenshot.click/07-14-o8bij-6mw22.mp4
 
![image](https://user-images.githubusercontent.com/8127145/148556723-65b5a940-9100-4827-bd5b-0982d209b649.png)

Expected behaviour: 
Image and video should be contained within the borders.

**Comment by duygukalaycioglu** [comment]
2 findings:

1. The existing videos on product pages seems have sharp corners.
<img width="459" alt="Screen Shot 2022-01-06 at 4 07 43 PM" src="https://user-images.githubusercontent.com/88160784/148471879-f0421fe6-8447-458d-98c8-53c1194e4148.png">

2. When a new video section is added to the product page, the only corner that is round is the left bottom one, others stay sharp cornered. 
<img width="961" alt="Screen Shot 2022-01-06 at 4 34 46 PM" src="https://user-images.githubusercontent.com/88160784/148472065-24791b00-0c9e-4a46-91c3-2be71b479176.png">

**Comment by kmeleta** [comment]
I think this is being addressed in https://github.com/Shopify/dawn/issues/1117 @martinamarien?

**Comment by martinamarien** [comment]
Should be fixed on `main` now.
