### ISSUE TITLE
[Safari] Shadow behaves weird and leaves ghost elements on screen

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1120]
**Describe the current behavior**

Inputs offset shadow, Predictive search combo box, Contact form comments input: All their shadow offset or border behaves weird on screen.

[Video example](https://screenshot.click/22-01-c4afo-ugvl3.mp4)

**Describe the expected behavior**

Ideally we wouldn't see any elements remaining on the page and the shadow offset should be smooth.

**Version information (Dawn, browsers and operating systems)**
- Safari Version 15.2 (17612.3.6.1.6)
- macOS Version 12.1

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

- Input [example](https://screenshot.click/22-01-xuc54-16vn9.png)
- Comment input [example](https://screenshot.click/22-01-hq6kv-944js.png)

**Comment by ludoboludo** [comment]
browser bug report that sounds very similar: https://bugs.webkit.org/show_bug.cgi?id=207586
