### ISSUE TITLE
Feat. blog section, cards showing a background when it shouldn't

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1123]
**Describe the current behavior**

Noticed an issue on cards for the feat. blog section. If the card doesn’t have an image, the text/content has the color scheme applied from the global settings to it. But I don’t think it should otherwise it looks odd next to some articles that don’t have an image

**Describe the expected behavior**

It should match the content on cards with images I think. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.5.0

**Possible solution**

**Additional context/screenshots**
Here is how it looks: ![](https://screenshot.click/22-01-mn3t5-9dvxa.png)

The background of the section is black because we're adding color scheme options on all section in another PR.

**Comment by ludoboludo** [comment]
I noticed that this is also happening and seen on the blog page: 
![](https://screenshot.click/22-01-33zbj-4zet1.png)

**Comment by sofiamatulis** [comment]
It sounds like this was added on purpose 🤔 

We have a line here saying that if it's card of type standard we should do that:

`{% if settings.card_style == 'standard' %} color-{{ settings.card_color_scheme }}{% endif %}`

Quick video: https://screenshot.click/20-41-0tsgx-ittr7.mp4

@melissaperreault could you confirm?

**Comment by melissaperreault** [comment]
I believe so too Sofia! 

> It should match the content on cards with images I think.

I am not sure I see well the proposition, the text would be floating because the outline wouldn't be inherited on that card. To me this is an edge case and would need more time to think of a good solution.
