### ISSUE TITLE
Refactor collage cards to use the general card class

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1136]
**Describe the current behavior**

We have some CSS specific code for the behaviour of the video and image blocks in the Collage section. 

We could look into reusing the styling from the `card` classes to reduce the repetition of the styling used. 

[Original comment](https://github.com/Shopify/dawn/pull/1090#discussion_r781325408)

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 4.5.0

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
