### ISSUE TITLE
Product Cards: Revise spacing between product name and price

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1172]
Two problems relating to spacing and the price label on product cards: 

- [ ] **1. Space between price and name**

There seems to be an excessive amount of vertical space between the product name and the product price on product Cards. Can we reduce this a bit? 

Whoever picks this up can pair with a designer to figure out an updated amount of padding. 

![image](https://user-images.githubusercontent.com/8127145/149230210-4f8e6906-edd0-4d59-af57-05fb1931bb48.png)

- [ ] 2. Strikethrough price alignment is off on mobile

![image](https://user-images.githubusercontent.com/8127145/149233240-3aaac1ad-0a0b-4d77-a8b0-f7d82bd697cb.png)

**Comment by kimberlyoleiro** [comment]
Close ^^
