### ISSUE TITLE
Collage Section: Section Height Setting

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1176]
The collage section can get really tall on larger screens and would benefit from a section height setting to let merchants create collage sections that don't exceed the height of a browser window. 

![image](https://user-images.githubusercontent.com/8127145/149233699-f86d902b-21e8-4fba-9a93-561fb146c1d8.png)

Video recording: https://screenshot.click/12-19-mna72-fb3ry.mp4

**Comment by melissaperreault** [comment]
Will be tackled by the parity effort!
