### ISSUE TITLE
[Faceted Filters] Mobile Clear control features incorrect role

### ISSUE THREAD

**Issue by svinkle** [Shopify/dawn#118]
## Issue summary

The mobile facet Clear control conveys a "link" role and semantics via `a` element. Users of assistive technology may become confused when activating this control does not load a new page or jump to another part of the page as expected with a "link" role. Currently the control clears the filters in the background and does not provide any other information.

<details>
  <summary>Screenshots</summary>
<img width="410" alt="Screenshot of Dawn mobile facet content drawer. Clear control is highlighted. " src="https://user-images.githubusercontent.com/1392632/124609207-6d1e3680-de3d-11eb-82d0-f97366512875.png">

</details>

#### HTML

```html
<a
  href="/collections/all"
  class="mobile-facets__clear button button--secondary js-facet-remove"
>
  Clear
</a>
```

## Steps to reproduce

1. Go to a collection page with Dawn theme with any supported mobile browser.
2. With an active screen reader, navigate to and activate the Clear control.

### Expected

- Clear control to convey `button` role

### Actual

- Control is conveyed as a link

## Recommendation

**In the JS env only:**

1. Use JS to dynamically apply the `role` attribute, setting its value to `button` in order to convey the appropriate role.
2. Ensure <kbd>Space</kbd> key is supported.

With this change, `button` semantics will be conveyed indicating to the user that an on-screen action will occur upon activation.

#### HTML

```html
<a
  href="/collections/all"
  class="mobile-facets__clear button button--secondary js-facet-remove"
  role="button"
>
  Clear
</a>
```

<!-- #### Diff

```diff

``` -->

## Specifications

- **Component:** Faceted Filters
- **WCAG Principal:** Perceivable
- **WCAG SC:** [1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)
- **Severity:** Medium
- **Effort:** Medium
<!-- - **Related:** -->

**Comment by eugenekasimov** [comment]
Hey @svinkle . What you described as a solution is already happening in the current code. I believe it hadn't been happening by the time you opened the ticket and later someone added this functionality :).

I'm closing this issue. Feel free to reopen it if I'm wrong. Thanks
