### ISSUE TITLE
Add media ratio setting for Product media

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1189]
### Observation

**Context**
When assets are tall and the media layout is set to `Thumbnails` or `Thumbnails carousel` we rapidly can lose them in view from the view port. We want to offer merchants more flexibility to make the most of their assets and needs.

**To do**
- [ ] Rename the `Desktop media size` to improve comprehension of the new setting? cc. @katycobb 
- [ ] Offer new media ratio setting that will change height of the featured media _(To investigate if the options are accurate and enough with UX)_

>  
    Desktop media height
    - Adapt to image
    - Small (3:2 ratio)
    - Medium (1:1 ratio)

- [ ] Add another setting to use original image ratio when height might crop merchants assets.
> 
     [ ] Use original image ratio
     Select if you don't want your image to be cropped.

**Other considerations**
- [ ]  Product template
- [ ]  Featured product (Even if we don't display thumbnails, the height setting can be relevant.)

**Comment by melissaperreault** [comment]
The Desktop media height setting options are not final. We must ensure to offer a scalable system. They serve an example in this issue.

**Comment by bredowmax** [comment]
Another idea to prevent preview images below the fold: preview images as a vertical list of images on the left or of the main image. I believe Amazon PDPs look like this

**Comment by kimberlyoleiro** [comment]
@melissaperreault the large featured product images on PDP were solved with D's work. settings were updated and images are now constrained within the viewport. Going to close this ticket 


![Image](https://user-images.githubusercontent.com/107572834/233730364-b236ca2f-58d3-4ac9-bf4a-81b5cc59d61e.png)
