### ISSUE TITLE
[Collection list] Cards becomes scrollable on smaller desktop resolution

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1218]
### Observation

- [ ] Depending on the resolution, the Collection list section becomes scrollable ([Video capture](https://screenshot.click/22-01-k2nc7-run53.mp4))

**Comment by danielvan** [comment]
@ludoboludo I can't seem to replicate the bug. The steps I followed were to update both Layout (vertical spacing and grid), and Card (shadows, corner radius) to match Sense. Looks good to me.

**Comment by ludoboludo** [comment]
Awesome, that should do it then 👍  I will close the issue and we can re open if it's noticed again.
