### ISSUE TITLE
Footer: Text Block: Default Copy Update

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1223]
The Regulatory Affairs team has asked that we tweak the default copy on the text block in the footer to encourage merchants to display their contact information on their footer. 

In order to respect updated guidelines from the [Consumer Protection Cooperation Network](https://ec.europa.eu/info/live-work-travel-eu/consumer-rights-and-complaints/enforcement-consumer-protection/consumer-protection-cooperation-network_en), we're looking to include a mention of "contact information" on the footer, so that merchants are more prone to add these details on their websites. 

Suggested new copy - but for @katycobb to review: 
"Share contact information, store details and brand content with your customers."

![image](https://user-images.githubusercontent.com/8127145/150175375-05685289-95f9-4c03-8a1d-a35dd18d9c5d.png)

**Comment by katycobb** [comment]
@nicklepine here you go! 

Share contact information, store details, or brand content with your customers.

**Comment by nicklepine** [comment]
@katycobb  Can we go with " Share contact information, store detail and brand content with your customers."  We want to make sure “share contact information” is not seen by the regulators to be an “either or” sort of suggestion.

**Comment by katycobb** [comment]
Sure! Updated: 

Share contact information, store details, and brand content with your customers.
