### ISSUE TITLE
escape character - github version control sync - locale files URLs

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#1225]
This might be a bit "off-topic", but does anyone know how to avoid a constant diff due to escape character in URLs in the locale files?

![Bildschirmfoto 2022-01-19 um 19 24 41](https://user-images.githubusercontent.com/13047497/150191482-921dab81-5ff4-4373-a20e-f714c1dae400.png)
 
This happens regularly when updating the theme

**Comment by gregjotau** [comment]
I open an issue, in case it actually is a bug that this escaping is happening.

**Comment by ethanclevenger91** [comment]
@gregjotau why did you close this? Also having this issue.

**Comment by ludoboludo** [comment]
I'm going to re open the issue so we can keep track of it. 👍
