### ISSUE TITLE
When a collection has one or more tags in its URL, filters are shown but have no effect

### ISSUE THREAD

**Issue by carolineschnapp** [Shopify/dawn#129]
**Describe the current behavior**

On the Navigation page, you can add links to collections that are filtered by tags:

<img width="1299" alt="21-45-y01j6-tmfdp" src="https://user-images.githubusercontent.com/143817/124651455-f139e380-de68-11eb-9288-c1b9867233cc.png">

When going to such links, however, the filters have no effect. They are completely ignored in the back-end.

**Version information**
- Dawn Version: Where can I find this?
- Chrome Version 91.0.4472.114
- macOS Version 11.4

**Possible solution**

There are two ways to fix this, either 1, 2 or 3 below:

1. Back-end fix: have tags work with filtering.
2. Back-end fix: have `collection.filters` NOT return any filter when `collection.current_tags` (aliased to, simply, `current_tags` on the collection page) is not blank.
3. Theme fix: add a conditional in the theme to hide the filters when `collection.current_tags` (aliased to, simply, `current_tags` on the collection page) is not blank, something like this:

```liquid
if current_tags == blank
```

![image](https://user-images.githubusercontent.com/143817/124651909-82a95580-de69-11eb-96e0-6c6d1c102455.png) 

@gabriel-letarte we probably should fix this in the back-end, right?

**Comment by carolineschnapp** [comment]
Let's fix this in the back-end.

**Comment by TGIFelix** [comment]
Has this been fixed in the backend?

**Comment by rcobiella** [comment]
Experiencing the same issue here. Any recommended workarounds?

**Comment by cadlec** [comment]
Hello @carolineschnapp 
_Let's fix this in the back-end._
Pls, is this fixed? because, I still have this issue

Or any workarounds ?

**Comment by carolineschnapp** [comment]
@cadlec Just to be clear, the fix in the back-end has been to not render filters when tags are applied to a collection. That fix has been deployed. We can not have tag filtering and facet filters work simultaneously. 

FYI, we are moving away from using tags to filter collection: the “move away” means that facet filtering will not be available when tag filtering is applied. It also means that we are very strongly encouraging merchants, theme partners, and app developers to use facets over tags to filter collections.

Our documentation: https://help.shopify.com/en/manual/online-store/themes/customizing-themes/storefront-filters

**Comment by cadlec** [comment]
@carolineschnapp Thank you!
