### ISSUE TITLE
Product Card: Provides no hover feedback below 990px window 

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#13]
[Video](https://screenshot.click/04-05-xmi6m-ii9gz.mp4)

**Problem**
Product card provides no feedback below 990px window width

**Expected**
I think hover effect should apply on smaller screens too, at least on non touch screens.

**Thoughts from Johan:**
Add text link feedback at minimum

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
