### ISSUE TITLE
[Product card] Product title and price spacing

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#1307]
Reduce the spacing between the product title and price on all screens. [Video](https://screenshot.click/03-23-i7j78-p2vh7.mp4) - when I change the margin-bottom to 0, the items look more closely related.

**Comment by kimberlyoleiro** [comment]
@Oliviammarcello this looks to be resolved on Dawn 9.0

<img width="855" alt="Screenshot 2023-04-21 at 4 29 53 PM" src="https://user-images.githubusercontent.com/107572834/233729226-cc4c2c17-b3ca-4e53-b3f7-9e0bd583f192.png">
<img width="288" alt="Screenshot 2023-04-21 at 4 31 37 PM" src="https://user-images.githubusercontent.com/107572834/233729356-374cb63d-5f7b-4889-b9c1-4b95e54e8d56.png">
