### ISSUE TITLE
Line item property returning an error on the product page

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1331]
**Describe the current behavior**

When adding a line item property to your product template, it returns an error due to a check running specifically on radio buttons. 

Adding a custom prop like this on the `main-product.liquid` file after the current for loop ([screenshot](https://screenshot.click/08-16-1lyny-752sa.png)): 
```html
<fieldset>
  <label for="your-name">Your name</label>
  <input form="{{ product_form_id }}" name="properties[Name]" type="text">
</fieldset>
```

**Describe the expected behavior**

It doesn't seem to break the add to cart functionality but throws an error in the console: 
![](https://screenshot.click/08-02-q4mg6-84cj6.png)

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 3.0.0

**Possible solution**

```javascript
updateOptions() {
    const fieldsets = Array.from(this.querySelectorAll('fieldset'));
    this.options = fieldsets.map((fieldset) => {
    // run a check here to see the type of input there are and do an early return if needed?
      return Array.from(fieldset.querySelectorAll('input')).find((radio) => radio.checked).value;
    });
  }
```

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
