### ISSUE TITLE
Filter drawer Unable to select filters via mobile view or collapsed desktop setting on collections page

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1346]
**Describe the current behavior**

When trying to select filters via mobile view or collapsed desktop on collection pages, the drawer closes prematurely:

[![](https://screenshot.click/bv7k8-v0kfi-0to4r-artet-8mzlm.gif)](https://screenshot.click/bv7k8-v0kfi-0to4r-artet-8mzlm.gif)

It doesn't happen on touch devices though.

**Describe the expected behavior**

Users should be able to select filters via mobile or collapsed desktop without the drawer closing prematurely:

[![](https://screenshot.click/kowb8-yoauw-1ko8a-tgzu0-2rh0v.gif)](https://screenshot.click/kowb8-yoauw-1ko8a-tgzu0-2rh0v.gif)

**More information**

 - Changes were made via the following PR: [#1242](https://github.com/Shopify/dawn/pull/1242) to fix issue: [#1188](https://github.com/Shopify/dawn/issues/1188)
 - I believe the fix was implemented to ensure that when `closeMenuDrawer()` was called with no params, the menu drawer would close: “Allow clicking outside menu to close menu, Ensure closing submenu does not also close main menu”.
 - Unfortunately it seems that now when you try to click on some elements (including input elements) within the drawer menu of the **Facets** filter and sort feature, the `closeMenuDrawer()` is called and closes the menu, rendering users unable to use the filtering feature correctly.

**Device information (browsers and operating system)**
- Chrome Version 97.0.4692.99
- macOS Version 12.2
- Themes: Dawn 3.0.0

**Possible solution**

 - As a possible solution, see changes made to `closeMenuDrawer` function [via the following commit.](https://github.com/Shopify/dawn/commit/7f73c1ce5574226345204377ebff978cbb153f32)
 - Adding back the if statement `if (event !== undefined)` appears to fix this issue, but may result in reviving the issues found in [#1188](https://github.com/Shopify/dawn/issues/1188)

```diff
  closeMenuDrawer(event, elementToFocus = false) {
-    if (event !== undefined) {
      this.mainDetailsToggle.classList.remove('menu-opening');
      this.mainDetailsToggle.querySelectorAll('details').forEach(details =>  {
        details.removeAttribute('open');
        details.classList.remove('menu-opening');
      });
      document.body.classList.remove(`overflow-hidden-${this.dataset.breakpoint}`);
      removeTrapFocus(elementToFocus);
      this.closeAnimation(this.mainDetailsToggle);
-    }
  }
```

**Comment by gregjotau** [comment]
I think this is the same as: https://github.com/Shopify/dawn/issues/1311
