### ISSUE TITLE
Collection -> product -> back button to collection = not maintaining position on mobile 

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#1354]
On desktop scroll works, on mobile it does not always scroll back to the position

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: Latest
- Chrome/Safari on mobile

From Baymard:

Return Users to the Same Place in the Product List when Returning from the Product Page 

Issue: If users have to refind where they were in a product list after returning from a product page, they may not find products of interest again and will become annoyed at having to redo previous work, and could abandon.

Advice: Return users to the same place in the product list after they return from product pages.

**Comment by markjaniczak** [comment]
I noticed this too and did some digging, you can find more info and a workaround [here](https://github.com/Shopify/dawn/issues/1449).
