### ISSUE TITLE
Multicolumn: add slider on tablet 

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#1360]
**Describe the enhancement you'd like**
Original comment by @ludoboludo

_I wonder here if we should be adding the slider on tablet as well. It took me a few seconds to realize that it's a section on which Enable swipe on mobile means only on mobile but not on tablet. When others, like feat. collection, blog posts do._

_Could be a follow up but I think should be shipped in the same them update/upgrade. Otherwise it makes for an odd experience. But maybe it would have too much of an impact on existing merchants. Unless we have a breaking change included and then we don't need to worry about it_ 

https://github.com/Shopify/dawn/pull/1352#discussion_r805025142

cc @wiktoriaswiecicka

**Comment by Innms** [comment]
did you find any solution for this @sofiamatulis
