### ISSUE TITLE
Product title doesn't display on browser tab

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#14]
**Problem**
Product titles don't show properly in the browser tabs, for product pages. 

**Expected**
Product tiles should display as tab title, for product pages (like Debut) 

Dawn: 
![image](https://user-images.githubusercontent.com/8127145/122093410-0f1ba780-cdd9-11eb-8c8c-a8de23cf70c3.png)

Debut: 

<img width="389" alt="Screen Shot 2021-06-15 at 9 46 16 AM" src="https://user-images.githubusercontent.com/8127145/122093471-1c389680-cdd9-11eb-874c-b5cdf2b11892.png">

**Comment by chrisberthe** [comment]
Closing in favour of #77.
