### ISSUE TITLE
On iOS 14 the cart image is stretched

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1409]
**Describe the current behavior**
![](https://screenshot.click/23-53-5ssuq-qdlsa.png)

The image on earlier version of iOS are stretched. Technically, it's a browser version we should be supporting.

**Describe the expected behavior**

The product image shouldn't be stretching

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 3.0.0
- iOS 14

**Possible solution**

Add on the element wrapping the image this styling: `align-items: flex-start;`

**Comment by gregjotau** [comment]
Related to this?

https://github.com/gregjotau/dawn-famme/issues/37

**Comment by pa-famme** [comment]
This is how it looks like. 
![image](https://user-images.githubusercontent.com/92975223/155549548-a8e169e7-a4b0-4716-89b8-6ba09a600919.png)
