### ISSUE TITLE
[Header] Logo position enhancements

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#1416]
### Add alternative logo position options on both desktop and mobile to provide additional flexibility.  
Screens on Figma can be [found here.](https://www.figma.com/file/VIshelzL4USycwoA3QU4Ix/Header?node-id=449%3A4122)

<img width="1250" alt="Screenshot 2022-02-25 at 2 17 56 PM" src="https://user-images.githubusercontent.com/60230008/155774754-f859e2bb-06b6-42d0-a8e0-8d902ee646a6.png">
<img width="1124" alt="Screenshot 2022-02-25 at 2 18 04 PM" src="https://user-images.githubusercontent.com/60230008/155774757-d04e6f1b-29f0-4eb5-a1eb-affd9c402acf.png">

![image](https://user-images.githubusercontent.com/8127145/164251075-c8ba33b3-85f1-46ea-8d0a-1e11f1855bb9.png)

**Comment by nickarvanitas** [comment]
Maybe this is outside of the scope of this issue, but I would expect a configuration that has the mobile hamburger menu appear on the top right side instead of the top left side, with the Logo left aligned.
