### ISSUE TITLE
obvious default for swatches: cross over the option if not available

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#144]
**Describe the enhancement you'd like**
A clear and concise description of what you want added to Dawn. Add any considered drawbacks.

All sizes seems to be available, but none are in stock, you can only see if they are out of stock after clicking:

![image](https://user-images.githubusercontent.com/13047497/124834846-add29880-df80-11eb-836d-5cd78bdf17ae.png)

**Describe alternatives you've considered**

**Additional context/screenshots**
Maybe a screenshot or design?

**Comment by gregjotau** [comment]
See famme.no for more examples.

**Comment by bredowmax** [comment]
I came across the same issue today: right now, it's not clear to the shopper which variants are available and which ones are not. In above displayed example, "Black/white" might be available in currently selected size 35, but not in size 36. Likewise, size 35 might not be available in "black/white"

**Comment by gregjotau** [comment]
I also think that a nice feature is to have pictures of variants, instead of text. Could be a setting to enable a picture of the variant, but that is more of a specialized feature, focus on the basics first of course.

**Comment by gregjotau** [comment]
This duplicates https://github.com/Shopify/dawn/issues/45 "sold out UI which has an open PR (which works, tested it)

**Comment by gregjotau** [comment]
![image](https://user-images.githubusercontent.com/13047497/126212342-d84ee598-4f6c-4475-8bed-5d428e087c38.png)
