### ISSUE TITLE
Product page slider controls coming up on mobile when there is only 1 image

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1448]
**Describe the current behavior**

When you go to a product page that has only 1 media and has the setting to `Hide other variants’ media after selecting a variant` checked, it's showing the slider controls: 

**Describe the expected behavior**

It should not be showing controls when there is 1 media only. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 4.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**

Seems to be due to this if statement in which we could also check if `variant_images > 0`: 
![](https://screenshot.click/03-43-s7hux-2k9ni.png) 

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by KaichenWang** [comment]
Seems to also be appearing for products with no media (Dawn 7.0.0)

![Screen Shot 2022-09-15 at 4 55 27 PM](https://user-images.githubusercontent.com/3710548/190451121-1a386a2f-46f9-48f9-8d60-a165a81ab365.png)
