### ISSUE TITLE
[Header] Sticky header options

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#1453]
Change the sticky header from a check box to a dropdown to allow for merchant to pick between no sticky header, always on, or only on scroll up (current). 

[Figma link. ](https://www.figma.com/file/VIshelzL4USycwoA3QU4Ix/Header?node-id=456%3A9225)

**Comment by kimberlyoleiro** [comment]
Consolidated into https://github.com/Shopify/dawn/issues/1454
