### ISSUE TITLE
If older browsers and newer versions of "bad" browsers will not be supported, add a popup

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#146]
**Describe the enhancement you'd like**
A clear and concise description of what you want added to Dawn. Add any considered drawbacks.

Newest version of the Samsung internet browser does not work with the theme, if there is no plan to support these browsers, it might be an idea to include a popup asking people to change to an up to date browser?

**Describe alternatives you've considered**

**Additional context/screenshots**
Maybe a screenshot or design?

**Comment by gregjotau** [comment]
@tyleralsbury do you know if the latest version of Samsung internet does work? Or if it does not work at all?

**Comment by gregjotau** [comment]
I am just closing this issue, as I hope that Samsung will update the browser pretty soon to make it work, so I do not think the dev effort supporting bad browsers is worth it Vs. other things that needs to be fixed.

Or are there any plans to support samsung internet (latest version)? @ludoboludo

**Comment by ludoboludo** [comment]
Hey @gregjotau, do you know if this is still an issue ? We had some changes done I believe a couple weeks ago to fix some of those issues 🤔 If I remember correctly. 

Might be a different issue here. But we had this: https://github.com/Shopify/dawn/pull/311
