### ISSUE TITLE
Rich text 2.0

### ISSUE THREAD

**Issue by wiktoriaswiecicka** [Shopify/dawn#1460]
Currently Rich text section has limited options to style heading and paragraph text or change text alignment. We are adding settings that allow merchant to achieve more layout options.

As a merchant:

- I can add more than 3 blocks to my rich text section
- I can align the content to be right, center of left aligned
- I have more options for position or layout of the content 
- I can italicize and bold words in my headings.

### 1. Section settings
- [ ] Text alignment (Left, Center, Right)
- [ ] Text position on desktop (Left, Center, Right)

### 2. Improve Heading block settings

  - [ ] Adding extra large text size 
  - [ ] Changing short text field to Rich text RTE to enable merchant to use bold / italic in large headings.

### 3. New block

- [ ] Adding caption block
- [ ] Lift block limits

**Comment by andrewetchen** [comment]
>### 2. Improve Heading block settings
>
>  - [ ] Adding extra large text size 
>  - [ ] Changing short text field to Rich text RTE to enable merchant to use bold / italic in large headings.
>
>### 3. New block
>
>- [ ] Adding caption block
>- [ ] Lift block limits

Setting a reminder for myself to look into the following:

**Extra large text size**
- We currently have `h0` for Large; `h1` for Medium; `h2` for Small.
- How will Extra large be implemented?

**Caption block**
- Should we use the same caption block from the Image with text section by including Text style and Text size?

**Block limit**
- Set a higher limit or remove it completely?
