### ISSUE TITLE
Blog posts with less whitespace

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#147]
**Describe the enhancement you'd like**
A clear and concise description of what you want added to Dawn. Add any considered drawbacks.

Blog posts are too narrow. Either increase the width so it is not so much whitespace or create a new template with less whitespace:

https://famme.no/blogs/news/det-du-trenger-for-a-komme-i-gang-med-treningen

Turbo theme has a nice blog template as default. Also the blog list is better. The dawn blog list is just confusing to be honest.

**Describe alternatives you've considered**

**Additional context/screenshots**
Maybe a screenshot or design?

**Comment by gregjotau** [comment]
@ludoboludo closing this, but you guys can look at the template we got custom coded on hey carson: https://github.com/gregjotau/dawn-famme

It looks better than the default Dawn I think, see the blogs on famme.no for reference (how they are listed)

**Comment by ludoboludo** [comment]
There has been some updates in here that might have changed the way it looked: https://github.com/Shopify/dawn/pull/581
