### ISSUE TITLE
Mega menu long text overflowing

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#1497]
**Describe the current behavior**
Long text is overflowing: 
https://screenshot.click/15-05-mu4vg-hc48d.png
https://screenshot.click/22-03-vau2f-tscif.png

**Describe the expected behavior**
It should not overflow

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

cc @melissaperreault

**Comment by melissaperreault** [comment]
Fixed by https://github.com/Shopify/dawn/pull/1520
