### ISSUE TITLE
Blog Article: Display day in date of publication

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#15]
![image](https://user-images.githubusercontent.com/8127145/123441539-f6ae4880-d5a1-11eb-9b6c-84242496d825.png)

**Problem**
In Dawn the date on blog posts, date only shows the month and year, not the day.

**Expected**
Should also output the day.

**Comment by ludoboludo** [comment]
This should also apply to article card (blog section) and for the search results right ?

**Comment by nicklepine** [comment]
Yes, wherever we are displaying the date, let's ensure we're displaying the day, month and year.

**Comment by ludoboludo** [comment]
Got another question for you @nicklepine. Is that ok to add the day to the date ? We have a filter that we can use and handles different formatting based on the language but it has the day in it. Have a look at [this article page and the comment](https://spicedivine-unstable.myshopify.com/blogs/news/test-blog).

You can see the different formatting options [here](https://shopify.dev/api/liquid/filters/html-filters#format) (note the `on_date` one).
