### ISSUE TITLE
Collapsible content section rows' hover style doesn't match the global settings

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1513]
**Describe the current behavior**

When hovering the row containers, the hover style doesn't receive the same border radius as the row containers receive via `content containers` global settings. 

**Describe the expected behavior**

Should match the visual look.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 4.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**

**Additional context/screenshots**
![](https://screenshot.click/18-45-stms1-ukqzm.png)

**Comment by kimberlyoleiro** [comment]
This looks to be resolved in Dawn v10
<img width="929" alt="Screenshot 2023-05-11 at 1 21 10 PM" src="https://github.com/Shopify/dawn/assets/107572834/b51c1b54-7b46-4903-882d-a2807886ae4a">
