### ISSUE TITLE
Desktop sliders' slide width

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1519]
**Describe the current behavior**

Desktop slider on the featured collection section is not showing the grid peek from the next element. This is due to the width calculation of the items. It should have another value to deduct from the width in order to maintain the grid peek. 

This is happening specifically with the PR about zero grid spacing. 

**Describe the expected behavior**

Should show the next slider a little bit.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 4.0.0

**Possible solution**

Add a value into the calculation of the width so that we're always showing the grid and not splitting the available space strictly for the slides visible.

**Additional context/screenshots**
![](https://screenshot.click/17-16-jalir-zmvx7.png)

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
