### ISSUE TITLE
choosing colors on product gets the right image, but the next images are wrong

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#154]
**Describe the current behavior**

1. Choose image
2. image shows up
3. go to next image 
4. the next image is not the right color

**Describe the expected behavior**

Would have expected all next images to be correct color after clicking the color

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by gregjotau** [comment]
@ludoboludo this one is related to the variant linked to images issue, so just closing this, but I still think it is a problem that that the "front image" is changed, but your "position" in the images your browsing has not changed. So that clicking a new color does not put you in a place where *all the next images* are the new color.

**Comment by ryanaldred11** [comment]
I just wanted to add some context in case anyone encounters this in the future.

I found this occurs up to Dawn 2.2.0.

It looks like this:

[![alt](https://screenshot.click/10-56-q6l86-ggchl.gif)](https://screenshot.click/10-56-q6l86-ggchl.gif)
