### ISSUE TITLE
Add to cart button spinner is not displayed in Safari

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#1589]
**Describe the current behavior**

When a custom clicks the add to cart button in Safari, the add to cart button goes blank and it looks like nothing is happening, then the button reverts to it's original state and an add to cart banner is displayed

**Describe the expected behavior**

When a customer clicks the add to cart button, the text in the button is replaced with a spinner to indicate the request is being processed and then afterwards the add to cart button is reverted to it's original state and an add to cart banner is displayed

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 4.0.0
- Safari 15.4 on MacOS (Catalina)
- Safari 15.4 on iOS 15.4

**Possible solution**

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mashkovtsevlx** [comment]
I proposed a fix in #1646

**Comment by andrewetchen** [comment]
Closing as this was fixed here: https://github.com/Shopify/dawn/pull/1646
