### ISSUE TITLE
Multicolumn text is not aligned on mobile swipe view

### ISSUE THREAD

**Issue by katycobb** [Shopify/dawn#1641]
**Describe the current behavior**
When multiple column blocks are used in multicolumn section, and the "enable swipe on mobile" is checked, the last column's content alignment is not as expected. The second-to-last column's text spills into the last column.  

**Describe the expected behavior**
The final column's content would be centered, and the second-to-last column's text would not be visible when viewing the final column. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 5.0.0
- Chrome Version 100.0.4896.127 
- macOS Version 12.3.1

**Possible solution**

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/93404168/165347872-eb85802f-3577-4364-8190-d4c0ad63b281.png)

**Comment by ludoboludo** [comment]
This should be fixed with this https://github.com/Shopify/dawn/issues/1641 PR merged 👍 Closing the issue.
