### ISSUE TITLE
[Product] Spacing between product title and product thumbnails is too tight

### ISSUE THREAD

**Issue by martinamarien** [Shopify/dawn#1652]
**Describe the current behavior**
The spacing between the product title and gallery thumbnail images is very small - on mobile.

We introduced this block of css. As a result, the margin top that was previously being applied to the product title h1, is not being applied anymore.

```css
.product__title > * {
  margin: 0;
}
``` 

<img width="428" alt="Screen Shot 2022-05-02 at 1 48 32 PM" src="https://user-images.githubusercontent.com/26778637/166298393-7eb9c932-9bdb-4d25-84b8-12b249f9df66.png">

**Describe the expected behavior**
We would expect more space between the thumbnails and the product title.

<img width="428" alt="Screen Shot 2022-05-02 at 1 47 41 PM" src="https://user-images.githubusercontent.com/26778637/166298272-9e207ede-1a5a-4bb1-9b1a-0679d7d53e4e.png">

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 5.0.0
- Chrome Version 101.0.4951.41 
- Safari
- iOS + Android

**Possible solution**
Modify the selector to only target the elements that the margin property should be applied to.

**Comment by bacounts** [comment]
Could this be addressed in a quick PR with #1653, or vice-versa?
