### ISSUE TITLE
Spacing between main image and gallery controls

### ISSUE THREAD

**Issue by YoannJailin** [Shopify/dawn#1653]
Currently, i noticed that on my theme product page, spacing between main image and gallery controls is really high. 

<img width="436" alt="Capture d’écran, le 2022-05-02 à 16 03 27" src="https://user-images.githubusercontent.com/95925370/166317479-6f278047-156d-42e3-9349-c67253d4a615.png">
<img width="480" alt="Capture d’écran, le 2022-05-02 à 15 55 29" src="https://user-images.githubusercontent.com/95925370/166317483-a91e0baa-4749-4378-8150-2e043f721a5e.png">

(By gallery controls, i mean slider controls or thumbnails slider) 

Also, I went to check on other themes using Dawn in the theme store (Crave in this example) and noticed that this spacing is shorter there. 

<img width="463" alt="Capture d’écran, le 2022-05-02 à 15 55 37" src="https://user-images.githubusercontent.com/95925370/166316800-9da5d198-6980-4a21-990d-65bf46b99e10.png">

I made sure in my test product that all images have the same ratio. Image sizes is different but the ratio if always square.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 5.0.0
- Chrome Version 101.0.4951.41
- macOS Version 11.3.

**Comment by bacounts** [comment]
Could this be addressed in a quick PR with #1652, or vice-versa?
