### ISSUE TITLE
Product Media thumbnails get cut off on small devices

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1656]
**Describe the current behavior**
Product media thumbnails can get cut off on smaller devices. 

Here's how to replicate: 
- Ensure show thumbnails is selected for mobile PDP
- go to a product page with multiple images
- Select the last thumbnail in the list
- observe that the thumbnail edge can get cut off by what seems to be background opacity behind the arrows. 

(note that this was spotted on iphone 10 using an actual device. this looks fine on inspect element.)

**Describe the expected behavior**

Avoid cutting off thumbnail images. 
![image](https://user-images.githubusercontent.com/8127145/166447765-c7ff09eb-26ca-4513-bda7-0a2c8ebd3cbd.png)

![image](https://user-images.githubusercontent.com/8127145/166447355-8411b121-b9b2-42e3-a9b1-fd6e28da19a9.png)

**Comment by ludoboludo** [comment]
This is related to this issue, so the fix can be similar: https://github.com/Shopify/dawn/pull/1648#issuecomment-1114853487
where we add a pseudo element to the `ul` with a `width: 1px;` and some padding or margin left applied.
