### ISSUE TITLE
The order form has too many fields

### ISSUE THREAD

**Issue by stunish** [Shopify/dawn#1682]
The order form has too many fields (name, country, address, province, postcode). Marketing in Ukraine is built in such a way that the customer is used to filling in only the "phone number" and "name" fields. The shop receives all the other data from the customer in a phone call. Our clients complain that it is very difficult to leave an application. However, these fields can't be removed: they're not available in the settings, and it's not clear how to remove them in the code. Editing address.liquid has no effect. Please make it possible to leave only the fields with phone number and name when placing an order.

Translated with www.DeepL.com
![Снимок](https://user-images.githubusercontent.com/105246634/167498315-65154c20-d409-4d13-aa37-28dd74952c8c.PNG)
/

**Comment by bacounts** [comment]
Unfortunately, this issue is not at the theme level. Please contact customer support and file an issue for review by the platform / editor team. Sorry we could not help you. Please feel free to close this issue at your convenience.

**Comment by stunish** [comment]
thank you
