### ISSUE TITLE
possible issue with Wallets (Apple Pay, Google Pay, Facebook Pay)

### ISSUE THREAD

**Issue by M00NSH0T** [Shopify/dawn#1685]
Last week, I noticed I was unable to delete items from my cart in my store (it's live, but I haven't launched / started advertising yet). The issue was also present with adding to the quantity in the cart. Trying to trace this kept leading me back to cart.js, but while I'd made some changes to that in the past, it had been working. 

Here's what I was seeing:

```
Uncaught TypeError: b.call is not a function
    at m (cart.js?v=10017497365385121541652281310:1:330)
    at CartItems.updateQuantity (cart.js?v=10017497365385121541652281310? [sm]:68:40)
    at CartItems.onChange (cart.js?v=10017497365385121541652281310? [sm]:30:10)
    at cart.js?v=10017497365385121541652281310? [sm]:23:12
    at global.js?v=137475518025856886881644779818? [sm]:165:20
```

Anyway, I went back to my development store and started messing around. I installed a clean new theme (v5.0.0) and was still seeing the issue. The one thing I noticed that I hadn't seen before were the icons during checkout for Google Pay, Apple Pay, and Facebook Pay. So, I tracked those down in the store settings and disabled them, and everything started working again. Went back to my live store, did the same, and it's working again as well.

I haven't yet been able to figure out which one(s) is at fault, but there does appear to be an issue here that makes it impossible to change quantities of items in your cart if you have all of these wallets active within Shopify Payments.

**Comment by bacounts** [comment]
Cc for triage: @melissaperreault

**Comment by M00NSH0T** [comment]
@ludoboludo thank you very much. It does seem to be resolved.

I actually had only selected Google Pay for that test in my settings as follows:
![image](https://user-images.githubusercontent.com/30039978/168403657-b55bf480-bf3b-44e7-acc4-5560f9fac09d.png)

before it would still show Facebook Pay as well, even though only Google Pay was selected. But that too appears to be fixed now, so whatever you did seemed to resolve both issues. Thank you.
