### ISSUE TITLE
[Variant picker block] Add checkbox to hide sold out variants

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#1693]
1. We can make an enhancement to how we tackle surfacing sold out variants. [Currently](https://screenshot.click/27-45-s1ceh-yq1j1.png), if a variant is sold out, the buyer only has the disabled add to cart button as a reference. We should have the variant pill  / dropdown indicate that the variant is sold out.  [See Figma](https://www.figma.com/file/mYV4VA1cld0UYcAIMe2Y8N/Product-Page?node-id=202%3A15976) [See current TS Snippet for code reference](https://ts-code-snippets.com/2.0_Themes/Product_Page/Disable_Items_Sold_Out_Dropdown/)

2. Add checkbox to the `Variant picker` block on the PDP to enable and disable the ability to hide sold out variants. [Figma](https://www.figma.com/file/mYV4VA1cld0UYcAIMe2Y8N/Product-Page?node-id=208%3A23536)

For Parity, ensure this is implemented on: 
- [ ] Product Page Template
- [ ] Featured product Section
- [ ] Quick Add Modal

**Comment by bacounts** [comment]
This topic has been a huge discussion in three already existing PR's. There seems to be several holdup's, including a platform based error. See #1407 & #105 & #876
