### ISSUE TITLE
Sticky Header: Behaviour Exploration

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#17]
The sticky header is not top notch on the product page, and cuts off the top part of the right column.

https://user-images.githubusercontent.com/26778637/122608826-e69ae400-d04a-11eb-86fd-1aad5a78b260.mov

From @martinamarien:This is the behaviour I would expect with the sticky header. It comes in on top of the content on the page and shouldn't cause content to scroll below it. I think we should leave it as is.

From @Guillaumegranger1: Is this something we can test easily? I'd be curious to see how we feel when interacting with the proposed fix.

**Comment by dan-menard** [comment]
Talked this over with some folks actively working on the header, we all agreed this is how the sticky header should work.

Closing as won't-fix.
