### ISSUE TITLE
Buttons on address page not working

### ISSUE THREAD

**Issue by uwi2k2** [Shopify/dawn#1702]
**Describe the current behavior**
On the page "account/addresses" all buttons that allows you to add, edit or delete addresses do not have event listeners and do not work at all. 
With a different theme (e.g. Debut) all buttons are working as expected.

This is what the code for a button in theme "Dawn" looks like: 
`<button type="button" aria-expanded="false" aria-controls="AddAddress">`

And in "Debut":
`<button type="button" class="btn address-new-toggle" id="AddressNewButton" 
aria-expanded="false" aria-owns="AddressNewForm">`

**Describe the expected behavior**
Form to add, edit or delete addresses should be visible after clicking the button.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 5.0.0
- Browser: problem exists in all browsers 

**Possible solution**
Add an event listener to all buttons.

**Comment by uwi2k2** [comment]
Problem Solved.
I was caused by an error in an app.
Your code works fine.

**Comment by uwi2k2** [comment]
closed

**Comment by ChristopherCapito** [comment]
@uwi2k2 hey. do you know how that error got introduced by the app? I have a similar issue but I dont know where to start looking.

**Comment by uwi2k2** [comment]
@ChristopherCapito .. i am sorry .. its so long ago .. it was for sure some JS error that occured on pageload.
If you have a link to your page i may take a look and see if i can help.

**Comment by ChristopherCapito** [comment]
Its motodream.de

Through a stackoverflow thread I found a code Snippet to add which just Creates an event listeners within the liquid file directly. But that also does not work 100% 

Also, ideally I would of course find a way to fix the issue instead of coding around it hehe
