### ISSUE TITLE
[Product page] Add image zoom flexibility

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#1704]
Update product information to include an image zoom selector. Provide options to `open lightbox`, `zoom on hover`, and `No zoom`. [Figma](https://www.figma.com/file/mYV4VA1cld0UYcAIMe2Y8N/Product-Page?node-id=483%3A28704)

@metamoni, we can split this into two parts. The latter is a nice-to-have, but there seems to be some open PRs with potential solutions that could be a quick win. Would you please start exploring what would be required to do both (disable and zoom on hover)

**Version 1**
- [ ] Add checkbox to disable zoom

**Version 2**
- [ ] Add option to zoom on hover

**Comment by bacounts** [comment]
Upon a PR merge, it should eventually close #733, #1323, #1381, #1502
