### ISSUE TITLE
[Multicolumn] Theme media setting application

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#1759]
When adding an image to the multicolumn section, the `Theme settings` --> `Media`  settings don't apply to the image. E.g the stroke opacity or corner radius. [Video](https://screenshot.click/31-20-ll96a-o1wco.mp4)

**Comment by melissaperreault** [comment]
Closing as it is captured here https://github.com/Shopify/dawn/issues/1525 but I'll add the comment for additional reference!
