### ISSUE TITLE
Add to cart does not work with JS disabled

### ISSUE THREAD

**Issue by bakura10** [Shopify/dawn#179]
Hi,

As of today Dawn output a <noscript> select: https://github.com/Shopify/dawn/blob/main/sections/main-product.liquid#L235

However another one is set in the product form: https://github.com/Shopify/dawn/blob/main/sections/main-product.liquid#L260

Because you cannot have two input with the same name, in this situation the last one (depending on the block order) will take the control, and as add to cart is typically after selectors, only the add to cart one will win.

Dawn add to cart form with non JS is therefore currently stuck to the first available variant.

I think Dawn should make sure that the name="id" only exists once within the form and be synchronized in JS.

**Comment by colinloretz** [comment]
+1 We are using our own theme built on Dawn and ran into this with a live customer. Going to go ahead and update our version to fix this but definitely a fix should be considered.
