### ISSUE TITLE
CLS problem with larger logo

### ISSUE THREAD

**Issue by RobertHowner** [Shopify/dawn#1798]
The bigger the top of page logo the bigger CLS warning you get, on both mobile and but much worse on desktop. If you set logo on for 250px this results in  large drop i page speed with 0,137 CLS

- Dawn Version: 6.0.1

I know you guys aim for 0 CLS so this would be a great improvement.

**Comment by RobertHowner** [comment]
After more testing it seems to be pretty random. I get lowest CLS on 180-200px with only 0.003 on both mobile and desktop. Hager an lower that that gives more CLS but not only on logo but other elements, seems to be pretty complex. But if possible to get rid of the CLS it would of course be great for PageSpeed scores.

**Comment by kimberlyoleiro** [comment]
Should be closed with https://github.com/Shopify/dawn/issues/1900
