### ISSUE TITLE
In Editor: Pop Up Modal customization freeze preview scrolling

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#18]
https://screenshot.click/21-06-6drut-imirz.mp4

*Problems* 

- [ ] Problem 1: Making changes while the pop-up page modal is open re-renders the section but leaves the modal open. The preview can no longer be interacted with after this happens.

- [ ] Problem 2: The hidden link for the pop-up activator gets wrapped with a live text data attribute, but the visible text does not. Since a live text data attribute exists, the editor tries to live text update the field, but since the visible text doesn’t have the attribute, no visible change to the preview occurs. We always ‘cleanup’ live text settings on blur of the text input, so the merchant will still see the change eventually, but they shouldn’t have to blur for this to happen.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
