### ISSUE TITLE
[Card settings] Cards with page pills within search results

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#1823]
Associate Pages within search results with the Blog cards settings until we have new theme settings specifically for Pages. This way, both Pages and Blogs within the search results will have better consistency.

Right now, Pages within the search results are using the Product cards settings

Original comment: https://github.com/Shopify/dawn/pull/1774#discussion_r901957724

**Comment by melissaperreault** [comment]
I think this issue is a duplicate of https://github.com/Shopify/dawn/issues/1821

I still think it would be more intuitive and future proof to rely on blog cards than collection cards as no collection cards appears in the search results page. To be discussed.

**Comment by sofiamatulis** [comment]
Closing since it's a duplicate
