### ISSUE TITLE
How do you guys automate the translation files?

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/dawn#1867]
I notice you guys have a [translation.yml](https://github.com/Shopify/dawn/blob/main/translation.yml) in the repo that appears to be used for generating all of the language config files.
Which bot, software is used to create these?

https://github.com/Shopify/dawn/blob/b7038b438ce91a2d7c62f69f8a286074b2a2b71a/translation.yml

Adding new strings to each of them is a pretty arduous task so hoped there would be an automation I could use instead.

**Comment by kimberlyoleiro** [comment]
Sorry folks, I'm going to close this issue as it doesn't contribute to our product roadmap
