### ISSUE TITLE
Filters not being removed when unchecked

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1879]
**Describe the current behavior**

When trying to uncheck filter items, they don't get removed unless it's the last checked filter.

**Describe the expected behavior**

You should be able to uncheck a filter, which would then remove the pill and update the list being shown. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 6.0.2

**Possible solution**

We seem to be keeping track of two filters (mobile version and desktop) and when running our fetch query we're removing the filter from only one of them. We could probably loop through the two array and remove the filter in both instances 🤔 

Looks like it would be related to some changes that were applied in this PR: [#1443](https://github.com/Shopify/dawn/pull/1443/files#diff-9418056d09bded2d61a68790334221e384b6404991d01e3a0f837c75e598fc76)

**Additional context/screenshots**
[video recording of the issue](https://screenshot.click/27-01-c7xv5-2csez.mp4)

**Comment by affinityphoto** [comment]
I'm experiencing the same issue. For my store, I can choose filters "available" and "unavailable". Then, I can choose a color with (1) product variant. This solo product is "available". I go back to the availability filter option and see:

[√] available (1)
[✓] unavailable (0)  _←this should be js unchecked and grayed out._ 

When i uncheck "available (1)",  I expect the code to show "no products match filer..." but it leaves the unchecked "available (1)" as active.  The filter does not remove the available product. From there, the js is unstable and filters don't uncheck/check properly. The js doesn't trigger on the checked state.
