### ISSUE TITLE
Broken Liquid when you use images wider than 5760px in places

### ISSUE THREAD

**Issue by willbroderick** [Shopify/dawn#1893]
This occurs in a few places. This example shows the problem on the article template.

**To recreate**

Upload an 8000px wide image to a blog post's featured image.
Go to that blog post in Dawn (any version that passes this through the `image_url` filter) and view source.
See error in source:
![image](https://user-images.githubusercontent.com/1590737/183026625-8d3a37cf-f86f-4acb-8c4e-d350906cdf01.png)

Caused by this line: 
https://github.com/Shopify/dawn/blob/87b7f1edaa6859fb36623d262d4044bcd6c73441/sections/main-article.liquid#L265

**Possible solution**

The `image_url` filter should automatically apply `min(param, 5760)` to the width parameter.

It seems like a strange choice (to me) to error when passing a large width into this filter. I can't think of a case where this is the preferred behaviour over the suggestion above.

At the moment, every time `image_url: image.width` is used, the code needs to include an extra line:
```
{% assign image_width = image.width | at_most: 5760 %}
{{ image_url: width: image_width }}
```
This is unnecessarily verbose, slower to process, more prone to user error, and duplicates an arbitrary platform-limit in theme code - a limit that could change.

**Comment by richardmonette** [comment]
If only width (or height) is specified then perhaps it could be min(param, 5760)

What would you expect the behaviour to be if both width _and_ height as specified? An aspect ratio preserving resize of the params? e.g.

```
longest_dimension = max(width, height)
scale_factor = 5760 / longest_dimension
width *= scale_factor
height *= scale_factor
```

**Comment by bakura10** [comment]
Hi @richardmonette ,

Thanks for having a look at this. If only one dimension is set, easy, just clamp to whatever the max is supported by Shopify. If both are specified, yes, clamp based on the max dimension and preserve the ratio. This would solve all our trouble for those extreme use case where merchants upload image directly coming from their camera :D

**Comment by bakura10** [comment]
I always wonder as well why the width is needed at all 😂. If I remember, the width allow to generate the URL being used as the src attribute. However with srcset the src is never used. Maybe Shopify could use the largest possible size as the src attribute if no width is explicitly set.

**Comment by ludoboludo** [comment]
>I do see that the docs https://shopify.dev/api/liquid/filters#image_url warn "You need to specify either a width or height parameter. If neither are specified, then an error is returned." however when I tested this it didn't actually appear to be necessary.
cc: @richardmonette 

I'm getting an error yeah when not mentioned a width or height: `Liquid error (sections/main-product.liquid line 58): image_url must define width or height`. And I was using `{{ product.featured_image | image_url | image_tag }}`
