### ISSUE TITLE
[Product Page] Description Section SPIKE

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1905]
Explore the idea of having a section to link to the product description to offer more flexibility to the merchant when deciding where to display the description of their product/variant. 

**Problem:** 
- merchants often request it when they have a long description without many images to balance their product page space.
https://docs.google.com/presentation/d/1sSS9YroYZ1Zn5_1E0UuG3RZRvfTd7pt4Abq5j8Hzrxs/edit#slide=id.g116fc1e2031_1_96

**How it's currently being solved:**
https://ts-code-snippets.com/2.0_Themes/Product_Page/%5Bs%5D_Add_a_Full_Width_Product_Description/

**Technical investigation:** 

- What is the level of effort to surface product description as a dynamic source similar to product title + vendor

<img width="323" alt="Screen Shot 2022-08-23 at 11 23 04 AM" src="https://user-images.githubusercontent.com/107572834/186198499-e996f171-6047-48c3-9ffe-8c27b55a6f20.png">

**Considerations:**
- Where does the product description get displayed by default? Product Info text block? The first tab of collapsible tabs block?
- If a merchant adds a subsequent section for there description (to have more visual space to display the content), what happens to the default product description? Is there duplication?

**Comment by stufreen** [comment]
One super important thing to consider @metamoni @kimberlyoleiro 

The rich text editor on the product description lets merchants add stuff like images, tables, colors, video, etc. However the `richtext` setting in the online store editor only allows bold, italic and links currently.

If we allow product description to be inserted as a datasource it would be the **first** time a datasource is more powerful than the setting it's inserted into. By that I mean you could insert all kinds of rich content using the datasource that you couldn't insert by just typing static text into the setting.

The risk of doing this is that themes might not have CSS to handle all of the additional rich content. The themes are built for the current `richtext` setting and may not be built to accept additional content. As soon as we ship this change it will let merchants insert `description` datasources and could result in broken themes.

We should consider what the roll out plan will be carefully. We will want to give third party merchants a chance to update their themes to make sure the correct CSS is in place, and obviously do the same with first-party theme, before shipping to merchants.

cc @mkoenig-shopify

**Comment by ludoboludo** [comment]
That's a great point I hadn't thought of Stu. One other direction we could take would be to reuse the [`page` section](https://screenshot.click/30-31-v1cgw-ipamq.png) we have which would work very well here. We would need to have a product description dynamic source and then place the section where we want on the page. 

That current page section would probably need some tweaking to offer more options. Right now it's a bit narrow.

**Comment by mkoenig-shopify** [comment]
One other thing to consider here is that technically we have a principle not to have datasources unlock styling that wouldn't be possible in static implementation. Unless we're revisiting that principle, IMO the rollout plan should start with using the `page` section as @ludoboludo mentioned. I would like to avoid using `richtext` in the editor for this usecase if we can avoid it. if it's unavoidable, though, then let's pair and make sure we're accounting for this shift in strategy going forward

**Comment by mkoenig-shopify** [comment]
let's pair on this if you want to go further, actually, since this idea may not even work @ludoboludo - could you grab time with @Rusty-UX @stufreen and myself to talk through this a bit more?

**Comment by ludoboludo** [comment]
Hey @Rusty-UX 👋 would you mind reminding me how theme support solves that problem ? 🙂

**Comment by Rusty-UX** [comment]
Howdy! I'm wondering if we could take this [section here: ](https://ts-code-snippets.com/2.0_Themes/Product_Page/%5Bs%5D_Add_a_Full_Width_Product_Description/#path-2-full-width-description-block) and include as a section on Dawn, only for the product template, that merchants could optionally add. And it would only be scoped to the product, not available on other templates.
