### ISSUE TITLE
Cart Drawer does not work at all.

### ISSUE THREAD

**Issue by outdatedx** [Shopify/dawn#1927]
**Describe the current behavior**
So my current website has a cart drawer and It does not work adding to cart opens up the menu but does not update anything in there unless I refresh and if I increase or decrease the quantity the I get this error meesage 
```
There was an error while updating your cart. Please try again.
```
I had alot of customization does to the theme itself so I cant even start from scratch or pull something from the repo or else I would have to rewrite almost everything.

Also Im using a starter kit which is dawn with tailwind
from here https://github.com/TrellisCommerce/shopify-tailwind-starter-base

**Describe the expected behavior**
It should update the cart, quantity and the total.
**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 6.0.1
- Chrome  Version 104.0.5112.102 (Official Build) (64-bit)
- Windows 11

**Comment by outdatedx** [comment]
Bump!

**Comment by ludoboludo** [comment]
Hello @outdatedx 👋 

If the theme has had a lot of customization but the original version is working properly there isn't much we can do about it as this repo is used to report issues on the original code of Dawn.

In this [help doc](https://help.shopify.com/en/manual/online-store/themes/theme-support#additional-resources) there are some resources/ways mentioned to get help in the situation that the theme has received lots of edits. 

I hope you get to find the reason of the issue.
