### ISSUE TITLE
Cannot render HTML as rich text on Product Custom Metafield

### ISSUE THREAD

**Issue by thespencercool** [Shopify/dawn#194]
**Describe the current behavior**
When using DAWN theme for online store 2.0, when entering HTML code on Custom fields on Metafields, will not display and render HTML as rich text. HTML will only display as PLAIN Text.
**Describe the expected behavior**
Expected behavior should display html as rich text on product page front end
**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**
possible solution is to fix theme to support and render html correctly as rich text for product page display. I am not a developer and may need online store support team for this.

**Additional context/screenshots**
[Screenshot removed]
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by dan-menard** [comment]
Closing as won't fix.

It would be a (very) large technical lift to support HTML in our RTE, we're not planning to add that level of support.
