### ISSUE TITLE
products are not added to cart on iphones

### ISSUE THREAD

**Issue by germ777** [Shopify/dawn#1947]
products are not added to cart on latest safari on iphone, ios 15.6.1 and also on older safari 13.1.2 for mac os.

to reproduce, click the ‘add to cart’ button on any product page, the ajax drawer is triggered and correctly shows the product added to cart, however the cart page doesn’t contain any products. the cart page displays “your cart is empty”. 

this issue appears on shopifys own dawn theme demo (https://themes.shopify.com/themes/dawn/styles/default/preview) using safari on iphone.

**Comment by bacounts** [comment]
@nicklepine for triage

**Comment by ludoboludo** [comment]
This issue you're noticing is only on the demo store from our theme store isn't it ? I'm noticing the same behaviour for all demo stores though it's not happening when I test the latest version of Dawn and on a personal store. 
If you can confirm those findings ^ that'd be great. I'll try and see why it's happening for the theme store or at least loop in the right team 🤔

**Comment by kimberlyoleiro** [comment]
@ludoboludo If this is not a Dawn issue can we please close this ticket
