### ISSUE TITLE
Search icon is displayed twice on certain viewports

### ISSUE THREAD

**Issue by valeriegohier** [Shopify/dawn#196]
**Describe the current behavior**
-On Dawn, when using center aligned logo placement and when collapsing to make the screen size smaller, the search icon is displayed twice

**Screenshots**
![Screen Shot 2021-07-15 at 1 35 16 PM](https://user-images.githubusercontent.com/53573494/125847859-45c12790-dc36-4cfe-a7e2-67e0e54139df.png)

**Comment by tyleralsbury** [comment]
Note that this specifically seems to happen at tablet breakpoints when the setting for a centered logo is enabled.
