### ISSUE TITLE
Redundant a11y attributes on icons

### ISSUE THREAD

**Issue by kmeleta** [Shopify/dawn#1972]
All our icon snippets and many other svg icons in Dawn are using both `aria-hidden` and `role="presentation"`. Presumably we don't need both and can probably remove. We should validate the current implementation and update all instances if needed.

@metamoni noticed here https://github.com/Shopify/dawn/pull/1933/files/8a6eb9e6009b43b0092e6d4d3b68008977815e19#r969426427

**Comment by metamoni** [comment]
@svinkle we noticed that a lot of our SVG icons use both `role="presentation"` and `aria-hidden="true"`. Since they both achieve the same thing - hiding the icon from screen readers - do we need both? Is there a reason why both were added in the past?
