### ISSUE TITLE
Could complementary products be a section?

### ISSUE THREAD

**Issue by baldurh** [Shopify/dawn#1978]
The new complementary products feature was introduced in https://github.com/Shopify/dawn/pull/1938

The markup was implemented in the `main-product` section which means the payload for the recommendation contains the entire `main-product` section and the `<product-recommendations>` element then pulls the `<product-recommendations>` tag out of the html response and injects the `innerHTML` into itself (so meta!)

This means that a) the payload is unnecessarily big and b) this cannot be reused anywhere.

I was wondering since the [products recommendations section HTML API](https://shopify.dev/api/ajax/reference/product-recommendations#get-locale-recommendations-products) can render any section whether the inner markup should be moved to a section (eg. `complementary-products`) instead and then you could change the `<product-recommendations>` tag to point to that section instead:

From
```
data-url="{{ routes.product_recommendations_url }}?section_id={{ section.id }}&product_id={{ product.id }}&limit={{ block.settings.product_list_limit }}&intent=complementary"
```
To
```
data-url="{{ routes.product_recommendations_url }}?section_id=complementary-products&product_id={{ product.id }}&limit={{ block.settings.product_list_limit }}&intent=complementary"
```

Then the payload only contains exactly the markup you want to inject into the tag instead of loading additional markup you throw away. This can then also be reused in other places as well.

I was planning on making this change for my store so I can render the complementary products in the cart drawer. Is this something you’d be interested in having done in dawn as well?

cc @ludoboludo since you added the feature. Thanks btw, it’s amazing! 🔥

**Comment by ludoboludo** [comment]
> I was planning on making this change for my store so I can render the complementary products in the cart drawer. Is this something you’d be interested in having done in dawn as well?

This sounds like an interesting take. I can see how it would be useful to show it in there. I'm curious as how you decide which complementary products to show though as you would need to loop through all the items added into the cart and select which complementary products you're wanting to display 🤔 

As for using a section, could you elaborate a bit more on what you mean ? 
Since we're using/showing it as a block, it's part of the `product-information` section, which as you mentioned outputs the whole HTML from it and we're handpicking what we want. I agree that it's pulling in more info that needed. 

You mean that if we were to use a section instead of a block, then the result of the fetch would be a lot smaller and more performant ?

**Comment by ludoboludo** [comment]
> However, this could be tricky in terms of theme/block settings since this disconnects the markup from the block. It would probably need to be styled and configured using global theme settings for this to work.

Yeah that's the part I would be a bit concerned about 🤔 Even in terms of merchant experience while using the theme. I don't think we have a similar behaviour anywhere else in the theme at the moment.

**Comment by baldurh** [comment]
Yeah that part is tricky. I'll just go for a custom implementation for my theme since I can pretty much hard code the configuration in the section and then re-use it in the cart drawer. Thanks for the discussion and feel free to close this issue 😊

**Comment by ludoboludo** [comment]
My pleasure! Always nice to see how features are being used and how we could approach them differently 🙂

**Comment by baldurh** [comment]
Hey @ludoboludo just in case you’re interested I completed the cart upsell feature for my store :)

![cart-upsell](https://user-images.githubusercontent.com/1823617/230771115-c41e0038-ca9c-4682-813a-94996fcc3a82.gif)

You can see it in action on https://dimm.is/

**Comment by ludoboludo** [comment]
Niiice! Looking very sharp 👌 🤩  ill share with the team 🙂
