### ISSUE TITLE
[In Editor] Refactor theme color settings to prevent full preview reload

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#20]
**Problem**
Almost all general theme color settings are included in a style tag in the body of the document + are filtered in liquid. Because they are filtered, we need to ‘cleanup’ our live color setting update operations with a server rendered source of truth. Because they are rendered in a style tag in the body of the document, the only cleanup we have available to us is a full preview reload. This is quite slow.

**Comment by melissaperreault** [comment]
Closing for now, we can revisit later.
