### ISSUE TITLE
Dawn theme theme score can not goes more then 70

### ISSUE THREAD

**Issue by ersanjay5991** [Shopify/dawn#2000]
**Describe the current behavior**
Dawn theme page speed score  very low 25

**Describe the expected behavior**
I can see the dawn theme page speed score 99 on somewhere on doc

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version : linux

**Possible solution**
theme speed as maximum after adding few image and text update also.

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
mobile score 23 it's very low
![image](https://user-images.githubusercontent.com/39982842/193397585-15562410-2a73-4bb8-a00f-e857b8182b9d.png)

**Comment by baldurh** [comment]
Please post a link to your store so this can be investigated

**Comment by Zeioth** [comment]
Some kind of AMP support would be nice. Google seems to value this a lot.

**Comment by bakura10** [comment]
AMP is more or less deprecated @zeioth, Google no longer pushes it and no longer show AMP results on the search engine. You should avoid AMP in 2022 :)

**Comment by thecoolagency** [comment]
Avoiding too many apps. Keeping your theme clean when [removing apps](https://community.shopify.com/c/shopify-apps/removing-code-from-a-deleted-app/td-p/951319) can also help. 

This is built on Dawn + a lot I added: 

<img width="1037" alt="Screen Shot 2022-10-03 at 11 52 18 PM" src="https://user-images.githubusercontent.com/8910410/193753736-ad4bdb36-5756-4ecf-ba0f-e596d4dc7f57.png">

Dawn isn't the problem. Share a link so we can troubleshoot!

**Comment by kimberlyoleiro** [comment]
Closing this as it's not related to the Dawn repo
