### ISSUE TITLE
Option to switch cart type

### ISSUE THREAD

**Issue by KyleStych** [Shopify/dawn#2010]
Looking for an option to switch the cart type from Page to Popup on individual product templates.  If there's an override somewhere or someone can tell me where this decision is made, I can attempt a PR.  Thanks

**Comment by ssaich1** [comment]
This is updated in the theme editor > settings > cart. You can choose between Page, Popup notification, and Cart drawer on the newest version of Dawn. Some previous versions of Dawn did not include the choice options, instead only allowing a popup notification.

**Comment by ssaich1** [comment]
It is not possible to change the cart type per individual product templates.
