### ISSUE TITLE
Same product with different settings on Product page and Featured Product - confusing

### ISSUE THREAD

**Issue by eugenekasimov** [Shopify/dawn#2012]
**Describe the current behaviour**
With a new [Inventory status block](https://github.com/Shopify/dawn/pull/1979#discussion_r989704445) in the Product page and Featured product sections a merchant can set different threshold for the same product which will cause a confusing for buyers. Based on a different threshold value you may see a different status.

<details>
<summary>Product page</summary>
<img width="2493" alt="Screen Shot 2022-10-07 at 9 49 50 AM" src="https://user-images.githubusercontent.com/105315663/194608884-5516158c-20ac-43b4-8d86-6f2dd620b14f.png">
</details>
<details>
<summary>Featured product</summary>
<img width="2493" alt="Screen Shot 2022-10-07 at 9 51 20 AM" src="https://user-images.githubusercontent.com/105315663/194609075-574c023b-b154-4e19-89cc-5181b0dbe5b4.png">
</details>

**Describe alternatives you've considered**
Due to technical limitation we cannot linked two settings from different schemas and make them get synchronized. I see a few ways of resolving this issue.

- Remove this block from the Featured product section. ✅
- Accept it as is and inform merchants about potential confusion that may occur. 
- Add this setting to the global Theme Settings.

**Comment by eugenekasimov** [comment]
> @eugenekasimov - You could move the threshold slider out of the block level and into the Theme Settings. You would need to add a theme setting section, as currently, none are logical for this, but it would make the setting more global.

Hey @bacounts , thanks for another alternative way. I should add this to my description.

**Comment by melissaperreault** [comment]
Hey Eugene, thanks for documenting this!
We see value to leave the block at a local level for more flexibility for merchants to add where they see the best use case. It follows a similar pattern like `Reviews` for instance where if you would like to display reviews on all product reference you would have to add it manually. Let's observe and adjust as we learn more how merchants are using it.

**Comment by kimberlyoleiro** [comment]
Hey folks! Thanks for this suggestion. As @melissaperreault alluded to, there are different contexts in which product information is displayed. The featured product session does not need to be a mirror of the product page. There's also the added complexity of having different product templates with different settings that creates a net new context to try to map too. 

I'm keen to close this one @eugenekasimov
