### ISSUE TITLE
Footer UI & Sign up 

### ISSUE THREAD

**Issue by valeriegohier** [Shopify/dawn#202]
- The footer has lots of white space between the columns and also between the columns and the Signup section 
- The box for sign-up could be more refine and the stroke between the box ''your email" and '' Subscribe'' are not the same. 

[Screen Shot 2021-07-15 at 1 56 42 PM](https://user-images.githubusercontent.com/53573494/125856542-330aa51c-3d9d-4721-9c6e-50c290fe2ba7.png)

**Comment by wiktoriaswiecicka** [comment]
### Sign up form

> The box for sign-up could be more refined and the stroke between the box ''your email" and '' Subscribe'' are not the same.

> On mobile, the boxes surrounding "Your Email" and "Subscribe" (as well as language and country selector) should either be consistent widths or removed entirely. I recommend removing And +1 to Val's note about the stroke weights being inconsistent.

> "Sign up to our emails" is oddly phrased and doesn't offer much given that "Your email" is already written out in the field. We could further simplify the footer by removing the header and making the text within the field editable.

- [ ] Benchmark shows that the Newsletter block in the footer is not as prominent as other parts of the theme (in contrary to catch more attention) We will keep a simplified version and remove the Subscribe button completely, and replace it with an arrow within the input field.

> "Sign up to our emails" is oddly phrased and doesn't offer much given that "Your email" is already written out in the field. 
@gretchen-willenberg could you help with this one?

- [ ]  Reduce whitespace around newsletter:  `.footer-block--newsletter {margin-top: 5rem - change to 2rem)`

Updates on mobile before and after:

<img width="679" alt="Screen Shot 2021-07-22 at 2 14 38 PM" src="https://user-images.githubusercontent.com/61301164/126688694-801e6ad4-5abe-45a4-9cfa-84ce0a7f140c.png">

### Collapsible menu links

> On mobile, rather than collapse all items into a "quick links" drop down, we should explore a version where items are simply stacked. If we do collapse the list, we should remove the lines above and below the "quick links" text to avoid line redundancies. https://screenshot.click/16-16-sfox6-61f3b.png

- [ ] Adding a setting to collapse/expose all the filters would create a more complex Liquid logic. Given that Dawns main audience is merchants with small to mid-size catalog, and merchants starting with a default theme, won't build a more professional footer. wouldn't have many links in the menu. We should be more optinionated and choose for merchant to **expose all the links instead and remove collapsible menu.** 


### Other layout improvements

- [ ] Remove "Follow us on social media" written out. The icons alone are sufficient without the text.

- [ ]  Desktop: Reduce padding top and bottom on the whole section to match the 5rem on other sections

**Comment by gretchen-willenberg** [comment]
Thanks @wiktoriaswiecicka That was a bit of old copy or placeholder copy.  
1. The heading copy should be `Subscribe to our emails` (no punctuation; the Figma had the typo)
2. The email field placeholder might be from the language editor. (*worried expression*) From what I read via Github issues and Slack, the recent language editor work has been done without any content designer support or review. See image from my draft 2.0 Dawn store's language editor.
We aren't encouraging merchants to change it and I agree with the simplification to `Email`  vs `Your email`
3.  Also agree with removing the help text above the social icons; I don't see any use of that in the [copy doc](https://docs.google.com/document/d/14Aa-twJrAWSo95v7RwTF0M2Pk5xJE3t10GJfmcesWBU/edit?usp=sharing) Melissa and I used to review copy. See 'Footer' 

![Screen Shot 2021-07-22 at 3 06 38 PM](https://user-images.githubusercontent.com/68568732/126695627-96da7f8b-17a0-4ed4-970b-a60515b7c0f6.png)
