### ISSUE TITLE
UI of boxes 

### ISSUE THREAD

**Issue by valeriegohier** [Shopify/dawn#203]
- Stokes around boxes are not delicate and could look more sophisticated 
![Screen Shot 2021-07-15 at 2 26 22 PM](https://user-images.githubusercontent.com/53573494/125859447-b45cd4e8-6693-4a14-9da7-28a33c4644fb.png)

![Screen Shot 2021-07-15 at 1 56 42 PM](https://user-images.githubusercontent.com/53573494/125859428-a8a04d02-acac-4012-8ebf-50ddde6bfa7e.png)

**Comment by nicklepine** [comment]
Closing this ticket, as the specific areas where borders are problematic are documented in other tickets.
