### ISSUE TITLE
Mix and match your bundle

### ISSUE THREAD

**Issue by valeriegohier** [Shopify/dawn#209]
-On Dawn's preset #2, what is the box '' Mix and match your bundle''?
![Screen Shot 2021-07-15 at 9 33 40 PM](https://user-images.githubusercontent.com/53573494/125879631-d8c0d129-a05e-4f59-95b8-4cd6504e1cde.png)

**Comment by nicklepine** [comment]
This is copy from the merchant we're using for the demo. We'll remove that.
