### ISSUE TITLE
Search Modal: Page Scrolls slightly when opened

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#21]
### Reason 
When the search modal is opened, it animates (-1.5rem) before coming down. And at the same the input element inside of the modal is receiving focus (`trapFocus`). I _think_ when it receives focus, it's "above" the header by 1.5rem and causes the page to scroll by that much.

We should be applying some sort of delay (200ms?) to take into consideration the animation for the search modal.

### Replicate 
Trigger the sticky header. Click on the search modal and then close. Repeat a few times. You will notice the page is scrolling by 1.5rem every time you open it. 

Browsers: Chrome and Firefox.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
