### ISSUE TITLE
Update the opacity of all separator lines

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#22]
Currently, all separator lines have an opacity of 20%. They should be updated to 8% of the text colour to match the stroke lines used in the collage section and create a more subtle embellishment through the theme.

**What's included:**
- Footer, header, announcement bar
- Accordion on the product page
- Lines between pickup availability options, etc.

**What this doesn't include:**
- Form fields
- Product card borders
- Dropdown borders (i.e navigation, cart notification)
- Drawer borders (i.e navigation on mobile, pickup availability) 

cc: @Guillaumegranger1

**Comment by Guillaumegranger1** [comment]
I'm personally more inclined to keep the outer stroke at 20% as per the second screenshot. We should make sure it's consistent with the other fly out elements, such as the cart notification, desktop dropdowns, mobile nav, etc.

**Comment by ludoboludo** [comment]
Oh should I change the opacity as well in the filter drawer? It seems like it would make sense: ![](https://screenshot.click/21-08-atel6-yi3yi.png)

**Comment by Guillaumegranger1** [comment]
Yes to the question above. 👍
