### ISSUE TITLE
Color option for header backround

### ISSUE THREAD

**Issue by kimlohnne** [Shopify/dawn#221]
It is possible to change color for footer.
Would like this possibility for header aswell.
It is needed to make logo and header look good together

**Comment by dan-menard** [comment]
This can be accomplished using the "color scheme" option in Dawn:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/590055/206568664-110c48a8-85ea-4c3a-a330-40f8f87b2fa9.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/590055/206568735-4796f9c3-a7b9-474a-b515-3096a0b321f0.png">
