### ISSUE TITLE
Cant list product's tags in product card template

### ISSUE THREAD

**Issue by sensorario** [Shopify/dawn#2213]
## Describe the current behavior

I cant list the list of tags of a product in product template.

## Describe the expected behavior

I expect to list all the tags, ... 

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 6.0.2

## Possible solution

Sorry, .. I've not idea.

## Additional context/screenshots

I've added this piece of code inside product templte. The product have a tag.

{%- tag in product.tags -%}
    {{ tag }}
{%- endif -%}

But I do not see anything.

**Comment by ludoboludo** [comment]
Should work if it's done in a forloop. In your example you're using an invalid liquid approach. It would need to be: 
```liquid
{%- for tag in product.tags -%}
  {{ tag }}
{%- endfor -%}
```

Feel free to reopen if that wasn't the issue
