### ISSUE TITLE
Support for variant image or swatches instead of option selector in text

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#224]
**Describe the enhancement you'd like**
A clear and concise description of what you want added to Dawn. Add any considered drawbacks.

We want something built into the theme that we got custom built for famme.no, I think it will be useful for all merchants

```
 {%- if option.name contains 'olor' or option.name contains 'olour' or option.name contains 'COLOR' or option.name contains 'COLOUR' -%}
                        	<label class="color" for="{{ section.id }}-{{ option.name }}-{{ forloop.index0 }}">
                              {%- for variant in product.variants -%}
                              	{%- if variant.option1 == value or variant.option2 == value or variant.option3 == value -%}
                              	  {%- if variant.image -%}{{ variant.image | img_url: 'compact' | img_tag }}{%- break -%}{%- endif -%}
                                {%- endif -%}
                              {%- endfor -%}
                        	</label>
                          {%- else -%}
                            <label for="{{ section.id }}-{{ option.name }}-{{ forloop.index0 }}">{{ value }}</label>
                          {%- endif -%}
```
```
.product-form__input input[type='radio'] + label.color {
  padding: 0;
  overflow: hidden;
  border-color: transparent;
}
.product-form__input input[type='radio'] + label.color>img {max-width: 59px;}
```

But maybe the Shopify team can find something more effective, it is a very normal request to have swatches, but I think variant images is better as there is no need to maintain swatch colors. 

**Describe alternatives you've considered**

Swatches or just keep text

**Additional context/screenshots**
Maybe a screenshot or design?

![image](https://user-images.githubusercontent.com/13047497/126195667-1fa48864-a5fe-496b-b025-ea3b76e03769.png)

**Comment by gregjotau** [comment]
@ludoboludo any thoughts on this one? If it is not realistic to implement the issue can be closed.

It is problematic with the 'color' check conditions, as in different languages the option will be "farge", "farve", "coleur" etc. for norwegian, danish, french. 

But I think having this would be a major value add for many stores :)

**Comment by ludoboludo** [comment]
Hey @gregjotau, hmm yeah that condition might be too fragile to be used. But I get the idea. I will keep it in mind and bring it up to the team.
