### ISSUE TITLE
Language/Currency Picker in the Header

### ISSUE THREAD

**Issue by duygukalaycioglu** [Shopify/dawn#2240]
**PR SUMMARY**
Currently the merchants have language/currency pickers on the footer.
We are adding the same pickers to the header. 

 **SETTING UPDATES**
- [ ] Add two toggles for each picker to the header settings - one for language and one for country (currency). Default: both toggles are on.

<img width="381" alt="Screenshot 2023-01-20 at 1 59 32 PM" src="https://user-images.githubusercontent.com/88160784/213812827-9ce902df-430a-4d79-ad8f-ad43d8d2c492.png">

 **DESIGN UPDATES**
- [ ] Add two pickers to the desktop next to the search icon.
- [ ] Hide the pickers within the drawer menu on tablet and mobile. Make sure there is enough target sizes to be 44px wide and tall for the buyer on mobile to select from the lists and follow the same spacing values between the picker labels and the arrows.
<img width="733" alt="Screenshot 2023-01-20 at 2 19 46 PM" src="https://user-images.githubusercontent.com/88160784/213815374-b087f4f7-5059-4d55-92ae-16d97bc2c2b7.png">

[Prototype](https://os2-demo.myshopify.com/admin/themes/139250368534/editor)
[Figma file](https://www.figma.com/file/KAhNwsSXRi9JPsNRncX38O/Header-flexibility-Phase-2%2F3?node-id=722%3A8459&t=8VBe8YmfSaEwsbdH-1)

**Comment by YoannJailin** [comment]
Hello Andrew,

Looks nice! Here are a few notes :

On both mobile and desktop :
- When a selector is clicked and its drop down opened, can we display the arrow in the upper position?
- If one of the two drop downs is opened, if we click on the image banner below then click on the other selector, both drop-downs will be opened. Can we make sure that when we click outside of a dropdown, it closes no matter where we click outside of it? So both aren't opened at the same time.

On the mobile version :
- Can we reduce the spacing between the language / currency links and their arrow?
- Can we align the selectors row to the Log in icon?
![Group 6869](https://user-images.githubusercontent.com/95925370/214018833-cad36994-e725-47ff-a2f1-9592481cfda3.jpg)
- Can we reduce the spacing between the log in row and the selectors row? (Illustrated In orange here)
![Group 6868](https://user-images.githubusercontent.com/95925370/214018925-9bf30ddb-8277-4f35-8d8f-051f0467fb16.jpg)
- If mobile resolution is super narrow, the layout broken (version on the left) can we fix the spacings and alignments?
<img width="778" alt="Capture d’écran, le 2023-01-23 à 11 28 03" src="https://user-images.githubusercontent.com/95925370/214019043-879cf9c7-8c8c-43e0-827e-d05310a29968.png">
@duygukalaycioglu do you agree?
