### ISSUE TITLE
[PDP] Buy button disabled while "Continue selling while out of stock"

### ISSUE THREAD

**Issue by DennisNEOLYMP** [Shopify/dawn#2246]
## Describe the current behavior
Products do have "Continue selling while out of stock" enabled, but buy button is disabled.

## Describe the expected behavior
Button should be clickable

## Version information (Dawn, browsers and operating systems)
- Dawn Version: 7.0.1

## Possible solution
Check for inventory policy in buy-buttons.liquid
`and product.selected_or_first_available_variant.inventory_policy != 'continue'`

![image](https://user-images.githubusercontent.com/81567531/214049991-c4e41738-ca01-4f19-a480-fdff4c41e0d8.png)

**Comment by DennisNEOLYMP** [comment]
Thanks for your offer.
When changing variants, the button is correctly enabled.
When I directly enter the variants URL the button shows out of stock.

![image](https://user-images.githubusercontent.com/81567531/214533385-03e3ee63-a478-4d02-a2a5-4ec8a958390c.png)

**Comment by DennisNEOLYMP** [comment]
Thanks for your offer.
When changing variants, the button is correctly enabled.
When I directly enter the variants URL the button shows out of stock.

![image](https://user-images.githubusercontent.com/81567531/214533809-8f1d293c-a93a-44de-bb77-0ca7ef035d98.png)

**Comment by ludoboludo** [comment]
@DennisNEOLYMP do you happen to use some of our recent updates that weren't released yet ? And not the version from the theme store ? 
Cause I'm able to replicate on our current `main` branch but not when I test on the version of Dawn I get from the theme store.

**Comment by DennisNEOLYMP** [comment]
I did use the most recent commit. 
When testing on official, after you mentioned it, I went by the theme store.

**Comment by ludoboludo** [comment]
Yeah so I think I found the issue and created a PR with a fix. But I will need to get my colleagues to check to make sure it's the right fix for it. Thanks a lot for bringing it up @DennisNEOLYMP 🤗 

It will prevent us from potentially shipping a new theme version with that bug in it.
