### ISSUE TITLE
Support shopify hosted video in video section

### ISSUE THREAD

**Issue by kmeleta** [Shopify/dawn#2247]
Add support for shopify hosted video (via video setting type) to existing video section.

https://www.figma.com/file/hQiYDulTbQCKxBqIbtCpWZ/Multirow-and-Shopify-hosted-video-explorations?node-id=610%3A23896&t=u195pyrwPwLIjTFE-0

Edit: Updated settings content
<img src="https://screenshot.click/video-settings-final_v3_FINAL-1.png" width="200" />

**Comment by bredowmax** [comment]
May be related to https://github.com/Shopify/dawn/issues/1687

**Comment by danielvan** [comment]
@kmeleta, we had some feedback around the settings order and definition here. I've built an example image with the rationale behind the choices and our desired approach. Let me know if it works, or if you'd like align.

[Image](https://screenshot.click/13-40-g2933-m69c2.png)

cc @katycobb

**Comment by kmeleta** [comment]
Content decisions have changed. Aligned with Dan, Melissa, and Katy on these decisions, at least until applicable bugs/behaviors in the video setting are resolved.

**Updated settings/content**
<img src="https://screenshot.click/video-settings-final-v3_FINAL.png" width="200"/>
