### ISSUE TITLE
Collection Banner Section - Remove margins

### ISSUE THREAD

**Issue by jendunnam** [Shopify/dawn#225]
Remove the margins around the image. On [mobile](https://screenshot.click/16-26-1vwq0-dxht8.png), it should be flush on the sides and bottom. On [desktop](https://screenshot.click/16-27-ohj5j-kf9o2.png), it should be flush on top/bottom and side.

**Comment by tauthomas01** [comment]
Clarification: The hope is for the image to reach top, bottom and right edge. The text would remain where it is.

Expectation
Mobile
[![alt](https://screenshot.click/22-42-o3ne0-6xemg.png)](https://screenshot.click/22-42-o3ne0-6xemg.png)

Desktop
[![alt](https://screenshot.click/22-39-wdmpj-7na1z.png)](https://screenshot.click/22-39-wdmpj-7na1z.png)

**Comment by nicklepine** [comment]
Clarification: 

This is what we'd like to achieve on desktop: 

https://screenshot.click/21-02-28f7g-unzcx.png
