### ISSUE TITLE
Dynamic checkout/ "Buy now" buttons are not loading when logged in as B2B customer

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#2273]
When logged in as B2B user, dynamic checkout/ "Buy now" buttons are not loading on storefront

`spb.en.js` which handles payments is throwing an error for B2B users.

<img width="1505" alt="Screenshot 2023-02-01 at 4 18 56 PM" src="https://user-images.githubusercontent.com/3710548/216190296-2002f942-baec-438c-9a80-4fd18e18c436.png">

_Originally posted by @KaichenWang  in https://github.com/Shopify/dawn/pull/2251#discussion_r1093845254_

**Comment by tibo-shop** [comment]
B2B customers are intentionally not shown the "Buy now" buttons.
