### ISSUE TITLE
Image looks duplicated when `Click and hover` on image zoom is selected

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#2278]
## Describe the current behavior
When you select `click and hover` on image zoom on a transparent image, the image looks like its duplicated: https://screenshot.click/02-19-pssv9-s19g8.mp4
This seems to happen only with png

## Describe the expected behavior
The img should not look duplicated

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 8.0.0
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Possible solution
- we could potentially change the opacity of the image below to 0 
- hide the image below, since we can't force a background colo

**Comment by Duendedawid** [comment]
.
