### ISSUE TITLE
blocks are limited to only 12 even though there is max_blocks set

### ISSUE THREAD

**Issue by basylvalencia** [Shopify/dawn#228]
**Describe the current behavior**
All the components are limited to 12 blocks
**Describe the expected behavior**
When there is a max_blocks set to more than 12, it should allow to add blocks more than 12.
**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**
![Screen Shot 2021-07-20 at 10 02 04 PM](https://user-images.githubusercontent.com/57985026/126337561-64f12295-0574-400b-b230-b1d2c8ded2d1.png)

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by andershagbard** [comment]
This is a [limit in Shopify](https://shopify.dev/themes/architecture/sections/section-schema#max_blocks) and not specifically the theme.

Not sure why they implemented this limit. Seems like a bad idea, which just limits themes.

**Comment by dan-menard** [comment]
Closing. Anders is correct that this isn't an issue we can address in Dawn, and the limit has since been increase to 50.
