### ISSUE TITLE
[Featured product] Alignment between share button and view details is off

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#2289]
## Describe the current behavior
When I add a feat. product section, the alignment between the share button and view details is off and looking odd

## Describe the expected behavior
They should either be properly aligned or on a different "row" from each other. 

3 Scenarios to consider
- [x] Align when product is empty (placeholder image) 
- [x] Align when product is selected (with image)
- [x] Align when product is selected (without any image) 

Solution should include

- [x] Mobile, tablet, desktop

## Version information (Dawn, browsers and operating systems)
- Dawn Version: 9.0.0

## Additional context/screenshots

<img width="911" alt="Screenshot 2023-05-26 at 9 12 37 AM" src="https://github.com/Shopify/dawn/assets/107572834/93839760-bab9-4907-a56c-bc57c7417c7a">
<img width="427" alt="Screenshot 2023-05-26 at 9 12 50 AM" src="https://github.com/Shopify/dawn/assets/107572834/421c1d9e-4a04-4d39-becf-efa8f6ce7f99">
<img width="446" alt="Screenshot 2023-05-26 at 9 13 00 AM" src="https://github.com/Shopify/dawn/assets/107572834/6b57e094-e29b-4a6b-b40c-05596160cc97">
<img width="933" alt="Screenshot 2023-05-26 at 9 13 09 AM" src="https://github.com/Shopify/dawn/assets/107572834/78ebee14-a8bc-435d-a64f-bb2d4fb36378">

**Comment by YoannJailin** [comment]
Hello @ludoboludo ! To solve this i would simply align the Share link to the View details link. View screenshots here : 
![Frame 3186](https://github.com/Shopify/dawn/assets/95925370/25d7b3a9-3a8c-4349-91f7-fd81db9aab40)
![Frame 3185](https://github.com/Shopify/dawn/assets/95925370/f1d95e75-c772-45e5-95bf-d2c3a223fa64)
![Frame 3184](https://github.com/Shopify/dawn/assets/95925370/b774ead1-779a-4da5-b07c-0b3fd9ab428f)
![Frame 3183](https://github.com/Shopify/dawn/assets/95925370/28bbcfaf-73cb-45d3-9669-b5a98c98d060)
