### ISSUE TITLE
Product card spacing

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#231]
Issue:

There is too much space between name and price. Additionally, on smaller screens this makes is unclear what text info pertains to what card / image. 

![image](https://user-images.githubusercontent.com/8127145/126494369-17211781-839a-4648-8599-93f06fd3105c.png)

**Comment by Oliviammarcello** [comment]
The spacing requires a few tweaks:
- [ ] The space between the image and the first element should be 2rem
- [ ] Space between vendor and title should reduce from 1.1rem to 0.7rem
- [ ] The space between title and price should change to 1.3 rem

[Screenshot before](https://screenshot.click/21-30-xg0oe-mm5s3.png) | [Screenshot after](https://screenshot.click/21-28-dpp33-8ulov.png)

**Comment by Oliviammarcello** [comment]
One more update based on recent feedback:
- [ ] In the cart the strikethrough price is smaller than the final price. Can we update the product card strikethrough price to match. [Screenshot.](https://screenshot.click/21-49-qio5t-eqk39.png)
