### ISSUE TITLE
[Header] Reveal dropdown from same direction

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#2335]
- [ ] The dropdown doesn't reveal from the same direction of the menu. Menu items, reveal from the top; and selectors reveal from the bottom. I suspect this is due to reusing the same component for when they reveal in the footer. ([Video reference](https://screenshot.click/27-04-610s6-2dgj7.mp4))

_Originally posted by @melissaperreault in https://github.com/Shopify/dawn/pull/2258#pullrequestreview-1315926642_

**Comment by ludoboludo** [comment]
This was fixed in the original PR. I made tweaks to tackle it 👍 [video](https://screenshot.click/13-03-1v22s-yr5xn.mp4)

Unless I'm missing something 🤔
