### ISSUE TITLE
Duplicate IDs in navigation menu

### ISSUE THREAD

**Issue by ethanclevenger91** [Shopify/dawn#2336]
## Describe the current behavior
If two different top-level navigation items both have second-level items with third-level items at the same position, the `details` elements in the second-level items will have duplicate IDs in the tablet/mobile menu.

## Describe the expected behavior
HTML elements should not have duplicate IDs

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 8.0.0
- Firefox Version 110
- macOS Version 13.2.1

## Possible solution
Add top-level position to the ID generation strategy

## Additional context/screenshots
Issue can be seen here by running [the axe browser extension test ](https://www.deque.com/axe/) on [this site](https://sterner-stuff-test.myshopify.com/)
password - rtohre

**Comment by kmeleta** [comment]
Yep I spotted the existing duplicates working on that ticket. Should be fixed when https://github.com/Shopify/dawn/pull/2506 merges
