### ISSUE TITLE
Adjust Multi Column Section Line Height

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#237]
**Describe the current behavior**

Line height on multi column is 1.8. Should be 1.5 (same as Image with Text) to be consistent. Visually feels too high at the moment. 

![image](https://user-images.githubusercontent.com/8127145/126504673-c55c1d41-0211-47cc-bea5-4b0690b4035f.png)

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0

**Comment by melissaperreault** [comment]
I would add that we could perhaps reduce the width when they are 2 column, I could help the legibility of each columns.

**Comment by melissaperreault** [comment]
Sharing the visual reference of the enhancement we can make related to my comment above.

![](https://screenshot.click/21-07-8faou-9qnw3.png)
