### ISSUE TITLE
[Image with text] Reveal in cascade for overlap content layout

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#2375]
### Context
Recap of what I propose
- No overlap content layout: Reveal image and content container background together, than the content blocks
- Overlap content layout: Reveal each side individually

>@melissaperreault, @kjellr this sounds like a great idea and I don't image it would be difficult to do. However, we don't have the "cascading" CSS in this PR, and adding that would change the scope a bit. The CSS that will handle delayed animation will be part of [this PR](https://github.com/Shopify/dawn/pull/2372) (draft) and will need to be reviewed and tested before we can introduce it into other sections.

_Originally posted by @metamoni in https://github.com/Shopify/dawn/issues/2362#issuecomment-1461494881_

**Comment by kjellr** [comment]
Sure, that sounds good for now. We can always re-open later if we'd like. 👍
