### ISSUE TITLE
Complementary products block is not shown when added on theme editor

### ISSUE THREAD

**Issue by FCalabria** [Shopify/dawn#2424]
## Describe the current behavior

Go to the customization screen, select the product page. On the "product information" section, add the "complementary products" block. The loading bar will appear, but after it finishes reloading the complementary products are still not visible. Hitting "save" makes the block visible.

## Describe the expected behavior

"Complementary products" block appears when added

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 8.0.1
- Chrome Version 111
- macOS Version 13.2.1

## Possible solution

¯\_(ツ)_/¯

## Additional context/screenshots

It does not happen 100% of the time, there might be some race condition or other requisite that I cannot figure out.

https://screenshot.click/Complementary_block_not_rendering_on_first_add.mp4

cc: @ludoboludo

**Comment by kimberlyoleiro** [comment]
Hey @FCalabria, I can't reproduce. Can you please resubmit a video with the full flow of configuring your complementary products on the admin + a link to your store so we can narrow down where the problem is

**Comment by FCalabria** [comment]
Hi @kimberlyoleiro, thanks for following up and sorry for taking so long to answer. I cannot reproduce it anymore, you might have solved it at some point as part of other changes. I'll close the issue.
