### ISSUE TITLE
[Multirow] Add cascading fade in on scroll animation

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#2426]
## Summary

Add cascading fade in on scroll animation for the Multirow section based on explorations made in https://github.com/Shopify/dawn/pull/2141. Pair with UX to define the ideal strong outcome. It should follow what we did for Image with text.

## Details

- [ ] If a color background is present on the section, it should not animate. 
- [ ] Reveal content in cascade for a more interesting flow, adapt if we need to reduce the noise.
- [ ] The setting will be applied from the new `Animations` theme setting category, below `Layout` and above `Buttons`. The new setting label is offered via a checkbox and its label is; `Reveal sections on scroll`. 

![](https://screenshot.click/14-19-ly06t-od5uh.png)

**Comment by ludoboludo** [comment]
This PR that was merged a couple weeks ago took care of this 👍 
https://github.com/Shopify/dawn/pull/2526
