### ISSUE TITLE
Unable to add line item properties

### ISSUE THREAD

**Issue by perryraskin** [Shopify/dawn#243]
These are the HTML inputs I am using on the PDP:

```
<product-form>
   <form method="post" action="/cart/add" id="product-form-template--29384234754__main" accept-charset="UTF-8" class="form" enctype="multipart/form-data" novalidate="novalidate" data-type="add-to-cart-form">
         <div id="cart-line-items">
            <input class="item-contains" type="hidden" name="properties[_item_0]" value="item0-data-here">
            <input class="item-contains" type="hidden" name="properties[_item_1]" value="item1-data-here">
         </div>
   </form>
</product-form>
```

## Current Behavior

Adding line items properties via HTML inputs within the `AddToCart` form does not carry over to `cart.json` upon adding product to the cart.

**Current Cart Screenshot:**
![image](https://user-images.githubusercontent.com/17967465/126542578-86dd02a0-8fca-4e46-9ed4-ad5557b50357.png)

**Current `Cart.json`:**

```
...
"items":
      [
           {
              "id": 40230556827839,
              "properties": null, 
               ...
           }
      ]
  ...
```

## Expected behavior

**Expected Cart Screenshot:**
![image](https://user-images.githubusercontent.com/17967465/126542517-8a27be84-64ed-41a9-9968-2132b9723cf5.png)

**Expected `Cart.json`:**

```
...
"items":
      [
           {
              "id": 40230556827839,
              "properties": {
                  "_item_0": "item0-data-here",
                  "_item_1": "item1-data-here",
               }, 
               ...
           }
      ]
  ...
```

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

## Possible solution

This works as expected in other themes (like Debut). This seems like a bug, so I am led to believe that the same functionality needs to be implemented into Dawn as it is in Debut.

The current docs for the Dawn theme are the same as they are for the Debut theme. It seems that either the docs need to be updated to explain the proper usage of inputs for line item properties, or that the Dawn theme has a bug that is blocking this functionality from working.

**Comment by muriloshimizu** [comment]
I'm also trying to pass data via line item properties, but as the OP mentioned, it's not working.

**I commented out the entire product-form.js and it worked**, so I believe the problem is in the javascript. Would appreciate some help here, as I'm not as good with JS. Ty!

**Comment by perryraskin** [comment]
More specifically, it's clear that the data, variable `parsedState`, that is returned via the `fetch` request to the `/add/cart` API is missing the `properties`, and the value is `null`.  The following code block is where it happens. Without this file, however, we do not get the nice added to cart animation on the top right. Furthermore, commenting out only this code block breaks the entire add-to-cart action.

```
fetch(`${routes.cart_add_url}`, { ...fetchConfig("javascript"), body })
      .then((response) => response.json())
      .then((parsedState) => {
        this.cartNotification.renderContents(parsedState);
      })
      .catch((e) => {
        console.error(e);
      })
      .finally(() => {
        submitButton.classList.remove("loading");
        submitButton.removeAttribute("disabled");
      });
```

The `body` object that is passed to the API has `properties` defined as expected, but the value is lost once the API returns the data. I tried to implement a workaround by generating the `properties` object manually and assigning it to `parsedState.properties` but that did not seem to have any effect.

I do hope a fix can be implemented here soon!

**Comment by perryraskin** [comment]
@heyjonmanning  I'm not 100% sure but I believe the property values need to be in an HTML `input` element. So instead of `<textarea>` try using `<input type="hidden">`. Since you mentioned it didn't even work when you commented out the entire `product-form.js` file, this is the only thing I can think of.

**Comment by heyjonmanning** [comment]
It appears that I was missing the form attribute from the line item property. Works with textarea just as well as a single line input. Thanks for spelling that out to me @carlsmith-wow and thank you @perryraskin for the revised product-form.js!
