### ISSUE TITLE
Related Products pricing updating when variant is selected with wrong values

### ISSUE THREAD

**Issue by graemec23** [Shopify/dawn#2449]
## Describe the current behavior
When a product variant is selected on a product view, the pricing of all the products in the related products are changed to what the product variant is.

## Describe the expected behavior
When selected a variant in a product view, the related product prices dont change.

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 8.0.0
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Additional context/screenshots

<img width="1357" alt="Screenshot 2023-03-18 at 11 10 49" src="https://user-images.githubusercontent.com/1915592/226102158-81639db7-db40-4c38-8623-43c897336795.png">

<img width="1353" alt="Screenshot 2023-03-18 at 11 11 06" src="https://user-images.githubusercontent.com/1915592/226102177-86eeb935-12cc-4cbb-936a-e1a95d19faf0.png">

**Comment by kimberlyoleiro** [comment]
Hey @graemec23 , we appreciate you taking the time to report this issue. Unfortunately, we cannot reproduce it in the latest version of our codebase and haven't heard back from you in some time. We'll be closing this issue, but please let us know if you have any other feedback.
