### ISSUE TITLE
[Featured collection] Reveal similar sections consistently

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#2489]
> * [ ]  As we reveal similar sections, the relationship of the animation between the section Title and the Cards is difference from Featured collection section and Multicolumn section. The first one will reveal the title sooner than the Multicolumn one ([Video example](https://screenshot.click/03-26-te17h-3z96l.mp4))

It only happens when the previous section is a Featured collection, and thus has more to do with refining _that_ section rather than this one (see video below).

https://user-images.githubusercontent.com/22390758/229740229-c46d2639-3366-4098-9246-a3c91adb88b1.mp4

I think the delay is caused by the `data-cascade` attribute on the Featured collection, which enables the cascading animation. For this to work properly we'd have to remove that attribute when it's not necessary, which we're not currently doing because we'd have to know whether we're in mobile/desktop view.

_Originally posted by @metamoni in https://github.com/Shopify/dawn/issues/2409#issuecomment-1495600019_

**Comment by ludoboludo** [comment]
I don't see this as being an issue anymore. Are we still able to replicate ? When I try on an up to date branch I get this: 

https://user-images.githubusercontent.com/28613840/234381347-3fcbf330-a554-4692-95ff-87138a09b459.mp4

**Comment by melissaperreault** [comment]
I cannot replicate anymore! 🎉
