### ISSUE TITLE
Quick view option on top of quick add

### ISSUE THREAD

**Issue by ericyew** [Shopify/dawn#2504]
## Describe the enhancement you'd like
It is mentioned in the theme store that this theme supports quick view. However, when actually configuring this theme, I do not see any option to enable quick view (unless I am missing something). The only option is to enable quick add, which only enables an `Add to cart` button to the product cards. Would be great if an option was added to add quick view.

## Describe alternatives you've considered
Using the `Quick Add` option or adding my own code to the theme

## Additional context/screenshots
![image](https://user-images.githubusercontent.com/16659756/230856492-9333680f-194f-4724-986b-abe983e9121b.png)
![image](https://user-images.githubusercontent.com/16659756/230857217-63a3d382-8de5-4a94-bffd-c92a359e9200.png)

**Comment by kimberlyoleiro** [comment]
Thank you for submitting this issue. The quick view is prompted if there is more than 1 variant to select. If there are no options (ie size or colour), we deemed it appropriate to add to the cart directly. We'll be closing this issue, but please feel free to contact us if you have any other questions or suggestions.
