### ISSUE TITLE
Invalid gtin format in Schema.org data (product page)

### ISSUE THREAD

**Issue by willbroderick** [Shopify/dawn#2548]
## Describe the current behavior
Add the barcode `012345678912` to a variant.
View the product page.
Check validity of the schema.org structured data on that page.

You'll see an error in the console log.
<img src="https://user-images.githubusercontent.com/1590737/233329076-e0d5dcce-fb19-46b1-91fc-b0ecde368e73.png" width="600">

## Problem
Here's an example of what's produced by Dawn:
```
{
"@type" : "Offer",
"sku": "1230",
"gtin12": 012345678912,
"availability" : "http://schema.org/InStock"
}
```

Two issues:
1. JSON parsers do not like numbers beginning with 0. This causes Facebook (and other parsers) to fail parsing this.
2. gtin expects text, not a number: https://schema.org/gtin12

## Version information (Dawn, browsers and operating systems)
- Dawn Version: 9.0.0

## Possible solution
https://github.com/Shopify/dawn/blob/main/sections/main-product.liquid#L553
Change `{{ variant.barcode }}` to `{{ variant.barcode | json }}`
The schema.org validator seems happy with this.

**Comment by naxorn** [comment]
@lougoncharenko FYI: The #2804 fix only addresses featured-product.liquid, but main-product.liquid also needs updating...
