### ISSUE TITLE
[Header] Fix default UI for dropdown and mega menu

### ISSUE THREAD

**Issue by YoannJailin** [Shopify/dawn#2579]
We would like to fix the default UI for Mega menu and Dropdown visible on desktop.

Mega menu

- [x] If Body font selected in theme settings contains a bold option, apply it on L2.
- [x] If not, apply bold on L2 using CSS
- [x] All links have the same size (L1/L2/L3)
- [x] Fix vertical paddings in the menu : 30 pixels above first row / 30 pixels between rows / Bottom padding is always 30 pixels.
- [x] Make sure mega menu opens above header (same spacing between the L1 clicked link and a dropdown)

Dropdown

- [x] Fix vertical paddings in the menu : 20 pixels on top and bottom
- [x] When opening L3 dropdown : 20 pixels at top and bottom
- [x] Remove indent space on L3
- [x] Add hover / clicked state on L3

[Figma file](https://www.figma.com/file/LlopBqbeLND3IQQvYMjVbn/%F0%9F%9A%A7-Navigation-UX-%E2%80%93-Dawn-2023?node-id=2665%3A141093&t=iRLqk6X2SyqlO2OY-1)

**Comment by danielvan** [comment]
Left some minor comments on Figma.

**Comment by stefanmomcilovic** [comment]
I would also recommend the ability for a mega menu to add images in dropdown something like I created here
<img width="1422" alt="Screenshot at Apr 27 13-55-59" src="https://user-images.githubusercontent.com/52540681/234854612-baf14b8d-3fa8-4d46-afd8-fe92b94fe2ad.png">
