### ISSUE TITLE
Ability to remove the zoom feature on product page

### ISSUE THREAD

**Issue by carlsmith-wow** [Shopify/dawn#258]
**Describe the enhancement you'd like**
A checkbox on the product page to enable/disable the image zoom functionality on the product page.

**Describe alternatives you've considered**
An alternative is to go into the liquid files and try to find where this functionality is enabled.

**Comment by bredowmax** [comment]
Yes, please! See also #168

**Comment by melissaperreault** [comment]
This is now possible with this change https://github.com/Shopify/dawn/pull/1983
