### ISSUE TITLE
[Featured Product] Sections Rendering API + Collection Metafield (product type)

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/dawn#2590]
## Describe the current behavior
I discovered a very specific bug that is impacting Dawn, as well as all other free, premium and custom themes. This bug is related to an issue with the Sections Rendering API combined with a product type metafield that belongs to a collection.  When using a dynamic source metafield to populate the **Featured Product** section _**only on the collection template**_ all calls Dawn (or any theme makes) to the Sections Rendering API will omit the product and return default example product details and $19.99 price.
<img width="357" alt="image" src="https://user-images.githubusercontent.com/454095/235207080-c7096bc4-bace-4d12-b58d-ff8f6094aeda.png">

## Describe the expected behavior
The Featured Product section should render consistently regardless if its source is a metafield or product when added to a Collection template.

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 9.0.0
- Chrome Version 112.0.5615.137 (not a browser related bug)
- macOS Version 13.0.1

## Possible solution
Investigate bug with the Sections Rendering API

## Additional context/screenshots
Scenarios where the bug does not occur:
- When directly assigning a product to the Featured Product section in a collection template.
- Using a product type metafield as the dynamic source of the Featured Product section in a product template.

### Steps to recreate
1. Create a new development store populated with test products
2. Settings > Custom data, create a new Collection metafield definition with a content type of Product
3. Edit any collection to add a product to the new featured product metafield
4. Install a fresh version of Dawn
5. Add a Featured Product section to the collection template
6. Select the metafield as the dynamic source of the product

### Video screen capture of the steps and bug
https://user-images.githubusercontent.com/454095/235213196-51161506-b82c-4605-ad48-3c0ddd62d992.mp4

**Comment by kimberlyoleiro** [comment]
Hey @jonathanmoore, thanks for flagging. Can you please be more explicit with the current vs expected behaviour? I'm afraid I don't fully understand what `default example product details` means?

>Dawn (or any theme makes) to the Sections Rendering API will omit the product and return default example product details and $19.99 price.
