### ISSUE TITLE
UI Polish Review: Image with Text

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#26]
Final polish review:

- [x] The image alignment settings should be removed from this section
- [x] The spacing between elements is a bit tight. On desktop can we [follow this](https://screenshot.click/21-01-cr0rx-gucuu.png)
- [x] The colour system dropdown should say "Background 1" instead of "Baseline"
- [x] Remove "Secondary button style" checkbox

**Comment by tauthomas01** [comment]
Hello @martinamarien , I took at a look at this task last week and Olivia just revised the item.

It looks like you are assigned to Image with text polish according to the project board so I'll let you take over.

**Comment by tauthomas01** [comment]
Update: @martinamarien I looked at the board and it looks like I'm assigned again. Sorry for the notice.
