### ISSUE TITLE
Product section that supports add to cart / quick checkout

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#263]
**Describe the enhancement you'd like**
A clear and concise description of what you want added to Dawn. Add any considered drawbacks.

On landing pages for specific products we want to have a "product section" that let's you add to cart and checkout without having to go into the product page. 

**Describe alternatives you've considered**

The alternative is to force the customer through the product page.

**Additional context/screenshots**
Maybe a screenshot or design?

![image](https://user-images.githubusercontent.com/13047497/126949595-efda950a-71a8-4cee-8dc1-a7ed61f0b339.png)

**Comment by bredowmax** [comment]
Related to #36
