### ISSUE TITLE
Dawn theme exploded 

### ISSUE THREAD

**Issue by Bycarterblaine** [Shopify/dawn#2650]
Updated very basic CSS, tested, worked properly, saved.
Woke up and logged in today to a disaster. 
No nav bar, missing content, and super spaced out.
Even though my coding yesterday was just a very basic css thing and worked fine.

Just looking to fix it, no duplicate theme. 

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 9.0.0
- Chrome Version 108.0.5359.124
- macOS Version 13.1

**Comment by ludoboludo** [comment]
This looks like a specific issue to the environment and custom code used. I will close the issue.
