### ISSUE TITLE
Announcement bars no longer stack, creating bad experience for stores that use stacked announcements

### ISSUE THREAD

**Issue by mbarnes-km** [Shopify/dawn#2701]
### Discussed in https://github.com/Shopify/dawn/discussions/2700

<div type='discussions-op-text'>

<sup>Originally posted by **mbarnes-km** June  8, 2023</sup>
This discussion is in regard to "Announcements slideshow #2394" https://github.com/Shopify/dawn/pull/2394
Please forgive me for any mistakes I make here, as I am new to github.

I manage a shopify store for a merchant and we have been happily using Dawn for a while now.  One of our favorite features is the stacked announcement bars.

I was horrified to see that the announcement bars no longer stack in Dawn 10.

The pull request linked above has absolutely no information in the section titled "Visual impact on existing themes" which is abhorrent because it has a HUGE impact on our theme - it removes a feature we rely on.

Additionally the pull request says that it "Fixes [#398](https://github.com/Shopify/themes/issues/398)." and as you can see from clicking the link, there is no issue #398 to be found.

I'm wondering why this was done, and if anything can be done to fix it.  
</div>

**Comment by naxorn** [comment]
You can still stack in v10, but the Dawn team changed it a bit.  Now you need to add multiple announcement bars with each one having only a single announcement, such as

![image](https://github.com/Shopify/dawn/assets/67534064/d90f303f-c845-4bfa-bbba-9c0414655d22)

They also allow you to specify custom announcement colors using the color schemes, which is a nice addition.

**Comment by mbarnes-km** [comment]
@naxorn 
My theme does not allow more than one announcement bar, as far as I can tell:
![image](https://github.com/Shopify/dawn/assets/135998159/2043776a-e038-4cfd-8d24-6584527861ec)

**Comment by mbarnes-km** [comment]
I just installed a brand new Dawn 10 theme from the store to double check this - I am limited to one announcement and one header section - neither can be deleted and I cannot add more announcement bars:
![image](https://github.com/Shopify/dawn/assets/135998159/e04a6c2f-c93f-4273-a28a-6066942c9963)

**Comment by mbarnes-km** [comment]
@naxorn 
What does your header-group.json look like?
I was able to kludge-in another announcement bar by copying sections and adding numbers to the end, so now I have this:
![image](https://github.com/Shopify/dawn/assets/135998159/98613170-f352-4648-a068-3aa68f34da55)
Ugly, but it works for now.

**Comment by naxorn** [comment]
Yep, that is a way to do it.  If you want to get the true theme editor experience, you can edit your code manually by following the changes in the commit [Allow multiple announcement bars in Header group](https://github.com/Shopify/dawn/commit/6118e899ea257bab48a985fbb72078d86beed259).  You really only need to change the schema in the [announcement-bar.liquid](https://github.com/Shopify/dawn/commit/6118e899ea257bab48a985fbb72078d86beed259#diff-250e86a261baea4f8f30f09dbd328ffcb0b7d5d73366b8376fd844a02e195a93).  Also, for simplicity, in the presets change [L154](https://github.com/Shopify/dawn/commit/6118e899ea257bab48a985fbb72078d86beed259#diff-250e86a261baea4f8f30f09dbd328ffcb0b7d5d73366b8376fd844a02e195a93R154) from 
```json
"name": "t:sections.announcement-bar.presets.name"
```
to
```json
"name": "Announcement bar"
```
Then you don't need to update the translation schema too.

When the next Dawn version is released, your code modifications will be removed, but it shouldn't matter as this feature should be in the next version anyway.

**Comment by mbarnes-km** [comment]
Thanks very much @naxorn you've been a great help. 
I definitely want the true theme editor experience so I'm really glad you followed up on this.

**Comment by naxorn** [comment]
@mbarnes-km Sorry, I keep forgetting that what's in ```main``` does not necessarily match with a specific release version.  I maintain a custom theme and only develop against ```main``` so each release I take a guess which commit should correspond to which version of Dawn.  Prior to v8.0.1 the tags matched commits in ```main```, but they've since changed that for the past three releases...
