### ISSUE TITLE
Unable to format file header.liquid error

### ISSUE THREAD

**Issue by Made4Uo** [Shopify/dawn#2717]
## Describe the current behavior
There is an error  Start line 184, and end line 184 in theme editor that appears when trying to save changes in the header file.

## Describe the expected behavior
No errors when saving

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 10.0.
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Possible solution
Change the if-statement for sticky header to capture instead.
Replace code: `{% if section.settings.sticky_header_type != 'none' %}sticky-header{% else %}div{% endif %}`
New code:
`{% capture sticky_header %}
  {% if section.settings.sticky_header_type != 'none' %}sticky-header data-sticky-type="{{ section.settings.sticky_header_type }}"{% else %}div{% endif %}
{% endcapture %}`
And use `{{ sticky_header }}` instead of if-statement

## Additional context/screenshots
![image](https://github.com/Shopify/dawn/assets/108191745/580b989e-5b0c-485c-b6ee-0c07657b2ef4)

**Comment by kmeleta** [comment]
I couldn't replicate this issue on a fresh install of Dawn 10.0.0 or on the main branch.
