### ISSUE TITLE
[Announcement Bar] Improvements

### ISSUE THREAD

**Issue by kimberlyoleiro** [Shopify/dawn#2785]
## Describe the enhancement you'd like

This ticket is a quick-wins follow-up to: https://github.com/Shopify/dawn/issues/2705 

### CHANGE 1: Timing

- [ ] Change minimum time to 3s
- [ ] Keep default 5s

### CHANGE 2: Auto-Slide Not Working on Mobile Confusion

- [ ] Change text to "Auto Slide on Desktop Only"

<img width="325" alt="Screenshot 2023-07-06 at 2 14 14 PM" src="https://github.com/Shopify/dawn/assets/107572834/301596b8-a311-4199-a509-8121b3f319f1">

**Comment by katycobb** [comment]
@kimberlyoleiro a followup: we've pivoted the copy [in the PR](https://github.com/Shopify/dawn/pull/2787) to just `Auto-rotate on desktop` since we have an announcements heading - forgot about that and it wasn't shown in the screenshot above 😅
