### ISSUE TITLE
Drop-shadow on buttons

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#279]
**Describe the current behavior**
Once a button is pressed there is an odd drop shadow persisting on the button that should not be there. 

- Dawn Version: 1.1.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

Seems to happen on all buttons. 
Recording: https://screenshot.click/21-37-x6se4-165gb.mp4

![image](https://user-images.githubusercontent.com/8127145/127223452-ea8b3053-4306-4bf0-ae93-d5a7654e4a73.png)

![image](https://user-images.githubusercontent.com/8127145/127223761-21cac357-b3c2-4279-9986-70a1d268b9f6.png)

![image](https://user-images.githubusercontent.com/8127145/127223770-8db24d27-7129-4040-889e-ca98fe05925d.png)

**Comment by tyleralsbury** [comment]
Added low effort.  If this is not a browser behaviour, it should be pretty simple to fix.
