### ISSUE TITLE
Add shop logo to Gift Card Template

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#28]
UI polish review:

- [x] The text seems to be hardcoded instead of taking the theme instead of taking the Text colour. [Screenshot](https://screenshot.click/21-08-rks94-urgo5.png)
- [x] The "copy code" text doesn't have the same text styling that other links have. It should have a 3px offset for the underline and the stroke should increase from 1px to 2px on hover. [Video](https://screenshot.click/21-14-0gmvi-6i8i2.mp4)
- [x] On desktop, the gift card image is a bit smaller than what it shown on figma. It should be 570px wild. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=2692%3A2656)
- [ ] Add logo picker to gift card template settings.

**Comment by tauthomas01** [comment]
Hi @KaichenWang , I took over this task before the meeting began and saw that you were assigned for this, so I started to add some changes (and checked the checkbox todo in the description), feel free to take over with branch `feature-gift-card-ui`.

**Comment by nicklepine** [comment]
Looks like we never added the logo picker. @LucasLacerdaUX mentions we would need to convert this part of the template into a section in order to be able to have settings.  Let's do it.

**Comment by xJon** [comment]
Improving the gift card screen would be great, the default cannot be modified without manual code changes.
