### ISSUE TITLE
Github integration

### ISSUE THREAD

**Issue by timdonaldson** [Shopify/dawn#280]
**Describe the enhancement you'd like**
This isn't so much a Dawn theme question but more of a Online Store 2.0 + Github integration question that I've encountered as I begin to work with Dawn.

I have a number of clients with multiple regional stores that share the same theme but have different settings_data.json files. This wasn't a problem with ThemeKit because we could exclude files in the config.yml file.

But as I begin to migrate stores to use the new Shopify Github and Online Store 2.0 functionality I'm not sure how to maintain a theme across multiple stores with different theme settings and json data.

**Describe alternatives you've considered**

Adding the **templates/*** to **.gitignore** removes the files from the theme on Shopify so I'm not sure if there is any alternative to retain json data files on the Shopify store theme, but have them untracked in the git repo

**Additional context/screenshots**
Maybe a screenshot or design?

**Comment by kenji-browcode** [comment]
I have the same and perfectly exact question!

I did spend some time testing different scenarios, with branches and all... but decided that it would be easier to NOT use the github integration. Keen to hear if anyone has an idea of how it can work.

**Comment by celsowhite** [comment]
@timdonaldson can you use a [.shopifyignore](https://shopify.dev/themes/tools/cli#excluding-files-from-shopify-cli) file in the root and ignore all the template json files?

This is actually my main question about Dawn and Online Store 2.0 at the moment. I'm not sure the proper workflow for pushing code without overwriting json data between themes.

- When pushing to a theme I'll overwrite the settings that a client has input using the customizer.
- If I use .shopifyignore, those files won't appear in my 'development theme' when I do 'shopify theme serve'.

**Comment by timdonaldson** [comment]
@celsowhite that should work with Shopify CLI similar to the previous Theme Kit solution but I don't think it would have impact on a Github theme

**Comment by gregjotau** [comment]
@timdonaldson this issue should be closed as to not have unnecessary open issues.

**Comment by timdonaldson** [comment]
But it is still an issue so I'm not sure why I would close it @gregjotau?

**Comment by gregjotau** [comment]
I might be wrong, but the theme developers of Dawn are not the ones maintaining the other workflow tools? 🤔 (so the wrong channel if I am not mistaken)

**Comment by timdonaldson** [comment]
Yeah you're right @gregjotau, I guess my hope was that teams that developed Dawn and the Workflow tools weren't completely siloed and that this thread might feed back into the overall development ecosystem. And since I couldn't find any way to raise this issue with the team that built workflow tools I thought this might be a good place. But this doesn't appear to be the case so I'll close this issue.
For anyone having issues git+multi store setup, I've created a thread on the forums: https://community.shopify.com/c/technical-q-a/cli-and-github-deployment-frustrations/m-p/1302035#M64964
