### ISSUE TITLE
Wrong active state on input form fields

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#281]
**Describe the current behavior**

The focus ring appears when inputting on form fields while using mouse / trackpad navigation.

The focus rings should display when using assistive/keyboard navigation. Otherwise we should rely on the input's active state. 

Let's make sure all form fields are correctly using their active state.

- Dawn Version: 1.1.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

Current:
(recording)
https://screenshot.click/21-24-ojm1i-3gcdy.mp4

![image](https://user-images.githubusercontent.com/8127145/127224855-a2bc0d7b-5268-4a4c-bbd2-63542d67dcd1.png)

Figma: 
![image](https://user-images.githubusercontent.com/8127145/127224744-6f3e293a-6e79-48bd-9232-1454db43f69f.png)

**Comment by KaichenWang** [comment]
The inputs are styled as expected. To clarify, when a user clicks an input and enters text (mouse / trackpad navigation), the browser considers the input to be in _focus_

**Comment by melissaperreault** [comment]
## UX Update

[Visual reference](https://screenshot.click/21-08-ekb9w-vij8j.png)

- [ ] Remove the focus offset style and rely on the border size increase to differentiate from other states
- [ ] The focus opacity has changed is now very close to the opacity of the border input, to distinguish all states we would need to bump the focus opacity for inputs I believe. ([Reference](https://screenshot.click/21-08-tae6p-wt5vn.png)). Can we cheat by making increasing the opacity by 20%?

**Comment by nicklepine** [comment]
Note that this should apply to all input fields that currently use the "box within box" focus state. I just noticed that variant picker dropdown on product pages uses that style 

![image](https://user-images.githubusercontent.com/8127145/128782638-4baf0ec1-183d-4ec3-aa63-ce3ee5bdd0c6.png)

**Comment by KaichenWang** [comment]
### Additional tweaks for focus rings (collection page filtering)
Originally posted https://github.com/Shopify/dawn/issues/100
- [ ] Can you add additional padding to the left and right side of the sort by active state. It should [match this](https://screenshot.click/21-44-8cfb5-07fll.png) spacing. [Screenshot](https://screenshot.click/21-40-iv9mc-kym2y.png)
- [ ] When playing with filters on mobile view in editor, A shadow lingers on the “clear” button after it’s been selected. We should remove this entirely. [Screenshot](https://user-images.githubusercontent.com/8127145/126512848-739645d6-0190-4c46-bae4-2a70bea878f0.png)
- [ ] The mobile show filters button has uneven padding on the focus
