### ISSUE TITLE
What is your JavaScript bundling strategy?

### ISSUE THREAD

**Issue by baldurh** [Shopify/dawn#283]
A change was introduced in #190 to 
> bundle the JS a bit tighter [...] to remove some network requests

by merging two features into the `global.js` rather than keeping them in their own files which can be downloaded and/or executed only when needed. This change adds more code into a single chunk which is downloaded and executed on every page.

Isn’t this approach of "saving network requests" a bit outdated since HTTP/2?

**Comment by baldurh** [comment]
I notice you’re still moving stuff into `global.js` rather than to separate js files. Most recently the product recommendation element in https://github.com/Shopify/dawn/pull/1938. May I ask why you prefer making this a single bundle of close to 1000 lines instead of breaking it up into smaller files?

cc @tyleralsbury @ludoboludo

**Comment by ludoboludo** [comment]
In the case on the product recommendation custom element, it was a 38 lines I moved yeah as it was needed in a couple scenarios/different files. 
But I think there is definitely some room for improvements and exploration. To find best way to potentially spilt our files and better performance.
