### ISSUE TITLE
Collage Section UI bugs

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#285]
A few bugs with the collage section: 

- [ ] The sold out / sale tags are cropped (we can't see the edges of the pill) 
- [ ] When 2+ collage sections are stacked, with their headings removed they overlap
![image](https://user-images.githubusercontent.com/8127145/127331269-b1e339a5-009b-479c-b86c-a08711442f53.png)

Martina suggests: I` think we need to remove the -6rem and use -4rem instead`

**Comment by tyleralsbury** [comment]
This should be a quick one so anyone could take it but I assigned @ludoboludo since he implemented the collage.

**Comment by ludoboludo** [comment]
I wasn't able to replicate the sold out/sales badge being cut out 🤔  If you have more context @nicklepine let me know. Maybe it happens on a specific breakpoint (mobile, tablet, desktop) or in a specific browser. Let me know, I created a PR to fix the spacing in between two collage section though.
