### ISSUE TITLE
Volume Pricing: Variant option combination that doesn't exist 'Unavailable' product still shows 'Volume pricing available', etc

### ISSUE THREAD

**Issue by edmund-teh** [Shopify/dawn#2870]
I believe we originally have this issue to avoid layout shift, but it might not make sense to display the `Volume pricing available` string and the `Volume pricing` table on a variant combination that doesn't exist. 

The information shouldn't display here, as the product is not available and therefore wouldn’t have or shouldn’t have volume pricing available, since the product is unavailable. 

See video recording for more info: https://screenshot.click/Volume-pricing-bug-Fast-follow-Jul-18-2023.mp4

https://screenshot.click/Current-PR-Desktop-Unavailable-variant-combo-v2.png
https://screenshot.click/Current-PR-Mobile-Unavailable-variant-combo-v2.png

We are presently doing this in our latest/current version of Dawn, by hiding the `Price` block on unavailable products/ variant combinations that don't exist: https://screenshot.click/Current-Dawn-Price-block-hidden.png

![Image](https://github.com/Shopify/dawn/assets/100385474/65392e68-befa-461a-8f1c-53637c0fb890)
![Image](https://github.com/Shopify/dawn/assets/100385474/e98846e1-594e-44b2-9639-e2706f604dd1)

**Comment by sofiamatulis** [comment]
We should also do this here: https://screenshot.click/21-01-iv2cu-f8a7r.png
