### ISSUE TITLE
Volume pricing PDP: Strange error positioning when volume pricing table is displayed on PDP

### ISSUE THREAD

**Issue by scottgmeadows** [Shopify/dawn#2894]
When a variant has volume pricing, errors appear below the volume pricing table. Not necessarily incorrect, but I think we should explore alternative placements that seem less "far removed" from where the buyer's focus is likely to be.

Example with volume pricing (and quantity rules):
![image](https://github.com/Shopify/dawn/assets/2594304/80ee8c51-d1fd-48cc-8751-5687a1657fa7)

Example without quantity rules or volume pricing for reference:
![image](https://github.com/Shopify/dawn/assets/2594304/39c6578c-c1ef-4523-b230-e6e8743a97fe)

**Comment by sofiamatulis** [comment]
@scottgmeadows @nicklepine The errors are part of the buy buttons component. If we were to move it, it would live with the vol pricing table (vol pricing table lives in the qty input block).

I think the reasoning behind keeping the errors close to the buttons are that if blocks are moved around we may not see them when the buyer clicks on add to cart. And it's important to get the error feedback when clicking on `add to cart` cc @melissaperreault
