### ISSUE TITLE
UI Polish: Theme Settings > Styles

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#29]
Ensure the proper theme settings - styles have been implemented: 

![image](https://user-images.githubusercontent.com/8127145/120705809-45c2fb00-c486-11eb-91fb-873fcce103e0.png)

[(Figma Link) ](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=5035%3A1217)

- [x] Accent badge color scheme includes Background 2, Accent 1 and Accent 2
- [x] Sold out badge color scheme includes Background 1, Inverse
- [x] 🆕 Accent icons setting includes options: text, outline button, Accent 1 and Accent 2

Accent icons include: Collapsible tab icons, Checkmark icon in cart notification, Discount icon

**Comment by tauthomas01** [comment]
I verified and it seems to be all done.

> Accent badge color scheme includes Background 2, Accent 1 and Accent 2

![image](https://user-images.githubusercontent.com/658169/124660307-0c5e2080-de74-11eb-9f56-3b7b5404cc73.png)

> Sold out badge color scheme includes Background 1, Inverse

![image](https://user-images.githubusercontent.com/658169/124660262-fb151400-de73-11eb-893d-58fcacca5154.png)

> Accent icons setting includes options: text, outline button, Accent 1 and Accent 2

![image](https://user-images.githubusercontent.com/658169/124660514-4af3db00-de74-11eb-937f-d82025c42a60.png)

> Accent icons include: Collapsible tab icons, Checkmark icon in cart notification, Discount icon

![image](https://user-images.githubusercontent.com/658169/124660202-e5075380-de73-11eb-83bc-dbe125e82abf.png)

Feel free to re-open if there are new styles.
