### ISSUE TITLE
Quick Order List: Keyboard interactions

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#2905]
Glen’s friction log: https://share.descript.com/view/X7sN6L8QXdR (start from 9:20)

**In his words:**

- Ideally there would be one key that I would tap that would take me to the next cell (input)
- Is it Enter?… no.
- Is it Tab?… no, because tab navigates to the next button [+]…
- Is it Down? no. down is very awkwardly editing the quantity value
- Hitting the Up key a bunch of times loses focus and only allocates one keystroke at a time
- If i just want to type quantity values, I can’t

Additionally, in his words: I do think there is a lot of room to improve the keyboard interactions, mainly…

1. The up/down arrow thing to incr/decr quantities doesn’t really work
2. AFAICS we haven’t implemented anything that allows for quick navigation from one qty input to the next

- Really you want to enable a keyboard workflow that is like [type qty] - TAB - [type qty] - TAB etc
- People who know that they want a 1-2-2-2-2-1-1 size run literally want to be able to type it out that fast.
- Please include improvements to the keyboard workflow in the post-Edition iteration of this project.

@nicklepine's suggestion:

- I think pressing the enter key should bring to the next quantity input
- We’d need a way to easily navigate to the previous quantity input but this one im not too sure how given the up and down keys are used to add/remove quantity. Maybe the sideways keys?

**Comment by sofiamatulis** [comment]
Expected behaviour: 

- `Enter` should submit the qty and the focus should go to the next input
-  `Shift enter` should bring you back to the previous input

If there is an error, the focus should not go to the next input
