### ISSUE TITLE
Quick order list: `total` misaligned when font size is larger

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#2921]
https://screenshot.click/27-58-fkzwz-2a11e.png

Quick video:  https://screenshot.click/24-10-fmlvp-by2az.mp4

**Comment by ludoboludo** [comment]
There is a similar issue with images when the font scale is higher than 100%. The image is cut off horizontally: 
![](https://screenshot.click/27-01-xw65e-q7qvu.png)

Should I create a new issue or can we group the issues related to the font size ?
