### ISSUE TITLE
Quick Order list: small screens with large fonts dont fit all content

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#2931]
Video: https://screenshot.click/31-13-nhlcn-llnnz.mp4

**Comment by edmund-teh** [comment]
> Hey team. I was investigating this issue and here are my thoughts.
> 
> First, the issue is happening basically because in certain case we don't have enough room to fit a four-digit number. I noticed that it only happens for variants that have compare_at_price.
> 
> ![Image](https://user-images.githubusercontent.com/105315663/258262137-6e672390-fbc3-4dd7-92c4-1c4cf50082cb.png)
> 
> I'm sure there may be different solutions. I think it's more about UX.
> 
> What if we place the old price and the current one on different lines? That should fix the issue.
> 
> ![Image](https://user-images.githubusercontent.com/105315663/258263003-c27329aa-4dc3-42ef-8ce9-4ffc657dc605.png)
> 
> Thoughts? @edmund-teh @sofiamatulis

I like this approach @eugenekasimov!

**Comment by eugenekasimov** [comment]
Hey @edmund-teh. What do you think, is it better to do this for all mobile cases no matter what mobile screen size is? Or we want to do this only for very small screens?

**Comment by edmund-teh** [comment]
> Hey @edmund-teh. What do you think, is it better to do this for all mobile cases no matter what mobile screen size is? Or we want to do this only for very small screens?

Let's prioritize consistency and do this for all mobile cases. I think that's okay. @eugenekasimov
