### ISSUE TITLE
Faceted navigation - Extra filters added when adding color filter (or any other filter)

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#295]
**Describe the enhancement you'd like**
A clear and concise description of what you want added to Dawn. Add any considered drawbacks.

When filtering on Beige color on famme.no, I would have expected the URL to become:

https://famme.no/collections/tights?filter.v.option.color=beige

Not:

https://famme.no/collections/tights?filter.v.price.gte=&filter.v.price.lte=&filter.v.option.color=beige&sort_by=price-ascending

I am not 100% sure if this has any effect on SEO, I just think it is logical that only the filter that is added changes the URL.

So I think that should be discussed, SEO for faceted navigation is important and I want theme developers to really think about it :) (I am no expert myself, but know it is important)

**Describe alternatives you've considered**

**Additional context/screenshots**
Maybe a screenshot or design?

![Screenshot 2021-07-31 at 13 01 39](https://user-images.githubusercontent.com/13047497/127737908-064c86dd-2289-41f0-8d42-da935dce6fd5.png)

**Comment by gregjotau** [comment]
![image](https://user-images.githubusercontent.com/13047497/127738172-dda3c8b4-bcc9-44cd-8355-368871c7c3ac.png)

As far as I see, this means that Dawn is non-SEO friendly by default since it adds parameters in the url that is blocked by robots.txt. Thus, the faceted navigation SEO support is broken by default

**Comment by akerd** [comment]
Yes, it seems logic also to me that only the non-empty filters are added to URL parameters.

**Comment by PaulNewton** [comment]
> @gregjotau  by default since it adds parameters in the url that is blocked by robots.txt
The ability to edit robots.txt via a theme level robots.txt.liquid was added recently to all shopify plans.
Caution is advised in editing that file and should only be done as a last resort by someone with knowledge of the syntax.

**Comment by gregjotau** [comment]
I close this, as an easy fix for most merchants would be to make a collection for the most important things to index, for example making a collection "black leggings", instead of relying on indexing a page with a query param is a good alternative with more control.

But I still think a saner default is not to add extra parameters.
