### ISSUE TITLE
Add Help text to Custom Liquid Section + Block

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#299]
Relates to: https://github.com/Shopify/dawn/issues/42

**Describe the enhancement you'd like**

We have an opportunity to better inform merchants on the usecases in which they add an custom liquid section:
- Add your own Liquid
- Add an app's liquid snippet

@gretchen-willenberg Could you help come up with copy for this? 

![image](https://user-images.githubusercontent.com/8127145/127916658-7732850f-2ff7-4dcf-873d-b9346e750f31.png)

**Comment by gretchen-willenberg** [comment]
**Support copy drafts**

v1 longer explanation; upgrade path more insider/jargony 
`Add app snippets or other Liquid code to create advanced customizations without taking your theme off the upgrade path. Learn more [offsite icon]`

v2 shorter, upgrade path explained more simply
`Add app snippets or other Liquid code without affecting automatic theme updates. Learn more [offsite icon]`

v3 a combination
`Add app snippets or other Liquid code to create advanced customizations without affecting theme updates. Learn more [offsite icon]`

**Additional copy changes**

- Leave custom field empty to emphasize it’s open to the merchant and flexible
- Remove [Learn about Liquid](url) link above custom field. It can end support text, like we do with metafields. Or, we may decide we don't need it with the addition of the support text.

**Comment by nicklepine** [comment]
Thanks @gretchen-willenberg. I think introducing the concept of the upgrade path might be a bit TMI in this context so I would stick to a spin off version of your V1: 

`Add app snippets or other Liquid code to create advanced customizations. Learn about Liquid [offsite icon]` 

What do you think?

**Comment by gretchen-willenberg** [comment]
True. Cool with the first sentence. 

Can I stubbornly hang onto `Learn more` vs `Learn about Liquid` to be consistent with our other education links in support copy (including metafields)? Since it's generic, it gives us the most freedom to link out. Might be about Liquid, might eventually be a bit more app-centric with Liquid?

`Add app snippets or other Liquid code to create advanced customizations. Learn more [offsite icon]`

**Comment by nicklepine** [comment]
Aligned on 
`Add app snippets or other Liquid code to create advanced customizations. Learn more [offsite icon]`
