### ISSUE TITLE
Harmomize spinner icons

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#31]
- [ ] Change the spinner icon from the "add to cart" CTA on the product page to the spinner used in cart.
 - [ ] replace any instances of spinners that don't match the solid spinner from cart (including filtering flow) 
 
![image](https://user-images.githubusercontent.com/8127145/123464195-8233d380-d5ba-11eb-92ce-08b0928e23fd.png)

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
