### ISSUE TITLE
Cart empty state enhancement

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#314]
## Update to make to the cart empty state

[Screen reference](https://screenshot.click/21-08-6wf0i-81lhv.png)

### A. 
- [x] Change the `Continue shopping` link to the primary button but keep it marked as a link for screen readers.

### B. 
- [x] When Accounts is activated on the shop, display the prompt text to Join or Sign in

### C. 
- [x] Add by default the Featured collection section linked to All products for both empty and cart filled state. The default heading `Shop best-sellers` is a placeholder for now, but if we could make it different than Featured collection it would be interesting.

cc. @gretchen-willenberg we are updating the empty state and would need your help for suggestions for the default heading for the Featured collection section and for the Account text.

**Comment by gretchen-willenberg** [comment]
@melissaperreault [Copy options](https://docs.google.com/document/d/14Aa-twJrAWSo95v7RwTF0M2Pk5xJE3t10GJfmcesWBU/edit#heading=h.74pq6ifgqjc)
