### ISSUE TITLE
Fix "close" icon animation

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#32]
- [ ] reverse animation pattern on close icon in cart notification (should go from faded to 100% opacity)
- [ ] reverse animation pattern on close icon in pickup availability drawer (should go from faded to 100% opacity)

[Screenshot](https://screenshot.click/21-06-mzerr-xymzp.mp4)

**Comment by melissaperreault** [comment]
I believe the animation would have to be reverse, but in scale. Reduction of size instead of scaling it like all other icons.
