### ISSUE TITLE
Bulk Quick Add: QR + VP on Product Card

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#3238]
Polish the Product Cards view to follow spacing, sizing etc of Figma

~~See [Figma Prototype](https://www.figma.com/proto/er95a3yIaQkzjWUnSvQtA7/Bulk-quick-add?page-id=2155%3A18069&type=design&node-id=2155-18913&viewport=892%2C395%2C0.16&t=nVdJmiKTxDUTWcyi-1&scaling=min-zoom&starting-point-node-id=2155%3A18913)~~

- Surfacing quantity rules + VP popover from card ([Figma](https://www.figma.com/proto/er95a3yIaQkzjWUnSvQtA7/Bulk-quick-add?page-id=2155%3A18069&type=design&node-id=2155-18913&viewport=1019%2C492%2C0.32&t=FtjWagooPjwBq5e8-1&scaling=min-zoom&starting-point-node-id=2155%3A18913&mode=design))
- Making sure card looks good with new picker

Updated [Figma]( https://www.figma.com/proto/er95a3yIaQkzjWUnSvQtA7/Bulk-quick-add?page-id=3305%3A54165&type=design&node-id=3307-101735&viewport=383%2C195%2C0.3&t=7QwM08OCd0wrJhwv-1&scaling=min-zoom&starting-point-node-id=3307%3A100047)

Text is underlined. Only shows when vol pricing is available (not when qty rules only)

 We are accessing the grid popover by
- clicking on the volume pricing note 

And dismissing it by
- clicking on the vol pricing again
- clicking on x
- clicking outside of the popover (desktop only)

**Comment by sofiamatulis** [comment]
We are descoping this for v1.

Reasoning:
- Currently the whole card is clickable and takes you to the PDP. We want the experience of clicking outside of the popover closes the popover but doesnt take you to the pdp
- That means changing the popover behavior from popover to modal
- This is tricky given the other qty popovers would look the same and have different behaviors
- Given our deadline, we are scoping this out
- This also means if the buyer clicks on the card it takes you to the PDP but the text `vol pricing available` opens the popover. The buyer can accidentally click on the card and be taken to the PDP which is frustrating

Prototype PR here: https://github.com/Shopify/dawn/pull/3362
