### ISSUE TITLE
How to upload Favicon

### ISSUE THREAD

**Issue by lambdadev007** [Shopify/dawn#324]
I have created a development store yesterday and tried to upload favicon. But there is no way to do so. I can't find the option in the theme settings.

**Comment by stayfocused** [comment]
It's already done recently: https://github.com/Shopify/dawn/pull/86

**Comment by gregjotau** [comment]
@lambdadev007 please close the issue if it is fixed :)

**Comment by dan-menard** [comment]
Closing, as this was fixed :)
