### ISSUE TITLE
New Product Page Block: Product Rating

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#33]
**User Story**
As a merchant, I can display the product rating on my product pages through a theme-provided block that is powered by the standard metafield "Product Rating"

**UI**
In progress

**Editor Settings**
In progress

**Comment by tauthomas01** [comment]
Hi @melissaperreault, I see you are working on product rating in Miro. Do you have any news regarding that?

**Comment by melissaperreault** [comment]
> I see you are working on product rating in Miro. Do you have any news regarding that?

No unfortunately! @valeriegohier and I are waiting for the team to progress on finishing the work to make this available. It's on our radar, thanks for asking!

**Comment by nicklepine** [comment]
@tulinn  Yes, this is also in scope, although handled as a setting. see #34
