### ISSUE TITLE
Feature request: A secure way to add a line item cost

### ISSUE THREAD

**Issue by unlocomqx** [Shopify/dawn#331]
Hi,

I'm developing a product custom fields app with cost impact and I would like to alter the product line price based on the fields values.

I searched but couldn't find a robust way to add a price impact, so here's my feature request in this regard, I hope you find it useful:

- A line item can have a "customization" prop which is an ID

- This ID references a data row containing a price and weight impact

- This customization can be added on the server side, so the app receives the fields then creates a new customization using the admin api and returns the ID

- The new customization ID is added to the line item props and the product is added to cart

- The line item would then show the combined cost/weight of the variant + customization

I think this would allow for a great way to customize products

Please tell me if you need more details
Thank you

**Comment by olafghanizadeh** [comment]
This seems unrelated to the Dawn theme, and should be posted in the correct forum for general Shopify application developmment.

**Comment by unlocomqx** [comment]
Thanks for your reply, I'll close this issue then
