### ISSUE TITLE
[Quick Add bulk] Quick Order List scrolling adjustment for Keyboard interaction

### ISSUE THREAD

**Issue by eugenekasimov** [Shopify/dawn#3312]
The Keyboard interaction scrolling in Quick order List needs to be adjusted for the case where we show the Quick Order List inside the Quick Add Bulk modal. 

Currently the scrolling doesn't happen when you reach a not fully shown row/input.

![29-59-5nk6c-xyyg4](https://github.com/Shopify/dawn/assets/105315663/ab27ed95-09ed-4f2a-9414-276bf12e1998)

**Comment by sofiamatulis** [comment]
cc @nicklepine
