### ISSUE TITLE
The product page does not display the sku function, I think this is a very necessary function for advertising

### ISSUE THREAD

**Issue by liao1204ya** [Shopify/dawn#335]

**Comment by bacounts** [comment]
Putting this issue back on the radar. This is a core function for sales and customer servicing and should be added to the roadmap. The SKU should change with the variable information and should be included as an option or block throughout the theme (ie., on the cart page, cart drawer, product card, product page, and in the search functions.)

CC for triage: @melissaperreault, @nicklepine
