### ISSUE TITLE
[Quick Add Bulk] refinements feedback

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#3416]
## Quick Add Bulk refinements feedback 

1- When I add many products, at one point the total loads and it hijacks the mouse click (the +/- gets blocked when the API call is happening)

2- I was slightly taken aback by the filled number badge on the cart icon. I understand we wouldn't put a number above 3 digits, but the filled icon first made me think it was a bug. Perhaps we could think of a better treatment?

3- The page jiggles on reload (even the store's logo). You can see it happening many times at the end.

**Comment by nicklepine** [comment]
Closing - created individual issues
