### ISSUE TITLE
Facets broken on new update — missing data-id (fix included)

### ISSUE THREAD

**Issue by drewlonious** [Shopify/dawn#3426]
## Describe the current behavior
`facets.js?v=105670031958728952761713395503:97 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'innerHTML')
    at FacetFiltersForm.renderProductGridContainer (facets.js?v=105670031958728952761713395503:97:46)
    at facets.js?v=105670031958728952761713395503:78:26`

## Describe the expected behavior
section `main-collection-product-grid.liquid` is missing `data-id="{{ section.id }}` attribute

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 13.0.1
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Possible solution
section `main-collection-product-grid.liquid` <ul id="product-grid"> is missing `data-id="{{ section.id }}` attribute. Adding data-id fixes the issue

## Additional context/screenshots

![Screenshot 2024-04-17 at 4 21 29 PM](https://github.com/Shopify/dawn/assets/47552877/6bab48a1-1be7-40cd-be93-6492ce7581a7)
You can see in the fetch GET request that section_id=undefined

**Comment by joshistoast** [comment]
Thankfully I caught this issue before I merged the updates into my live store. Very peculiar that nobody caught that `document.getElementById('product-grid').dataset.id` no longer exists, this would've easily and quickly been caught had basic testing been done before merging.
