### ISSUE TITLE
Unknown object "comment" used in sections/main-article.liquid - shopify theme check command multiple warnings shown 

### ISSUE THREAD

**Issue by ajaykayande1994** [Shopify/dawn#3442]
## Describe the current behavior
Please refer below
https://github.com/Shopify/theme-tools/issues/351
When I run commands "shopify theme check" in latest Shopify CLI >= 3.57.1, I am getting warning 
unknown object "comment" is used.
Please fix this as we're targeting zero warnings for shopify theme check command.
<img width="1217" alt="Screenshot 2024-04-25 at 11 06 46 PM" src="https://github.com/Shopify/theme-tools/assets/106052104/9306b4ad-42e4-4c5c-b629-399df3827121">

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 7.0.1
- Chrome Version 108.0.5359.124
- macOS Version 13.1

**Comment by charlespwd** [comment]
Actually not an issue. It's just poorly documented. See the theme-tools issue instead :D
