### ISSUE TITLE
''View store information'' on the PDP stays in focus once selected

### ISSUE THREAD

**Issue by valeriegohier** [Shopify/dawn#347]
**Version information (Dawn, browsers and operating systems)**
- Mobile version 

**Additional context/screenshots**

![Image from iOS](https://user-images.githubusercontent.com/53573494/128748166-f211ca98-245f-4de9-8da0-9455bf269a0d.png)

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
