### ISSUE TITLE
New Product Page Block: Related Products (Cross-sell)

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#35]
**User Story**

As a merchant, I can reference related products on my product page through the use of a theme-provided block that is powered by a product reference array standard metafield. 

**UI**
![image](https://user-images.githubusercontent.com/8127145/123465535-3e41ce00-d5bc-11eb-8cb3-4b86886b2330.png)

**Editor Settings**
![image](https://user-images.githubusercontent.com/8127145/123465469-2b2efe00-d5bc-11eb-9fe0-52be01020930.png)

[Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=1250%3A23873)

**Comment by bacounts** [comment]
@nicklepine and @ludoboludo — This issue should be closed. It was addressed in the commit https://github.com/Shopify/dawn/pull/1938.

**Comment by ludoboludo** [comment]
Thanks for pointing it out @bacounts 👍
