### ISSUE TITLE
category metafields not available through search & discovery

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#3527]
I want to be able to filter on category metafields, 

**Filter in product index
Adds definition to the filter options in the product index**

is enabled in the admin for the metafield.

Is this something Dawn would have to add support for? 

![image](https://github.com/Shopify/dawn/assets/13047497/d4c2c214-eddc-45ac-a478-5873a3e343c7)

![image](https://github.com/Shopify/dawn/assets/13047497/f5cfb086-d200-41c5-9e86-73a1a2807f5e)

![image](https://github.com/Shopify/dawn/assets/13047497/e8a4a7b4-d24b-43fb-8c46-580e5c9aa25d)

**Comment by haroldao** [comment]
@gregjotau Take a look at the related branch : https://github.com/Shopify/dawn/tree/release/15.0.0
