### ISSUE TITLE
Dawn 15 Update rendering incorrect product data in JsonLD schema.

### ISSUE THREAD

**Issue by kittol** [Shopify/dawn#3535]
## Product Schema via JsonLD is being altered in Dawn 15 Update resulting in incorrect values for critical fields such as 'Product ID'.

- Dawn Version: 15
Discovered during testing in Google Search Console

## Additional context/screenshots

![Search Console Screenshot 2024-06-21 130429 b](https://github.com/Shopify/dawn/assets/99061750/812f24f9-3545-492b-b275-a4d236630e00)

The 'Product ID' field in the screenshot now contains a number that seems to be irrelevant to my product data.

This field is the first entry in the Schema for the Product ID. 

The SKU that is used to populate data in Merchant centre is much further down the data and this will cause conflicts for Google Bot crawling product data. 

I am unable to find a field to correct this 'Product ID' on my merchant visible product page.

There is an additional ID field populated with url of the page and then '#product' why? This seems irrelevant and results in there now being two superfluous 'ID' type fields in the code before the crawler will find the actual product id of the SKU?

In Dawn 14 the Product Schema for the product data renders correctly.

Metafields on the product page have been changed so the google category in schema is now giving incorrect values and utilising the 

Schema now renders as follows:

Id: (merchant url)#product
type: Product
*********
product ID: 13 digit number (from unknown source? Has this been populated automatically by AI to resemble my product SKU's?)
name: (Page Title)

********
description: ( correct)

********
category: (this now seems to be pulled from the 'product type' metafield on the store page that is supposed to be where a merchant can populate additional data about their product type rather than this being the main google category/product type)

********
brand: (correct)
offer: (correct)
sku: (correct)
availability: (correct)
price: (correct)
url: (correct

Etc. Obviously this varies depending upon product/merchant data, but the rest of the schema seems to render ok for me. 

Everything else with the update to the new version of Dawn 15 seemed improved for me  but until clarity and correction is gained upon these critical issues with Schema I will not be able to update.

**Comment by mbasden** [comment]
My availability is not rendering correctly. It's showing InStock for OutofStock Variants. Can someone point me to where this code resides? I've commented it out on main-product and featured-product, but the product snippets are still coming through when I test it. Thanks!
