### ISSUE TITLE
New Section: Featured Product

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#36]
**User Story**

As a merchant, I can feature a specific product through a section on any template that supports sections, so to increase visibility /discoverability of a product on my online store. 

**UI**
![image](https://user-images.githubusercontent.com/8127145/123466017-d3dd5d80-d5bc-11eb-9e22-6c312b3b5cb1.png)

[Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=2463%3A0)

**Comment by Oliviammarcello** [comment]
There has been an update to the share button positioning and styling:
- [ ] The share block's default state should be at the bottom of the section and inline with the "view product details" button. [Figma desktop](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=11628%3A106333) | [Figma mobile](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=11628%3A106313)
- [ ] When the share block moves up, the "view product details" button should move back to the left-hand side. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=11628%3A107239)

The new styling for share can be found [in this issue,](https://github.com/Shopify/dawn/issues/204#issuecomment-893596486) but also visible on the mockups shared above.
