### ISSUE TITLE
Collection filtering - Add slider to price range filter

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#363]
**Describe the enhancement you'd like**
Slider UI is missing from collection page price range filtering

**Describe alternatives you've considered**
Slider UI would be complementary to manual price input which exists currently

**Additional context/screenshots**
Example
![Screen Shot 2021-08-10 at 1 50 36 PM](https://user-images.githubusercontent.com/3710548/128909758-9394b018-d53a-4547-9450-b6472f9c8ab5.png)

**Comment by nicklepine** [comment]
Closing. Duplicate from #44
