### ISSUE TITLE
Collection filtering - Adjust stroke-weight of checkboxes

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#365]
**Describe the enhancement you'd like**
Stroke-weight of checkboxes should use the same stroke-weight as other icons on the theme

**Describe alternatives you've considered**
Currently the SVG used for checkboxes has a different stroke-weight. The icon SVG must be adjusted and updated

**Additional context/screenshots**
n/a

**Comment by nicklepine** [comment]
Additionally, on iOS Chrome, I am seeing a bracket before the checkboxes:
