### ISSUE TITLE
Collection filterting - disable "reset" link/button

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#367]
**Describe the enhancement you'd like**
Reset (clear?) button stays active when there are no current active filters in a group. Would be nice to disable it so that the items don't refresh when it's clicked and nothing has changed.

**Describe alternatives you've considered**
n/a

**Additional context/screenshots**
[Screenshot](https://user-images.githubusercontent.com/3710548/129047298-31d73956-36e8-4edf-9cba-164f6a55e5a7.jpg)

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
