### ISSUE TITLE
Filters - Escape should dismiss the dropdowns

### ISSUE THREAD

**Issue by tyleralsbury** [Shopify/dawn#382]
**Describe the current behavior**

When the dropdown menu for the filters are not in the collapsible mode, ESC doesn't dismiss them.

**Describe the expected behavior**

ESC should dismiss the open filter dropdown.  This is an a11y concern that was brought up.  @svinkle do you think this is something that should be done?  Are there any downsides to it or is it purely upside in terms of a11y?

**Possible solution**

A small JS script that checks for `esc` and queries for `.js-filter[open]` and closes it.  Alternatively, if it's part of the existing filtering JS, we could keep track of the open filter on the custom element and not need to query at the moment that  the user hits esc since we already have it cached.

**Comment by svinkle** [comment]
> @svinkle do you think this is something that should be done

Yes, I reported this issue as well: https://github.com/Shopify/dawn/issues/108.
