### ISSUE TITLE
Disclosure - Double clicking the summary element selects it

### ISSUE THREAD

**Issue by tyleralsbury** [Shopify/dawn#383]
**Describe the current behavior**

When you double click on the summary element (in filtering, for example, the name of the filter) it highlights it and looks aesthetically not great.

**Describe the expected behavior**

The open/close behaviour that happens is okay, it's what would be expected and is the web native behaviour.  The highlight, though, looks unpleasant and is confusing - we should remove it.

**Possible solution**

We could use `user-select: none` to stop it from highlighting.  We should see if all summary elements should receive this treatment by adding a global style on the `summary` selector itself.

**Comment by ludoboludo** [comment]
I believe I had brought this up in a previous PR/issue about a feature using summaries.There were some concerns about the fact that if needed, you weren't able to copy the text. 

Nor sure if it should be something we worry about for the filters or menu items. We could decide to apply the fix on only some features. Here is where we are using the `summary` element: 
- Filters on collection pages
- Menu items in the header
- Search in the header
- Share button
- Password page modal (`Enter using password`)
- Collapsible tabs on the product page

@svinkle I have a feeling we had this conversation before but maybe I'm misremembering.

**Comment by svinkle** [comment]
@ludoboludo You might be thinking about https://github.com/Shopify/dawn/issues/78.

**Comment by ludoboludo** [comment]
@svinkle Hmm no I think it might be from another issue as this one doesn't seem to mention the `user-select` part. Here is a video to explain how it would work: [video](https://screenshot.click/21-09-p4yv1-o6geo.mp4). 

I wonder if it has any effect on tools used to navigate the page (VO, etc). When I test in Safari, I don't seem to get any issue in the way it's announced. 

Here is a theme which has the CSS property on summaries, if you want to give it a shot: [store preview](https://os2-demo.myshopify.com/?preview_theme_id=126316904470)

**Comment by svinkle** [comment]
@ludoboludo Thanks for this. This wouldn't affect accessibility in terms of assistive tech as the controls are still functional. However, I don't necessarily agree with the motivation to remove the ability to highlight. Yes, chances are people might not be inclined to copy and paste the text from these controls, but that's an assumption. If anyone _were_ to attempt this, I imagine they'd feel something was broken or they weren't doing something correctly.

@tyleralsbury Curious how this came up. When would someone double click these controls? What's the rationale behind this user action?

**Comment by ludoboludo** [comment]
I think it can happen when you open/close a menu/filter/collapsible tab. You don't need to do it super fast for it to happen. 

Another alternative would be to style the `::selection` using the color's schemes. But something we would need to run through the design team. 

This way instead of being the blue default background color it can be something matching the branding of the site and looking a little more sharp. 

More info about it [in the MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)

**Comment by svinkle** [comment]
> Another alternative would be to style the `::selection` using the color's schemes. But something we would need to run through the design team.

I'd like to see this explored before removing completely. Selection color still needs to conform to color contrast requirements. If the theme colors are used it shouldn't be an issue.

**Comment by ludoboludo** [comment]
Here is a [video](https://screenshot.click/21-09-7d3c7-d4o1r.mp4) of it would look like.

cc: @Guillaumegranger1

**Comment by tyleralsbury** [comment]
> The ask was to prevent involuntary highlighting the summary labels when double clicking, or opening and closing fast.
> 
> The ask was not to prevent highlighting summary labels at all times - users should still be able to select text and copy if they want to.
> 
> If it is impossible to accomplish the ask, without preventing highlighting at all times, then I think Ludo's suggestion of harmonizing the highlight color with the theme's color settings is a good compromise.

It would be pretty awkward and JS-oriented with some sort of debouncing to make it work, so I'd argue that harmonizing the colour is the most principled alternative for sure.

**Comment by kmeleta** [comment]
@tyleralsbury @ludoboludo Just thought I'd mention I came across and [briefly] tested a trick that could possibly still accomplish the original ask. Which is to basically check the `event.detail` count in summary mouseevents to see whether it's a double click or not, and just preventDefault if it is. I didn't implement everywhere to test but it seems to work https://screenshot.click/10-19-7j0qb-7elev.mp4

That said, I think selection color update is worthwhile regardless of course.

**Comment by tyleralsbury** [comment]
> @tyleralsbury @ludoboludo Just thought I'd mention I came across and [briefly] tested a trick that could possibly still accomplish the original ask. Which is to basically check the `event.detail` count in summary mouseevents to see whether it's a double click or not, and just preventDefault if it is. I didn't implement everywhere to test but it seems to work https://screenshot.click/10-19-7j0qb-7elev.mp4
> 
> That said, I think selection color update is worthwhile regardless of course.

Thanks for looking into that, Ken.

A CSS only solution like making the branding tighter is more principled than a JS solution, though it is nice that it's a tiny bit of JS.  If we feel strongly that the double click prevention is the better option, then we could use the JS approach but it does fall short of our theme development guidelines in a sense.

**Comment by kmeleta** [comment]
> A CSS only solution like making the branding tighter is more principled than a JS solution

Totally agree. I don't personally think the issue is worth adding any new complexity to fix, but if we were pushed on it, the js solution I mention _should_ be pretty minimal.
