### ISSUE TITLE
Predictive Search

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#39]
**User Story**
As a buyer, I want to be proposed search results as I type my search query, so that I can more easily and quickly find what I am looking for. 

**UI**
![image](https://user-images.githubusercontent.com/8127145/123472147-c926c680-d5c4-11eb-887d-bd84b84e2c21.png)

[Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=3393%3A48838)

**Comment by gregjotau** [comment]
👍 we need predictive search ASAP.

**Comment by gregjotau** [comment]
We added it to famme.no / fammestore.dk / fammesportswear.com

Works great!

Would be interesting if it could also use description mabye? 🤔 Since some of our items have english names, but people search in Norwegian.
