### ISSUE TITLE
Unit pricing bugs

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#4]
Unit pricing problems: 

- [ ] Font size on customer order details page is inconsistent with the font size used for unit pricing throughout the rest of the theme. [Screenshot](https://screenshot.click/21-06-wma1t-itru4.png) 

- [x] Unit price disappears for sold out variants. [Screen recording](https://screenshot.click/21-06-t5c25-pzcxa.mp4)

**Comment by tauthomas01** [comment]
Another issue I found is that `line_item.unit_price` or `line_item.unit_price_measurement` returns `Liquid server: internal` so I'm unable to see unit prices in the order detail page. I am not sure if there was a change in the backend.

![image](https://user-images.githubusercontent.com/658169/123983041-8d5b7a80-d991-11eb-8711-b29522219c54.png)
