### ISSUE TITLE
Quantity UI component change

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#400]
[Visual reference](https://screenshot.click/21-08-31tf8-enoux.png) for the outcome for all screens.

- [ ] We'll use a select component with a border opacity decreased in the cart template and Product page and section (8% of text). 
- [ ] On the cart template, the remove can icon will be displayed beside the dropdown, on the right.
- [ ] The dropdown will use the native list for all devices and the values will increment by 1 ~until the maximum value that has been set by merchants through a setting. (See below)~
- [ ] Add a new number setting type to let merchants adjust the value themselves to match their business needs. (Learn how merchants are using it.) (Depending on the limitation we may need to go back to a range setting, still investigating. But regardless we are aiming to put a max.)
- [ ] Default value is `20`
- [ ] ~Have this number setting maxed at `500` to accommodate larger merchants needs. (_Basically prevent merchants to put value above 500, is this possible attribute for that basic setting?_)~

**Comment by tauthomas01** [comment]
> Have this number setting maxed at 500 to accommodate larger merchants needs. (Basically prevent merchants to put value above 500, is this possible attribute for that basic setting?)

This is not possible. Only `range` type setting can allow a maximum number.

**Comment by melissaperreault** [comment]
## UX Update

After considering the pros and cons of both dropdown and input UI, we'll revert to the [input UI](https://screenshot.click/21-08-00g76-7w715.png) to enable all merchants need.
