### ISSUE TITLE
Video not working on mobile

### ISSUE THREAD

**Issue by gregjotau** [Shopify/dawn#402]
**Describe the current behavior**

https://famme.no/products/velvet-pants

We have a video of this product. It is not playing on mobile. It works on desktop.

Tested on iphone 12, latest Chrome and latest Safari.

**Describe the expected behavior**

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by PaulNewton** [comment]
@gregjotau Does this issue persist if you download and use the latest version of Dawn?
either a release, or the current main branch?

**Comment by gregjotau** [comment]
@PaulNewton we are basically in sync with the main branch: https://github.com/gregjotau/dawn-famme

We have some customization, but cannot see how those will affect the video display. I can try to do a reset --hard on the upstream/main and test again if you cannot replicate.
