### ISSUE TITLE
Footer: Image Block

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#41]
**User Story**
As a merchant, I can add an image file to my footer, so I can display badges (like FDA approved, Certified organic, etc) 

**UI**

![image](https://user-images.githubusercontent.com/8127145/123472724-8a454080-d5c5-11eb-8979-da35e39548e3.png)

**Editor Settings**
![image](https://user-images.githubusercontent.com/8127145/123472822-ab0d9600-d5c5-11eb-8202-ac91cf8f362e.png)

[Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=8722%3A81182)

**Comment by ludoboludo** [comment]
Here I'm wondering something about the alignment of the image. Should have two dropdown ? One for vertical alignment and one for horizontal ? 
[Video](https://screenshot.click/21-07-fct8q-6utyd.mp4)

**Comment by nicklepine** [comment]
I get the problem you're trying to solve @ludoboludo. I personally think we may want to keep it light on the settings side and keep the alignment setting to be horizontal only (left, center, right... or whatever the proposed values were). It could be confusing set up UX to have 2 alignment settings to account for both axis.

It can be up to the merchant to ensure they add similar ratio'd settings + leverage the width adjuster setting to ensure they remain of similar size. 

We can ship with this and monitor how merchant use the image block / and the support tickets around it to inform future iterations if need be!

**Comment by melissaperreault** [comment]
Aligned with monitoring, added it to our list of things to track. 👍
