### ISSUE TITLE
[Global] Search modal launcher control includes extra stateful attribute

### ISSUE THREAD

**Issue by svinkle** [Shopify/dawn#417]
## Issue summary

The search modal launcher control, which appears in the header, includes the `aria-expanded` attribute. This attribute adds extra stateful information (collapsed state.) Since the purpose of this control launches a new context (modal window), an "expanded" state is not required and may lead to a confusing user experience.

<details>
  <summary>Screenshots</summary>

<img width="200" alt="Dawn theme, header section. Search control is highlighted." src="https://user-images.githubusercontent.com/1392632/129746244-91fbad61-4c4c-4dee-a63d-c52bc5973822.png">

</details>

#### HTML

```html
<summary
  class="…"
  aria-haspopup="dialog"
  aria-label="Search"
  role="button"
  aria-expanded="false"
>
  <!-- Icons…-->
</summary>
```

## Steps to reproduce

1. Go to a Dawn theme store with any supported browser
2. With an active screen reader, <kbd>Tab</kbd> to the search control in the header

### Expected

- Search modal launcher to not convey an "expanded" state.

### Actual

- Search modal control announcement includes _"collapsed"_ context.

## Recommendation

Remove the `aria-expanded` attribute.

#### HTML

```html
<summary
  class="…"
  aria-haspopup="dialog"
  aria-label="Search"
  role="button"
>
  <!-- Icons…-->
</summary>
```

<!-- #### Diff

```diff
- line removed
+ line added
``` -->

## Specifications

- **WCAG Principal:** Perceivable, Robust
- **WCAG SC:** [1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html), [4.1.2 Name, Role, Value](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html)
- **Severity:** Low
- **Effort:** Low
- **Related:** https://github.com/Shopify/dawn/issues/701

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by svinkle** [comment]
Fixed at some point.
