### ISSUE TITLE
Product Page: Custom Liquid Block

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#42]
This ticket proposes the addition of a custom liquid block to :

- [ ] 1. the main section of the product page. 
- [ ] 2. featured product section 

**What this solves**
Similarly to the Custom Liquid Section, this can let merchants (and theme specialists) make slightly more advanced theme customizations without going off the upgrade path.

-----

From @andrewetchen 

> Add a Custom Liquid page block to [main-product.liquid](https://github.com/Shopify/dawn/blob/main/sections/main-product.liquid)
> 
> <details>
>   <summary>Custom Liquid - Page Block </summary>
> 
> ![image](https://user-images.githubusercontent.com/28404165/121723129-20e90c00-cab4-11eb-91db-5f0b23a5cc6d.png)
> 
> </details>
> 
> - Add the following: I added it before `{%- when 'description' -%}`
> 
> ```liquid
> {%- when 'liquid' -%}
>   {{ block.settings.custom_liquid }}
> ```
> 
> - Add the following schema block setting:
> 
> ```json
> {
>   "type":"liquid",
>   "name":"Custom Liquid",
>   "settings": [
>     {
>       "type": "liquid",
>       "id": "custom_liquid",
>       "label": "Custom Liquid"
>     }
>   ]
> },
> ```

**Comment by nicklepine** [comment]
I polled our slack channel to brainstorm other ideas for what this custom liquid block could be useful for. The consensus is this would definitely be helpful for merchants and support to perform more advanced customizations that require Liquid. The true beauty of this custom liquid block is that any customizations are contained within the block and so the theme remains on the upgrade path. Plus, it reduces the need to adventure in the code editor.

Here's what we got as ideas, in more detail: 

1. You could install apps that haven't yet been ported to using app blocks, which initially will be most of them. This would keep the theme on the upgrade path.

2. Could be used for adding information/custom button for products that aren't available or for merchants who take only custom orders. So the button has a different behaviour than the add to cart.

3. To simplify copy and pasting a block of code you might have found in a forum into a liquid block (rather than adventuring in the code editor) 

4. Custom formatting of different info like price, title, etc. Showing product tags that link to related products
Loading a menu of links.

From @drewrothrock : 

> I think when we talk about what can be done with using custom liquid on the product the possibilities are endless, but for a lot of them it’ll be important that it ‘fits’ within the rest of the product page blocks such as under the title, above the description, etc.
> Agreed this could excite merchants, and could potentially bring other areas of the platform like forums or help docs.  We’ve seen how difficult it is for merchants to locate files like product-template so having a block on the theme for simple customizations might be a big win - even for straightforward liquid drops like an array of product.tags  or product.collections

**Comment by bredowmax** [comment]
I'd love a Custom Liquid Block for Products. In my situation, I want to install the review stars of TrustPilot - an app that hasn't been properly ported to Shopify 2.0 yet. By using a Custom Liquid Block, the theme could remain intact, without any code changes
