### ISSUE TITLE
Inconsistent "Zoom In" Animation on Blog Post hover

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#421]
The zoom in animation upon hover of a blog post is too speedy. 

Let us make sure it uses the same subtle speed than what it used on Collage and Collection Cards. 

[Recording](https://screenshot.click/21-13-h1dh1-wtfaq.mp4)

**Comment by Oliviammarcello** [comment]
- [ ] Change the animation on blog posts to `--duration-long: 500ms;` instead of `--duration-default: 200ms;` to match collage and collection cards
