### ISSUE TITLE
Recaptcha Challenge Page Loads Anchored at the bottom of the page

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#423]
When submitting an email in footer, the recaptcha challenge page loads while the user is still anchored at the bottom of the page. When a page loads, I expect to be at the top of the page, rather than at the bottom. 

Recording: https://screenshot.click/21-40-fwyyh-2r9jj.mp4

**Comment by ludoboludo** [comment]
Trying to look into this but so far I'm jut getting a `Too many requests, please try again late` 😬 😓

**Comment by nicklepine** [comment]
Thank you for digging into this. I'll close for now.
