### ISSUE TITLE
Search and 404 page: Awkward spacing between sections

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#428]
The Search and 404 page adds awkward spaces in between sections

404: 
![image](https://user-images.githubusercontent.com/8127145/129903408-de0824ac-7e09-4a18-a26f-c78d01e07c6f.png)

Search:
![image](https://user-images.githubusercontent.com/8127145/129903472-4cf6deac-978b-4322-b80b-e097b7d9d0ba.png)

- [ ] Test to make sure all json templates use proper spacing between sections

**Comment by sofiamatulis** [comment]
@nicklepine I just re-tested and havent been able to reproduce the spacing with these sections in these templates:

https://screenshot.click/15-05-0zp2f-w8gtt.png

https://screenshot.click/15-04-6iw2q-fjmzw.png

**Comment by nicklepine** [comment]
Ok! Same.Thats good news. We can close. If this comes up again, we'll re-open.
