### ISSUE TITLE
Collage Section: Lift block limit

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#43]
Iterate on the implementation of the collage section to lift the limit of 3 blocks max. The layout is flexible by design and should let merchants add any number of blocks (until the editor limit). 

![image](https://user-images.githubusercontent.com/8127145/123473471-9bdb1800-d5c6-11eb-880f-85769cac8468.png)

**Comment by melissaperreault** [comment]
This would require more UX exploration for the settings as to how the additional blocks display under the first elements. To investigate if this is needed. This is interesting to optimize the number of sections which its current limit is at 25 and 50 for blocks.
