### ISSUE TITLE
Filter checkbox focus mis-aligned

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#432]
**Describe the current behavior**

On safari, the focus ring on filter checkboxes are misaligned

_Originally posted by @tauthomas01  in https://github.com/Shopify/dawn/pull/389#pullrequestreview-732911308_

**Describe the expected behavior**

Checkbox focus is aligned

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0
- Safari  14.1.1
- macOS Version 11.4

**Possible solution**

Somehow Safari calculates the `left` property differently on `.facet-checkbox input[type=checkbox]` vs. Chrome

**Additional context/screenshots**
[Screenshot](https://user-images.githubusercontent.com/658169/129911484-9bd0df35-295f-44dc-bf59-8a3b45e92052.png)

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
