### ISSUE TITLE
Miscellaneous design refinements

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#442]
While none of these are critical, they are listed in order of most to least critical: 

- [x] With the new “Layout” setting (Maximum width : 1600px), the section stacking feels too condensed and the theme lacks some whitespace. I propose to bump up all the section spacings by a small percentage when the max width is set to 1600px.

- [x] Collage, collection list, and multicolumn sections have inconsistent grid alignments
[Screenshot](https://screenshot.click/17-22-9jord-wn4vn.png), [screenshot](https://screenshot.click/17-20-ktr5e-o3qdy.png)

- [x] The loader animation (spinner) upon adding a product to cart is inconsistent. The animation should be the same as the one that is used when filters are applied on a collection page. We must ensure it is also the case elsewhere (cart updates, etc.)

- [x] Headings in columns on multi-column need more line height. [Screenshot](https://screenshot.click/17-24-k6tt0-l0h8u.png)

- [x] The dates in the article cards (blog index, featured blog section… need more spacing above
[screenshot](https://screenshot.click/17-26-3ycnv-mfddd.png)

- [x] The only place where one can see bold text throughout the entire theme is on pagination. I suggest we see the text without bold. The underline suffices.
[screenshot](https://screenshot.click/17-29-ks0xo-74knr.png)

- [x] The arrow next to the “Back to blog” link at the bottom of the articles is not vertically aligned
[Screenshot](https://screenshot.click/18-16-100ti-nj7yi.png)

- [x] There shouldn’t be an opacity change on the header icons on hover. They should be 100% all the time.

**Comment by wiktoriaswiecicka** [comment]
- [ ]  With the new “Layout” setting (Maximum width : 1600px), the section stacking feels too condensed and the theme lacks some whitespace. I propose to bump up all the section spacings by a small percentage when the max width is set to 1600px.

Aligned, let's bump it up to 7rem (was 5rem)

- [ ] Headings in columns on multi-column need more line height 

line-height: is 1.3 now, increase to 1.5

- [ ]  Collage, collection list, and multicolumn sections have inconsistent grid alignments

Decrease margins on desktop college to match other components

- [ ]  Wasn't mentioned by Nick but the border around a collection list card in the collage is using text color, instead, it should match other cards: .1rem solid rgba(var(--color-foreground),.08);

<img width="195" alt="Screen Shot 2021-09-07 at 3 00 12 PM" src="https://user-images.githubusercontent.com/61301164/132397125-91f4ba16-630c-4ba2-8aa7-823d87d22722.png">


- [ ] There shouldn’t be an opacity change on the header icons on hover. They should be 100% all the time.
We should remove opacity from all the icons that are CTAs (share icon etc.)

**Comment by wiktoriaswiecicka** [comment]
What we meant is the dark border around the collection list card - should be the same as the two images on the righ, but right now it’s using the color of the titles background below (text). Would it be possible that the part of the border around the image is the same as around the pictures on the right? Otherwise maybe we want to remove it completely? @Oliviammarcello 

<img width="1031" alt="Screen Shot 2021-09-08 at 10 33 42 AM" src="https://user-images.githubusercontent.com/61301164/132530104-5bf08faf-0a85-4970-9593-8ff3a7d2f241.png">

**Comment by melissaperreault** [comment]
> For context, we have decided to remove the border for collection in the collage since it was being affected by the color scheme.

I thought that all blocks borders were affected by the color scheme? Did we consider exploring how this will impact lighter assets surrounded by blocks with a border?

**Comment by sofiamatulis** [comment]
> > For context, we have decided to remove the border for collection in the collage since it was being affected by the color scheme.
> 
> I thought that all blocks borders were affected by the color scheme? Did we consider exploring how this will impact lighter assets surrounded by blocks with a border?

They are but it's just an issue when there is an image (screenshot above). We have just removed it for the collection block in the collage, the other blocks still have it

**Comment by sofiamatulis** [comment]
@melissaperreault the PR has been merged (includes many other refinements), but feel free to open a new issue for the border if needed 🙏
