### ISSUE TITLE
Search Results Template: Facet Filtering

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#46]
**User story**
As a buyer, I can filter down my list of search results using facet filtering, so that I can find what I am looking for. 
As a merchant, I can choose to enable filtering on my search results template, same way I can on my collection template. 

**Considerations/Open UX Questions**
- When applying filters that are all specific to products (price, variant options, availability, etc) do we surface other types of search results (pages, blog posts) ?

**Comment by cupelapps** [comment]
Hi Team,
My Hats off to the team. I have tested with the **storefront filtering**. [](https://shopify.dev/themes/navigation-search/filtering )It seems that the filtering stops with 1000 products within the collection(on a development store) And I have tested with adding pagination, but it is not working. Is there any limits for the storefront filters or it is still under development?

Regards
Muthu

**Comment by gregjotau** [comment]
For famme.no we *do not want* to display blog posts at all in search, maybe not pages either. So hopefully you can add an option with regards to what can be included in the search

**Comment by gregjotau** [comment]
Another thing here, we **need products to be displayed first**, right now we have a lot of blog articles mentioning "sko" (shoes), that shows up before the actual shoe product. It makes NO sense 😓

**Comment by gregjotau** [comment]
Example searching for shoes, a lot of less relevant articles are shown:
![Screenshot 2021-07-27 at 20 31 59](https://user-images.githubusercontent.com/13047497/127208790-86fa67f0-f927-4390-a9e3-d2019bf12e61.png)

**Comment by muthusomasundaram** [comment]
Hi there,
Kindly consider the sorting and pagination issue which is present for decades. For example, search results cannot be sorted by title or date on whole and also cannot be searched by collectionwise.

**Comment by tyleralsbury** [comment]
Added Low - Medium Effort.  Once filtering for Collections is complete, adding it to Search should be mostly a copy/paste job.  The only differences are...

1. The global variable `collection` is `search` instead
2. The way the product count works is different. There will be no X of Y, but just "Showing X products"
3. Need to add a hidden input with the name `q` for the search query to ensure it's in the form that's submitted to the filter/sort.

**Comment by muthusomasundaram** [comment]
Hi @tyleralsbury,
Thanks for the info. Can you confirm about the sorting feature in the search or search filter?
