### ISSUE TITLE
Harmonize overlay across drawer and modals

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#462]
Harmonize the drawer/modal overlays:

- Filter drawer, uses a darkened backdrop that you can click on to close the drawer.
- Popup link, uses a darkened backdrop that you can click on to close the popup.
- Pickup availability, doesn't have a darkened backdrop but you can click outside of the drawer to close it.
- Menu nav, doesn't have a darkened backdrop and you can't click outside of it to close the drawer.
- Cart notification, doesn't have a darkened backdrop and you can't click outside of it to close the drawer.
- Predictive search, uses a darkened backdrop that you can click on to close the drawer.

**Comment by bredowmax** [comment]
Noticed as well in user testing how I tried to 'escape' that modal by clicking outside - thereby breaking something in the page. Would be glad if this gets fixed!

**Comment by nicklepine** [comment]
This will be tackled when we get to #961
