### ISSUE TITLE
[Zoom] Product modal opening position

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#465]
Let's try to have the position center/center when opening the modal on the product template. This is to give the chance for customers to see details of the media. 

It is more likely that media details will appear in the middle of the media as oppose to relying at center/top where this only benefit vertical tall products.

**Comment by bredowmax** [comment]
The modal is the biggest single weakness of Dawn so far, rendering it unusable for most merchant if no custom code is added. I added screenshots in #355

Pease find another way for shoppers to view these product images. These modals just don't work.
