### ISSUE TITLE
[Featured Product] Pickup Availability - Discussion

### ISSUE THREAD

**Issue by LucasLacerdaUX** [Shopify/dawn#468]
**Describe the enhancement you'd like**
Should `Product Availability` be available on the Featured Product section?

- In both Debut and Express, this feature was only available on the product page.
- Figma mockups for Dawn also didn't include this feature.

Is this a standard we want to set, moving forward?

**Notes**
The current code for `pickup-availability` in Dawn is not compatible with multiple product sections. If we decide to make this feature available on Featured Product, some changes are required to be made to support more than one product at a time.

cc @melissaperreault

**Comment by melissaperreault** [comment]
Product page only feature! Thanks Lucas!
