### ISSUE TITLE
Search template: Single search bar

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#48]
The search bar [shouldn’t be repeated](https://screenshot.click/24-11-m5mrs-v8s6i.mp4) on the page after a search has been submitted.

- [ ] The search bar shouldn’t be repeated on the page after a search has been submitted. We want to open the result page with the header search expanded with the query typed in. Idea below this list how to accomplish this [from this thread](https://docs.google.com/document/d/1E6xtFJhdc3t4W0aVNuPyNIrRguwZ8oj-eTOZyyGUgjA/edit?disco=AAAAMapCR4c).
   - [ ] Link to latest [Figma reference](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=8405%3A77258)

**Implementation note before Unite**
Keeping the search input open in the header to remove the duplication of the search UI requires further time and investigation of how to provide a good accessible experience for keyboard navigation, so we will move this request after Unite to allow for time for prototyping to avoid shipping a weak experience.

Context: Original video feedback from Jen: https://screenshot.click/24-11-m5mrs-v8s6i.mp4

**Comment by melissaperreault** [comment]
cc. @al-mcquiston For context from the past on the intention to simplify the number of search input when in the Search results page.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
