### ISSUE TITLE
Update ratings block  and settings learn more link with the correct url

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#484]
**Describe the current behavior**

The current `learn more` link for the ratings block is not the correct one.

**Describe the expected behavior**

We should update the doc link once the doc is ready: https://github.com/Shopify/dawn/pull/341/files#diff-8634bdb8283e62e6df834e80736461b1c05b2d6d669fde29e2fe1b9b7e86ed87R519

https://screenshot.click/25-43-du8x5-ggiv1.png

cc @nicklepine @melissaperreault 

this applies to: 

The product rating block is available on :
- [ ] product page
- [ ] featured product section.

The product rating setting is available on:
- [ ] product recommentation, 
- [ ] featured collection, 
- [ ] collection template (product grid) 
- [ ] search templates (in the product cards)

**Comment by shainaraskas** [comment]
for the product info section, use this instead (it's closer): https://help.shopify.com/manual/online-store/themes/os20/themes-by-shopify/dawn/page-types#product-rating-block

for featured product, use this:  https://help.shopify.com/manual/online-store/themes/os20/themes-by-shopify/dawn/sections#featured-product-rating
