### ISSUE TITLE
New section: Video

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#49]
**User story**
As a merchant, I can add a video section, so I can convey messaging around my business/products in video format

**Context**
Merchants will have the ability to surface a video by adding a collage section, with a sole video block. However, this flow is not the most discoverable. We're contemplating the idea of adding a video section so merchants can more easily find and add this type of section to their online store.

**Comment by tyleralsbury** [comment]
Note for whoever works on this.  We need to use the deferred media pattern from the product gallery and collage sections to ensure that any assets loaded as a result of adding a video are loaded only when requested by the user, preventing a ton of loading up front.

**Comment by PaulNewton** [comment]
A thing to note is the underlying issues here exists upstream that will lead to similar section with pared down feature requirements.
 Mainly the theme designer in shopify does not have conditional settings or conditional presets in the schema that would let developers simply reuse [/sections/collage.liquid](https://github.com/Shopify/dawn/blob/main/sections/collage.liquid) with a **limited** group of settings effectively making it a section for use with a single piece of media through retitling and block restrictions.
If that ever changes sections like this could be consolidated.

For example in the below fakeup image all I've done is change "Collage" title to "Video and Media" and it's default blocks to a single video block. 
![image](https://user-images.githubusercontent.com/47228209/125731372-0f955e7a-f9ca-4cb3-848f-70d87793c0a0.png)
