### ISSUE TITLE
Mobile Media Gallery - Asset Navigation 

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#495]
As a buyer in a product media modal on product pages (looking at larger images), I should be able to navigate to the previous and next assets directly in the modal rather than having to close it, swipe to the next image, and then tap again to view that image larger.

**Comment by melissaperreault** [comment]
## UX Update

We'll be investigating the following through prototyping to learn the performance/code impact and best/ideal experience:

- Losing controls in view when zooming
   - Web native; The user is simply leveraging the regular gestures that browsers support and zooming in the entire page.
- Keeping controls visible and require more JS
   - Not web native; Implement a custom zoom using JavaScript, adding gesture listeners to the image container and scaling according to the distance between the initial and final tap.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps

**Comment by ChristopherCapito** [comment]
I actually have an in-kind suggestion: Swipe to close. It is supremely more convenient to swipe and image off screen to close than having to press a small Button at the upper right Corner of a phone.
