### ISSUE TITLE
Display line item price in Cart

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#497]
We recently cleaned up the cart page from the price column because we felt there was a lot of information gymnastics on this page for buyers to parse - and believe the total column provides the price information in most cases. 

For some usecases however, still seeing the price of an individual unit of a line item may be necessary. 

![image](https://user-images.githubusercontent.com/8127145/130972768-8362c300-c433-4f0b-b4ec-6e022f78dce3.png)

**Comment by sofiamatulis** [comment]
@melissaperreault Do you know where it has been decided to display the unit price on cart?

**Comment by melissaperreault** [comment]
@sofiamatulis Yes! Here is the update with the details:

## UX Update

[Visual guidance](https://screenshot.click/21-10-tamdi-pkgsb.png)
- [ ] We'll display the individual price below the product name, styled like variant options (color and size)
- [ ] The only missing piece that I would like to discuss and validate is if we can maintain the unit price ($3.05/100g) position under the total column, let's chat!
