### ISSUE TITLE
[CSS] Spacing between elements using universal selectors is showing

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#50]
## Problem

When we style the spacing between universal selectors (`* + *`), there are edge cases where extra spacing happens when you have a "left over" element displayed: if you have multiple elements such as this : 

```
// css
* + * {
  margin-top: 3rem;
}

// html
<h2></h2>
<div></div>
<a href="#">View more</a>
```

The `<a>` element would show extra spacing.

### Examples

Rich text
<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/658169/109052879-21e36280-76aa-11eb-9f01-ef5cd6890897.png)
</details>

Image with text
<details>
<summary>Image</summary>

[![alt](https://screenshot.click/24-57-422jn-w0xbf.png)](https://screenshot.click/24-57-422jn-w0xbf.png)
</details>

## More information

Typically, we style the spacing between each elements by using the following method:

```css
.content > * + * {
  margin-top: 3rem;
}
```

Since we now show HTML tags even if the content doesn't exist (e.g. `<h2></h2>`), we hide them by leveraging `:empty` to hide. Previously, we did not have the spacing issue because we would hide the HTML elements with Liquid condition (e.g. `if product.title != blank`).

### Potential solutions

- (To be tested) We could maybe try to use `margin-bottom` instead of `margin-top` for spacing, and leverage `first:child` or `last-child` to cancel the last or first spacing. This could result 1 or 2 extra selectors.
- We could also do something like > *:not(:empty) + * to prevent this.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
