### ISSUE TITLE
Weird focus states on Log in / Reset Password Pages

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#500]
When getting an error message on the Log In Screen and Reset Password screens, it puts some of the text in focus. Can we prevent this from happening as this looks buggy. 

![image](https://user-images.githubusercontent.com/8127145/130980135-35d0989c-e1e0-4759-894d-a73a9cbb3e59.png)
![image](https://user-images.githubusercontent.com/8127145/130980150-f6fde3e2-42e7-4bdb-8d76-e2e60329383b.png)

Video recording: https://screenshot.click/21-15-qj7tj-264ki.mp4

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
