### ISSUE TITLE
Weird overlap of filter drawer and sticky header

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#529]
![image](https://user-images.githubusercontent.com/8127145/131521430-d1261a3f-2c62-4174-8379-082d3ac44e31.png)

On collection pages, when filters are collapsed, and sticky header is enabled, the drawer is below the header and X from filter drawer is overlaps with the header. 

Desired behaviour is that the drawer be entirely overlaid on top of the header.

**Comment by ludoboludo** [comment]
Hey Nick, on which browser/device is this happening ? I was just trying to replicate in Safari or Chrome as well as on iOS but I wasn't able to: [video](https://screenshot.click/21-08-2vcd3-zjsyi.mp4).
Let me know what I might be missing.

**Comment by nicklepine** [comment]
https://screenshot.click/21-42-tc8x8-77tpr.mp4

I am on Chrome Version 92.0.4515.131  , on iOS
