### ISSUE TITLE
Missing Metatitle

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#53]
**Problem**

Dawn theme source seems to include the metadescription for the home/index page, but not the metatitle that I set in the admin. A generic metatitle shows up for the home/index page instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/8127145/122092448-f068e100-cdd7-11eb-9e6c-9693ec6f6f2f.png)
![image](https://user-images.githubusercontent.com/8127145/122092473-f5c62b80-cdd7-11eb-93ab-61ccba19193b.png)

**Comment by ludoboludo** [comment]
There is a title for the page that is the same on any page of the theme. I think this issue might be more relevant: https://github.com/Shopify/dawn/issues/77

In the screenshot above the title is right next to the `<link rel="preconnect"...` above the description.
