### ISSUE TITLE
Product Template: Share Block: Icon not responsive

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#54]
**Problem**
Clipboard icon doesn't do anything. 

**Expected behaviour**
Expectation would be that it copies link to clipboard.

**Screenshot**
![image](https://user-images.githubusercontent.com/8127145/122261024-f1664500-cea1-11eb-83c3-e8fc7ece8f5d.png)

It is happening for me on my Chrome browser, version 90.0.4430.212 https://screenshot.click/21-30-60y1a-wrcyq.mp4

**Comment by tauthomas01** [comment]
I am not sure if it's still relevant, since the icon became a button

![image](https://user-images.githubusercontent.com/658169/124006784-a91e4b00-d9a8-11eb-9161-ea5469952bc1.png)

**Comment by nicklepine** [comment]
True. Closing.
