### ISSUE TITLE
Multi-Column:  Add link/CTA option to columns

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#551]
The current multi column section lets merchants add a CTA at the section level, but doesn't offer the option to include a CTA at each column's level. Merchants may want to use this layout to display content where each column would benefit from their own call to action (or ability to link to different places). 

Can we explore either adding the option to link each column? (by clicking/taping on image / header / content, or by adding a button to each column) 

Video explanation: https://screenshot.click/21-15-fqnvd-jfdvy.mp4

**Comment by melissaperreault** [comment]
## UX Update

Agreed that keeping the button at the section level is a great flexibility to keep. Based on that, the CTA under each column block should be subdued to not compete with the section level button when they could both be visible at the same time. We have a great pattern already with the usage of link followed by the arrow scaling, this is the exact link styling I would recommend for this section.

([Screenshot reference](https://screenshot.click/21-09-yti3p-3cbqt.png))

- [ ] Add 2 new input setting at the Column block level
- [ ] Animate the arrow scaling to match the system in place
