### ISSUE TITLE
Duplicate Image with Text Section

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#559]
In 2.0.0, we seem to have accidentally inserted 2 x the Image with Text section. 

The image with text section should only appear once in the dropdown of  available sections to add. 

![image](https://user-images.githubusercontent.com/8127145/131926871-526bd785-85ad-4344-a99a-19c8997aba45.png)

How to replicate: 

1. Make sure you. have 2.0.0 Dawn installed. 
2. On any page that supports section, click add section. 
3. Observe that image with text appears twice.

**Comment by martinamarien** [comment]
Closing this, because the appropriate team is taking care of it.
