### ISSUE TITLE
Collection Page: Jumps and displays price twice

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#56]
In https://os2-demo.myshopify.com/fr/collections/handbags, the page jumps for a few milliseconds, apparently it displays 2 prices, and then goes back to displaying a single one.

![image](https://user-images.githubusercontent.com/8127145/122849449-8a012880-d2d9-11eb-846d-95fa104de6f7.png)

https://user-images.githubusercontent.com/8127145/122849561-bcab2100-d2d9-11eb-8f16-386fc7db674c.mov

**Comment by chrisberthe** [comment]
@nicklepine can you confirm this is still an issue? I can't replicate.
