### ISSUE TITLE
Localization Form gets double injected?

### ISSUE THREAD

**Issue by no3lillinger** [Shopify/dawn#569]
Hey! We noticed that after installing the geolocation app by shopify, localization gets shown two times. We've run the latest updates to our Dawn.  

![image](https://user-images.githubusercontent.com/89751117/132212629-cd2f691b-62cc-4afb-afa3-84aa4437cd5d.png)

**Comment by kenji-browcode** [comment]
The second one looks like the Geolocation app. Can you confirm that app is not installed and active?

**Comment by no3lillinger** [comment]
Right, it's the Geolocation app. We turned off showing the selectors in the app, the additional selector disappeared of course. We thought it has a connection to the Shopify Dawn themes Language and Currency checkbox/enabler.
Stupid inquiry! Closing this non-issue.
