### ISSUE TITLE
Update Preset #1 + add Preset #2

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#58]
**Preset Default:** 

Color values: 
Fonts: 

**Preset Craft:** 

Color values: 
Fonts:

**Comment by wiktoriaswiecicka** [comment]
### **Preset: Default** 

**Color values**

Solid button label: #FFFFFF
Accent 1: #121212
Accent 2: #334FB4
Text: #121212
Outline button: #121212
Background 1: #FFFFFF
Background 2: #F3F3F3

**Fonts**
Headings and body text: Lato (Light)


### **Preset: Craft**

**Color values**

Solid button label: #EFECEC
Accent 1: #2A332F
Accent 2: #476154
Text: #1C1A1A
Outline button: #7B8382
Background 1: #EFECEC
Background 2: #C1BCAE

**Fonts:**
Headings: Americana (Regular)
Body text: Quattrocento Sans

**Comment by Guillaumegranger1** [comment]
Yup. This all seems accurate 👍
