### ISSUE TITLE
Installments Pop Up: Double Focus Ring

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#59]
- [ ]  weirdest double focus ring happening on the installments modal on iOS (all around the content, and around the close icon) https://user-images.githubusercontent.com/2348980/122496535-f0283b80-cfb9-11eb-9b23-849f586b9b55.PNG
- [ ]  When closing the installments modal, double focus-rings (IMO the focus should come back to the clicked link, not the whole paragraph) https://user-images.githubusercontent.com/2348980/122496545-f3232c00-cfb9-11eb-98be-db7a62b759de.PNG

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
