### ISSUE TITLE
Blog Posts Section: Overlaps on thinner viewports

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#6]
**Problem**
the blog posts on a blog post section can overlap as the page gets thinner and thicker

**Steps**
Add a blog post section with 3 blog posts
Make browser window narrow and observe weird overlap
https://files.slack.com/files-pri/T017D49VC3F-F02319C3998/download/screen_recording_2021-05-25_at_3.25.34_pm.mov

**Comment by chrisberthe** [comment]
I can't replicate the issue either. Going to close but please reopen if you can come across it again.
