### ISSUE TITLE
Create a separate class text-styles for uppercase

### ISSUE THREAD

**Issue by wiktoriaswiecicka-zz** [Shopify/dawn#63]
We have two different text styles of the same size that can look inconsistent when used in different areas in the theme. It's important that in the second one we keep the text-transform: uppercase attached to the class, otherwise letter-spacing will feel a bit off:

<img width="187" alt="Screen Shot 2021-06-18 at 4 08 21 PM" src="https://user-images.githubusercontent.com/61301164/122611498-6aef6600-d04f-11eb-9fe9-218993724caf.png">

**1. Caption** 

letter-spacing: 0.7, 
text-transform: none;

**2. Caption with letter spacing** 

letter-spacing: 1.3
text-transform: uppercase;

@elyseviotto @KaichenWang @Guillaumegranger1

**Comment by melissaperreault** [comment]
Closing since we have to look at the whole typography system first to clean up the styles and hierarchy. We can re-open if needed.
