### ISSUE TITLE
Fix underline link on instalments and dynamic checkout

### ISSUE THREAD

**Issue by wiktoriaswiecicka-zz** [Shopify/dawn#64]
There should be 3px offset on underline links to match other link styles in the theme.

- [ ] Instalment "Learn more"
- [x] Dynamich checkout "More payment options"

@Guillaumegranger1

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
