### ISSUE TITLE
Quantity change issue

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#640]
**Describe the current behavior**

Here is a situation you can run in: 
- you have 3 of the same item in your cart
- the have a stock limit of 10
- you manually input 11
- then you will notice that the quantity updates to 10 but no error is mentioned.

This to me seems like there could be some work done platform wise to handle cases like this. Otherwise we need to run lots of checks and logic.

**Describe the expected behavior**

In the same situation as above, I would expect an error/notification to come up saying the amount requested was above the quantities available. Or something along those lines. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.1.0

**Possible solution**

Having more information returned when updating the cart so we don't have to create some extra logic to compare quantities. 

**Additional context/screenshots**
[Video](https://screenshot.click/21-09-icvc1-cpevr.mp4)

**Comment by andrewetchen** [comment]
Hey Ludo, I was testing this on `2.4.0` and experienced the same results.

I wanted to share the following as it _might_ help figure out the cause 🤞🏼 

- Product with a stock limit of 10
- I added 4 items to the cart.
- I changed the quantity to 11 and it automatically updates the quantity to 10.
- Changing it to 11 a second time produces the error message/text below the quantity 🤔 

https://user-images.githubusercontent.com/28404165/142671304-859a4cf9-872e-48cf-893b-52f3aaced23d.mp4

**Comment by naxorn** [comment]
@andrewetchen Did you try entering a value above 20 twice in a row?  Your video shows you initially entering 20, then 25.

**Comment by naxorn** [comment]
Hey @andrewetchen, played with this a bit and you need to start with a quantity less than the maximum to see the bug, so in your case start with something less than 20.  The first attempt to go over that resets the quantity to 20 without the error, but all subsequent attempts will display the limit error.
