### ISSUE TITLE
Product Page: Incorrect variant image displaying on mobile

### ISSUE THREAD

**Issue by jian-mahmoudi** [Shopify/dawn#641]

**Comment by Zarg-amir** [comment]
I am receiving the same issue and the frustrating part is that I'v contacted shopify support team and the devs got back to me with the simple answer "they can't replicate the same issue on their side so there is no issue". It sure is extremely annoying especially spending weeks on customizing the theme to then know this big issue on the product page. Can someone please fix this

**Comment by sakinurrahman** [comment]
I am facing same problem. How you did solve it?

**Comment by Zarg-amir** [comment]
@jian-mahmoudi It seems like you found a fix to your issue, can you please let me know what you did?
