### ISSUE TITLE
Quantity Update to Cart on Safari shows error message

### ISSUE THREAD

**Issue by justinlangille** [Shopify/dawn#657]
**Describe the current behavior**

Updating the quantity on Safari prompts an error message even though the quantity is actually updating without issue.

**Describe the expected behavior**

There won't be an error message if the quantity is updating properly.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.0.0
- Safari Version 14.1.2 (16611.3.10.1.6)
- macOS Version 11.6 and iOS 14.5

**Possible solution**

Not sure of the solution, the message comes from the `sections.cart.cart_error` translation which is set to `window.cartStrings` in the `theme.liquid` and then used in the `cart.js` 

**Additional context/screenshots**

Error message:

`There was an error when updating your cart please try again
`

iPhone (xcode simulation):

<img width="306" alt="20-40-xicg7-t0dgz" src="https://user-images.githubusercontent.com/17674959/134056474-589fe608-4cb4-476e-9025-c38b93870b0a.png">

Safari: 
<img width="1236" alt="20-40-fecrp-kfklu" src="https://user-images.githubusercontent.com/17674959/134056549-d1b5fe3a-4b67-4cdd-9bec-230cb5730ba1.png">

Issue reported on a merchant's store, was replicable on my own staff store (live store, not a test store)

Video of issue showing that the quantity is actually updating:

https://screenshot.click/20-45-p4zos-z63lp.mp4

**Comment by savraj** [comment]
Yes, we see this issue, actually. I don't think it's fixed yet. Did you have a solution?
