### ISSUE TITLE
[Collection template] Add short description metafield 

### ISSUE THREAD

**Issue by tauthomas01** [Shopify/dawn#67]
- [ ] P0:We will need to add the `Subheading` text setting - pre-populated with standard metafield "Product subtitle".

*FYI: Screenshot is outdated - name of standard metafield is Product subtitle and not Short Description. 

Figma: https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=6766%3A92017

[![alt](https://screenshot.click/16-39-ayo7p-mxl2n.png)](https://screenshot.click/16-39-ayo7p-mxl2n.png)

Note: Post Unite, we'll tackle the Show Product Rating setting (this metafield is not ready yet)

**Comment by tauthomas01** [comment]
Is there a mockup on how it should look like?

**Comment by melissaperreault** [comment]
> Is there a mockup on how it should look like?

They were blocks before but had to deblockify them. There was a lot of changes in the typography, Figma is outdated. I'll ask @wiktoriaswiecicka just to help on figuring out what text style to apply to this content. 

Here are the references:

- [It is this little line of text](https://screenshot.click/21-07-ipohu-nhac7.png), that could be longer and wrap on more than 2 lines. (To account for)
- Collection template [Figma link](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=1190%3A1380)
- It's basically the same outcome for all product cards. 🙏 

Do not hesitate if you have additional questions! Ping me for a quick review anytime!

**Comment by tauthomas01** [comment]
I talked with Brian and we won't be able to display the metafield like in the mockup. See conversation below

![image](https://user-images.githubusercontent.com/658169/124516520-d5bed200-ddaf-11eb-9865-ffbec9328481.png)

cc. @nicklepine @melissaperreault

**Comment by nicklepine** [comment]
Based on this new development (the fact that this usecase is not supported yet) I will adjust severity level to 3.

**Comment by melissaperreault** [comment]
Closing since this is no longer aligned with how we would introduce this. We can always re-open if needed.
