### ISSUE TITLE
Subscription Label missing from Add to cart notification

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#673]
The Subscription label is missing from the add to cart notification modal. 

![image](https://user-images.githubusercontent.com/8127145/134561011-3f4bbd7d-1cb1-41e5-a24f-8e12b96bbf0a.png)

Expected behaviour: 
It should display subscription information like it does on the cart page: 

![image](https://user-images.githubusercontent.com/8127145/134561053-6ece7663-44af-46ea-a252-299fdca988c0.png)

**Comment by LucasLacerdaUX** [comment]
Possible fix:
```liquid
          <p class="cart-notification-product__option">{{ item.selling_plan_allocation.selling_plan.name }}</p>
```
