### ISSUE TITLE
Featured Product section: "View full details" as a setting

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#676]
Merchants may prefer to not link buyers to a full product page from a featured product section, if there are no more details to uncover, or if the merchant wants to preserve a one page experience. 

Could we explore making that "View full details" link its own block, to give that flexibility for merchants?
![image](https://user-images.githubusercontent.com/8127145/134566232-fdaa3294-6fbe-4b3f-89ca-e41c183abd93.png)

**Comment by melissaperreault** [comment]
> Merchants may prefer to not link buyers to a full product page from a featured product section

I  would offer a setting to show or hide but mainly not a block. The link would require to live underneath the share link for  instance and wouldn't be able to  have a side by side layout when they are visible. Also wondering, product pages are more meant to have additional information and details and is key for conversion, but I can see some use cases for succinct product offering and purchase flow.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps
