### ISSUE TITLE
Cart: Issues with Featured Product Section / Quick Add on Cart. 

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#678]
We found some issues with adding a featured product section on the cart page [Screen recording](https://screenshot.click/21-09-rjm09-cgi1f.mp4):

   * - [ ] Adding a product to cart from the featured product section should automatically add the item on the cart page. Currently it does not until a page refresh. 
   * - [ ] After adding the item to cart, if you change a line item quantity of an existing product in the cart, the automatic update adds the item to cart, but it changes the line item of the product in cart to a different quantity (in the video above, red shirt qty went from 7 to 2). 
   
   Expected behaviour: 
   Item should be added to cart automatically. 

   Optimal solution: As part of the add to cart event, have it check if there’s a cart on the page and if there is, grab the section code for main-cart-items and main-cart-footer along with the notification / cart drawer sections, and render them onto the page.  This would be the optimal way to do it because it would just be bundled with the same AJAX request made to the cart API, so it wouldn’t add another separate request.
   
   Potential solution: When adding to bag from a featured product section on the cart, could we refresh the cart page if successful rather than triggering the add to cart notification?

@melissaperreault  Would love to hear your thoughts on the potential solution, or other POV from UX.

**Comment by nicklepine** [comment]
To also investigate: How might we ensure that when adding a product from Quick Add #1388  on a section on the cart page, that the cart updates to include that line item.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
