### ISSUE TITLE
Enhancements considered breaking changes

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#697]
## Context

As we are doing some maintenance and improvements to Dawn, we really want to make sure we can set merchants up for success and keep them on their theme's upgrade path and not introduce breaking changes. With this in mind we sometimes have to make some tradeoffs and hold on releasing enhancements that would break the theme's upgrade path. This ticket should be used to log some of these tradeoffs. 

### List of potential enhancements that would require a breaking change (WIP)

**Image banner section**
- [ ] Include `Adapt to first image` inside the option list of the `Image banner height` setting and remove entirely the checkbox setting `Adapt section height to first image size` and its info text.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
