### ISSUE TITLE
Collage section product/collection title text overflows and is clipped by container

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#699]
When we have the font size range to `150%` the text gets cut off in the `collage` https://screenshot.click/28-03-89dbl-7ohm8.png

This happens when the scales are different: https://screenshot.click/28-13-47dfl-m832n.png

_Originally posted by @sofiamatulis in https://github.com/Shopify/dawn/pull/688#discussion_r717613243_

**Comment by ludoboludo** [comment]
Hey @melissaperreault, [here is a video](https://screenshot.click/21-11-6ztwt-dn47m.mp4) where I test three different sizes: 
- the current one (which ends up being 30px without tweaking the base font)
- when I remove the collage specific styling to get it at 24px
- I also try it without the `h2` class it's currently receiving and have it at 18px
- and then to match the product title on a product that has an image, I add an h4 class to get it at 15px.
