### ISSUE TITLE
Dropdowns: No overflow scrollbar on mobile

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#7]
**Problem**
The overflow scroll bar in the country/ currency selector in the footer is quickly hidden on androids and isn't initially shown in iOS Chrome and Safari.

This makes it looks like I only offer 5 currencies even though I offer more. In the desktop view the overflow scroll bar is always shown.

**Steps**
Ensure Shopify Payments multi-currency support is setup and you are offering more than 6 currencies
on an iOS or Android device go to your dawn storefront
Scroll down to the footer
Click on the box to select a new country/ currency

**Screen recordings**
desktop - https://screenshot.click/19-35-c8h8t-jd061.jpg,
iOS - https://screenshot.click/19-31-rh5lo-e06q0.jpg,
android - https://screenshot.click/19-37-zajox-6muj1.mp4

**Comment by ludoboludo** [comment]
Yeah good point from @tyleralsbury. I checked too and it's meant to be this way on those OS. Android I think does a better job, as it shows the scroll bar when first opening the container.
Here is a capture of it: [video](https://screenshot.click/21-11-9r4u2-t5ul5.mp4) 

In my example I was trying to see if it helps to apply a different background color to each list item.
