### ISSUE TITLE
Syntax error in tag 'render' - Template name must be a quoted string

### ISSUE THREAD

**Issue by jasonhuhx** [Shopify/dawn#70]
**Describe the current behavior**

In a clean forked dawn theme folder, I get the following error after running `shopify theme serve`:

```
┃ ERROR update sections/main-product.liquid:
┃   Liquid syntax error (line 74): Syntax error in tag 'render' - Template name must be a quoted string
┃ ERROR update sections/apps.liquid:
┃   Liquid syntax error (line 3): Syntax error in tag 'render' - Template name must be a quoted string
┃ ERROR update templates/404.json:
┃   File extension is not valid for file templates/404.json
┃ ERROR update templates/article.json:
┃   File extension is not valid for file templates/article.json
┃ ERROR update templates/blog.json:
┃   File extension is not valid for file templates/blog.json
┃ ERROR update templates/collection.json:
┃   File extension is not valid for file templates/collection.json
┃ ERROR update templates/cart.json:
┃   File extension is not valid for file templates/cart.json
┃ ERROR update templates/list-collections.json:
┃   File extension is not valid for file templates/list-collections.json
┃ ERROR update templates/index.json:
┃   File extension is not valid for file templates/index.json
┃ ERROR update templates/page.json:
┃   File extension is not valid for file templates/page.json
┃ ERROR update templates/page.contact.json:
┃   File extension is not valid for file templates/page.contact.json
┃ ERROR update templates/password.json:
┃   File extension is not valid for file templates/password.json
┃ ERROR update templates/product.json:
┃   File extension is not valid for file templates/product.json
┃   Section type 'main-product' does not refer to an existing section file
┃ ERROR update templates/search.json:
┃   File extension is not valid for file templates/search.json
┃ 
┃ Serving .
┃ 
┃ Please open this URL in your browser:
┃ http://127.0.0.1:9292

```

**Device information (browsers and operating system)**
- macOS Version 11.2.1
- Shopify CLI version: 2.0.1

**Comment by davodavodavo3** [comment]
Same for me @jasonhuhx

**Comment by chrisborbidge** [comment]
+1

**Comment by knsakib** [comment]
+1 (no test?! everything will be done after feedback! :D )

**Comment by custombusinesssystems** [comment]
+1 and when i shopify theme serve I get the following image

`<iframe src="https://share.getcloudapp.com/RBulZjmq?branding=true&amp;embed=true&amp;title=true" width="575" height="400" style="border:none" frameborder="0" allowtransparency="true" `allowfullscreen="true"></iframe>``

**Comment by sebszocinski** [comment]
+1 Great launch Shopify 🤣

**Comment by carsick** [comment]
+1

**Comment by arnoldoosterom** [comment]
+1

**Comment by owenfranssen** [comment]
Ditto. Same errors here.

ubuntu 20.04.2
Shopify CLI 2.0.1
ruby 2.7.0p0

**Comment by custombusinesssystems** [comment]
seems odd but this answer to another question may help

https://github.com/Shopify/dawn/issues/71#issuecomment-871274773

**Comment by owenfranssen** [comment]
I tried that.
ran `shopify logout`
created a new staff account on the development store with theme privileges (among others)
ran `shopify login --store store.myshopify.com`
ran `shopify theme serve`
Same results

**Comment by davodavodavo3** [comment]
Create a new store with developer preview and all will work

**Comment by chrisberthe** [comment]
Sorry to hear this isn't working.

Unfortunately, there seems to be a bit of confusion around the setup process for new stores with the developer preview. As a result, we'll be updating our docs to clarify some of these things. Stay tuned for updates to [here](https://shopify.dev/themes/tools/cli/getting-started) and [here](https://shopify.dev/themes/tools/cli/core-commands#login). In the meantime, you can try adding a new staff account to the shop and leveraging that to login. Also, **try first logging in to your store's `admin/` before logging in via the CLI**, this should fix your issue.

Also, please note this isn't a Dawn issue. So I'd recommend you check out the https://github.com/Shopify/shopify-cli repo for more help. [This particular issue](https://github.com/Shopify/shopify-cli/issues/1309.) may be relevant to yours as well.

**Comment by imrank1** [comment]
+1 exp the same. Trying the solutions mentioned above did not work for me.
