### ISSUE TITLE
App Embed doesn't load on proxy page

### ISSUE THREAD

**Issue by nirali-hulkapps** [Shopify/dawn#704]
**Describe the current behavior**
App Embed loads on every page except proxy pages.

**Describe the expected behavior**
App Embed can have some useful variables for proxy page. It should Embed blocks for proxy page.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0
- Chrome Version 91.0.4472.114

**Possible solution**
- N/A

[Possibly duplicate of](https://github.com/Shopify/dawn/issues/220), but in my case it's not loading any other variables as well from embed app to proxy page.

**Comment by mmorissette** [comment]
This issue should be resolved now. @nirali-hulkapps let us know if you run into any other issues.
