### ISSUE TITLE
Video enhancing for mobil and desktop

### ISSUE THREAD

**Issue by Miktau** [Shopify/dawn#707]
Issue:
When you embed or upload a video from Youtube you have to go “out” from product page to play the video. Link is under. (Only on mobile)
Also it would be nice that you can crop YT videos to be the same ratios as the photos. I know this is possible if we upload directly but we mainly upload YT videos and therefor need a function for cropping. 
https://famme.no/products/camo-tights

Optimal:
Attach is https://www.revolutionrace.no/herre/bukser/friluftsbukser-turbukser/rvrc-gp-pro-pants-men?Color=2301. 
Here you can play the video without going out of the product page. Also the cropping is also better as you can upload YT video that is horizontal but crop the sides so it will display as the same ratios as our photos

Is this something you have in progress fixing?

**Comment by gregjotau** [comment]
This one is really important!
