### ISSUE TITLE
Question about serving the theme

### ISSUE THREAD

**Issue by davodavodavo3** [Shopify/dawn#71]
Hi everyone,

LOL, I'm not the first developer with a question right?

Guys, when I try to serve the theme it show this message
![image](https://user-images.githubusercontent.com/10462563/123886271-22de1680-d960-11eb-91f3-8b7dd4f7f98f.png)

Also the CLI is throwing few issues related to the json templates
![image](https://user-images.githubusercontent.com/10462563/123886320-3f7a4e80-d960-11eb-8960-3f12c86b1c6d.png)

Does the OS 2.0 is live or still not, or maybe I'm doing something wrong?(I used the new Shopify CLI with other themes and it works correct)

**Comment by kayluhb** [comment]
I'm receiving this error when integrating with github as well. The github integration logs say


```
09:27 PM Fetching new theme files

09:27 PM Files fetched

09:27 PM Error: sections/apps.liquid, Validation failed: Liquid syntax error (line 3): Syntax error in tag 'render' - Template name must be a quoted string

09:27 PM Error: sections/main-product.liquid, Validation failed: Liquid syntax error (line 74): Syntax error in tag 'render' - Template name must be a quoted string

09:27 PM Error: templates/index.json, Validation failed: File extension is not valid for file templates/index.json

09:27 PM Error: templates/cart.json, Validation failed: File extension is not valid for file templates/cart.json

09:27 PM Error: templates/password.json, Validation failed: File extension is not valid for file templates/password.json

09:27 PM Error: templates/page.contact.json, Validation failed: File extension is not valid for file templates/page.contact.json

09:27 PM Error: templates/blog.json, Validation failed: File extension is not valid for file templates/blog.json

09:27 PM Error: templates/page.json, Validation failed: File extension is not valid for file templates/page.json

09:27 PM Error: templates/list-collections.json, Validation failed: File extension is not valid for file templates/list-collections.json

09:27 PM Error: templates/search.json, Validation failed: File extension is not valid for file templates/search.json

09:27 PM Error: templates/product.json, Validation failed: File extension is not valid for file templates/product.json

09:27 PM Error: templates/404.json, Validation failed: File extension is not valid for file templates/404.json

09:27 PM Error: templates/collection.json, Validation failed: File extension is not valid for file templates/collection.json

09:27 PM Error: templates/article.json, Validation failed: File extension is not valid for file templates/article.json

09:27 PM 200 succeeded, 0 warnings, 14 failed

09:27 PM Theme updated!
```

<img width="946" alt="Screen Shot 2021-06-29 at 8 32 25 PM" src="https://user-images.githubusercontent.com/29550/123888464-2d28f200-d919-11eb-9c19-bfa2b281fe8e.png">

**Comment by knsakib** [comment]
+1

**Comment by aledimbean** [comment]
+1 Same errors here and 404 screen.

**Comment by meltinbit** [comment]
I made it work. Reading the documentation I found that you must have a Staff Account on the store you log in for serving the Dawn theme. If logged in with Partner Account it does not work. 
Hope it helps.

![Screenshot 2021-06-30 at 12 13 47](https://user-images.githubusercontent.com/24719939/123943629-a289d680-d99c-11eb-869f-b9151859b9d2.png)
https://shopify.dev/themes/getting-started/create

**Comment by davodavodavo3** [comment]
@meltinbit is correct. This seems still in development.

So create a new store with developer preview and all will work.

**Comment by chrisberthe** [comment]
Related: https://github.com/Shopify/dawn/issues/70#issuecomment-871350076
