### ISSUE TITLE
Structured data for product image missing

### ISSUE THREAD

**Issue by bredowmax** [Shopify/dawn#713]
**Describe the enhancement you'd like**
After launching a Dawn theme, Google Search Console does not find product images anymore. Looking into the source code of the live page, I can confirm. There is code in the theme to add image structured data - but it doesn't seem to work. This happens for all products that don't have an explicit variant set up. It _does_ work for those products that have several variants.

**Additional context/screenshots**
Live page: https://www.frenchgirlorganics.com/products/lumiere-caramel-shimmer-oil
Google Results: https://search.google.com/test/rich-results?id=zOC-sJXgkJs2wYYIJGeyPg

![Screenshot 2021-09-29 at 16 56 38](https://user-images.githubusercontent.com/30573532/135347315-4d418b12-24f8-484c-8030-e29829755df8.png)
![Screenshot 2021-09-29 at 16 55 41](https://user-images.githubusercontent.com/30573532/135347248-196b641f-2dea-4ef7-89e7-5bf951a96c6e.png)
![Screenshot 2021-09-29 at 16 55 26](https://user-images.githubusercontent.com/30573532/135347250-edd5be7a-fa53-4cf4-94e9-507183c2f60c.png)
![Screenshot 2021-09-29 at 16 55 14](https://user-images.githubusercontent.com/30573532/135347251-3e82ea78-d267-4227-b0f8-3cf282adc85c.png)

**Comment by bredowmax** [comment]
Appears to be related to #709 & #374

**Comment by gregjotau** [comment]
Yeah, somewhat related, but #709 is another structured data type.
