### ISSUE TITLE
[Urgent] Translation Issue

### ISSUE THREAD

**Issue by translation-platform** [Shopify/dawn#72]
:wave: Hello, International Languages team here!

We're [working](https://vault.shopify.io/projects/7404) to make it easier for translators to ask questions to developers.
In the meantime, we're sending existing questions to the person we think has the most context.
Here's a list of the questions that we would like your help answering - **click on the link and use the textbox to reply to the translator's query**:

- [This preposition of really can't be translated in Finnish without the context.](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/7410f0c4fa9a)

https://github.com/Shopify/dawn/blob/e06c6f5a02f77adadc177107f7b694faca33ad62/locales/en.default.json#L73

- [With no context, we cannot come up with an accurate translation. The same goes for "To".Please advise. Thank you.](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/cfd2c165e582)
   - [+RU](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/cfd2c165e582#comment-814f69f39861)

https://github.com/Shopify/dawn/blob/e06c6f5a02f77adadc177107f7b694faca33ad62/locales/en.default.json#L230

- [Is it like the word "of" in "Showing {count} of {total} products"?](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/dea8e65ad8ef)
   - [+RU](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/dea8e65ad8ef#comment-b70b048896a3)

https://github.com/Shopify/dawn/blob/e06c6f5a02f77adadc177107f7b694faca33ad62/locales/en.default.json#L73

- [Is it related to "reset to" or "from...to..."?](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/c86c72b0d013)
   - [+RU](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/c86c72b0d013#comment-f12b017573dc)

https://github.com/Shopify/dawn/blob/e06c6f5a02f77adadc177107f7b694faca33ad62/locales/en.default.json#L247

- [Is this a standalone string or will it be followed by the very page number?Thank you.](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/d4c02d46e2c5)

https://github.com/Shopify/dawn/blob/e06c6f5a02f77adadc177107f7b694faca33ad62/locales/en.default.json#L151

- [Could you provide me with some context please?](https://translation-platform.shopifycloud.com/repositories/Shopify/dawn/buyer/issues/73174de848ab)

https://github.com/Shopify/dawn/blob/e06c6f5a02f77adadc177107f7b694faca33ad62/locales/en.default.json#L9

---
- If the question is not valid anymore, please add a comment using the translation platform form.
- If you think someone else has more context, please ping them in this issue to answer the translator's question(s).
- Make sure to use the text box on translation platform to reply.
- If the question is about a misspelling issue, please reply and hit "Resolve Issue" once the misspelling is corrected.
- **Please, don't close this issue. @translation-platform will close it automatically once all questions are answered.**

Questions? Hop in the [#help-i18n-and-translation](https://shopify.slack.com/messages/C7TJQLVC7) Slack channel.

**Comment by chrisberthe** [comment]
For @Shopify/themes-front-end-developers: I provided more clarification for this list of strings. Let's leave this issue open until all buyer-facing translations are returned: #69.

**Comment by gregjotau** [comment]
![Screenshot 2021-07-01 at 23 56 55](https://user-images.githubusercontent.com/13047497/124194050-2b516100-dac8-11eb-9bc0-6014b407f730.png)

Seems some of the "bulit in" locale files are missing translations.
