### ISSUE TITLE
Option to disable zoom on product pages

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#733]
Merchants are requesting the option to remove zoom from product pages. This comes in handy for merchants that don't have high quality images, or simply don't sell the type of products where zooming on images is important (i.e. food items, services, etc) 

Debut solves this with a 'Enable image zoom" setting. 
![image](https://user-images.githubusercontent.com/8127145/135907257-16f0c161-764c-4d1d-9d57-cf0bcdae67a4.png)

* Note: Merchants should still be able to play video / 3d media with this setting enabled.

**Comment by bredowmax** [comment]
Oh yes please. It's one of the first features I deactivate on a new Dawn build

**Comment by tomotomy** [comment]
It would be dropdown that has two options enable and disable in this issue.

**Comment by kimberlyoleiro** [comment]
This feature is now available on Dawn 9.0. Closing this ticket
