### ISSUE TITLE
Slider numbers are inaccurate on small mobile screens

### ISSUE THREAD

**Issue by mikevich** [Shopify/dawn#834]
**Describe the current behavior**

The pagination in the slider option used in the Feature Collection and Collection List sections breaks on smaller mobile screens (below 362px in width). With larger number of products/collections, at least one page number skips, and causes subsequent page numbers to be inaccurate.

The JS that controls this uses the ratio between the total width of the section, which is responsive to screen size, and the current scroll value. `Math.round` is used to convert this ratio into a page number.

![image](https://user-images.githubusercontent.com/26332238/139111237-5ceeb486-9c80-4ef5-82d4-7052d5e7b8d1.png)

**Describe the expected behavior**

Page numbers should progress sequentially.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.3.0
- Chrome Version 94.0.4606.81
- macOS Version 11.6

**Possible solution**
Change `Math.round` to `Math.ceil` to ensure the ratio is always rounded up. This makes the page numbers work properly on both small and regular size mobile screens, in both sections.

![image](https://user-images.githubusercontent.com/26332238/139111350-c5163d77-a642-4e8b-8b3b-35f538761e24.png)

**Additional context/screenshots**

[Video showing the problem](https://screenshot.click/27-39-9h72j-q5j9m.mp4)

[Video showing issue resolved after changing to Math.ceil](https://screenshot.click/27-55-vljbm-b63y7.mp4)

**Comment by DigitalStu** [comment]
This has also cropped up with slider images on a product page in Dawn, the possible solution above did work as a fix, thanks.
