### ISSUE TITLE
[Product] Display variant inventory quantity

### ISSUE THREAD

**Issue by andrewetchen** [Shopify/dawn#870]
### Describe the enhancement you'd like

Add an inventory block on the product page and featured product section to display the inventory quantity on variant selection.

https://www.nngroup.com/articles/ecommerce-product-pages
>Customers need to have enough information to make an informed purchase decision. The product page, or product-detail page, is where users decide whether and what to buy. The page must include complete product information, educating and informing the user about the product in a straightforward way.

Displaying the product inventory count (_or stock level_) can help customers make informed purchasing decisions. For stores with limited product quantities, an inventory count can help create a positive sense of urgency and excitement during the buyer journey. And with [Black Friday Cyber Monday](https://www.shopify.ca/bfcm) and the holidays soon approaching, there could be other use cases.

**Potential drawbacks**
- Stores that allow customers to purchase the item when it's [out of stock](https://help.shopify.com/en/manual/products/inventory/track_inventory#selling-when-out-of-stock).
- Stores that [sell services or digital products](https://help.shopify.com/en/manual/products/digital-service-product).

A quick solution would be to make sure we don't enable the inventory block by default on the product page and featured product section.

###  Additional context

The Shopify Help Center currently lists the inventory feature as a supported customization for Dawn:
- [Show variant inventory on the product page](https://help.shopify.com/en/manual/online-store/themes/os20/themes-by-shopify/dawn/customize#show-variant-inventory-on-the-product-page)
- [Eligible](https://help.shopify.com/en/manual/online-store/themes/theme-support#shopify-design-policy) merchants can submit a support request to have this added to their Dawn theme.

**Here's a video showing the inventory on the product page**

https://user-images.githubusercontent.com/28404165/141182865-e0124baa-7dc1-40d6-b1ec-da6e51a49654.mp4

### Next steps

Submit a PR to add an inventory block on the product page and featured product section.

**Comment by gregjotau** [comment]
![screenshot](https://user-images.githubusercontent.com/13047497/157449435-b1c90bc1-3c76-40f6-8b99-da4225980e66.png)

```
The problem is that the inventory quantity value is not included in the variant javascript object, so we can't check it from there, and this theme doesn't have a master variants select to which we could have added thw inventory quantity values for each select option.

```

Getting some feedback on inventory quantity for a customization we want done. Is there a plan to make inventory quantity more "available" in the theme as a whole @ludoboludo ?

**Comment by ludoboludo** [comment]
@gregjotau we should re review the PR @andrewetchen had done here: https://github.com/Shopify/dawn/pull/876. So we can have it come up when/if necessary.

**Comment by andrewetchen** [comment]
> @andrewetchen Is this a duplicate of #876? If so, would you please close one

Hey @kimberlyoleiro, I originally created https://github.com/Shopify/dawn/issues/870 to serve as context and https://github.com/Shopify/dawn/pull/876 was created to action it.

For tracking progress or project related purposes, referring to this issue would be better than the pull request. I'm actually planning on creating a new pull request and might close 876 to reduce noise.
