### ISSUE TITLE
Cart Drawer

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#877]
[Cart drawer figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13659%3A96284)

- [ ] Create a global setting for cart and move `enable cart notes` and `show vendor` to the global settings. Add dropdown for the colour scheme under the `drawers and popups` global setting. [Screenshot](https://screenshot.click/21-03-1tlpp-y0b59.png)
- [ ] Empty state design. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13884%3A107054) | Empty state design with collection. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13884%3A110698)
- [ ] Cart note pattern [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13884%3A108186)
- [ ] Colour schemes. [Figma.](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13884%3A111446) |  Other drawers colour schemes. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13998%3A104509)
- [ ] Art directions. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=14040%3A97169)
- [ ] A11y annotation. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13998%3A102007)

Dynamic checkout will not be added until the new year.

@tyleralsbury

**Comment by ludoboludo** [comment]
For the colour schemes, I think that should be its own PR. As it supposed to impact other drawers and not just the cart one. 

There is already to be a good amount of testing needed for the cart drawer only, so having the colour scheme update on its own would be beneficial.

**Comment by Oliviammarcello** [comment]
@ludoboludo Makes sense, added an issue here: https://github.com/Shopify/dawn/issues/1611
