### ISSUE TITLE
Quick Add

### ISSUE THREAD

**Issue by duygukalaycioglu** [Shopify/dawn#882]
**MVP Brief**: Add ability of "quick buy" on product cards for merchants with low intents to purchase. 
**Variations:** Product cards with no variant, Product cards with 1 or more variants. 
**Design File:** [Figma File](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/?node-id=14203%3A99898)

**1. Variations**
There will be 2 different named buttons for 2 variations. 

- [ ] **Variation 1:** Product Card with no variant. Buttons for this variant will be named "Add to cart"
- [ ] **Variation 2:** Product Cards with 1 or more variants. Buttons for this variant will be named "Choose Options". 
<img width="717" alt="Screen Shot 2021-11-15 at 3 20 51 PM" src="https://user-images.githubusercontent.com/88160784/141868061-bcbdc25b-6d74-48e9-a181-0851c9a64d6f.png">

**2. User Flows**
There will be 2 different flows for 2 variations. 

**Variation 1: Product Card with no variant.** 

<img width="716" alt="Screen Shot 2021-11-16 at 4 26 06 PM" src="https://user-images.githubusercontent.com/88160784/142087363-8db66375-8720-45d4-8889-eee261cc65fc.png">

- [ ] When the buyer clicks "add to cart" from the product card, the product will be automatically added to the cart. The button will transition into "Added to cart" - stays in this state (also make the button disabled to avoid adds by mistake) for 5 milliseconds and turns back into default state. 

<img width="735" alt="Screen Shot 2021-11-16 at 4 20 22 PM" src="https://user-images.githubusercontent.com/88160784/142086809-e9fcb096-f380-49cd-9b84-44c83209a123.png">

- [ ] The cart pop up will be exposed once the product is added to cart and disappear. This interaction is currently existing in Dawn, so no change. In this case, the buyer can add only 1 product at once. If they would like to remove the product from the cart, they will need to navigate to the cart. 

<img width="592" alt="novariant - added to cart" src="https://user-images.githubusercontent.com/88160784/141868437-f1ff8c60-be24-4470-994b-6ef2290f8f56.png">

**Variation 1: Edge Case Scenario**
- [ ] The buyer adds a product more than once and hits the max limit of items in stock. In this case, when the limit is hit – change the button label to "Sold out" and to disabled state. If the buyer removes a product from their cart, take the button back to its default state "Add to cart".  _FYI this is reviewed and approved by the content designer and other theme designers._
<img width="710" alt="Screen Shot 2021-11-16 at 4 35 53 PM" src="https://user-images.githubusercontent.com/88160784/142088149-72353a46-76d0-4afa-a212-f5a8c67b8108.png">

**Variation 2: Product Card with 1 or more variants.**

<img width="718" alt="Screen Shot 2021-11-16 at 4 27 37 PM" src="https://user-images.githubusercontent.com/88160784/142087478-75be5096-0104-4ed0-93bc-1fa925a743ab.png">

- [ ] When the buyer clicks "choose options" from the product card, a quick view modal will be exposed for the buyer to select their options, and add to cart. In this case, the buyer can add more than 1 product at once. Both the product title and the view full details is clickable to the product page. (focus state: same as current Dawn specs - underlined)
<img width="716" alt="Screen Shot 2021-11-16 at 4 22 46 PM" src="https://user-images.githubusercontent.com/88160784/142087057-c9e29222-efe9-4365-9250-d949c169619c.png">

- [ ] When the buyer clicks "add to cart" from the quick view modal, the button will transition into "Added to cart" - s stays in this state (also make the button disabled to avoid adds by mistake) for 5 milliseconds and turns back into default state. 
<img width="715" alt="Screen Shot 2021-11-16 at 4 24 14 PM" src="https://user-images.githubusercontent.com/88160784/142087209-67be74d9-6633-44dc-a088-f87862988d63.png">

- [ ] After the buyer closes the quick view modal, the interaction is the same as variant 1. The cart pop up will be exposed once the product is added to cart and disappear. 
<img width="731" alt="Screen Shot 2021-11-16 at 4 25 03 PM" src="https://user-images.githubusercontent.com/88160784/142087284-9e7a07f9-9ffd-4b86-947c-721fc55f06d4.png">

**3. Settings**

- [ ] Add "Enable quick buy button" to the featured collection settings 

<img width="187" alt="Screen Shot 2021-11-16 at 4 38 10 PM" src="https://user-images.githubusercontent.com/88160784/142088310-c6a668cb-7c98-4cb2-a0b3-37f8b4939703.png">

**Note related to the impact on quick buy's cart view via new cart settings:** 
With the new cart settings, the merchant will be able to choose from different cart type options.
- Drawer
- Pop up notification
- Page
<img width="280" alt="Screen Shot 2021-11-16 at 4 42 21 PM" src="https://user-images.githubusercontent.com/88160784/142088639-9360ad1b-f61e-473a-bc52-514ef3a797e8.png">

**Impact on Quick Buy flow**
After the buyer adds and item to the cart, the cart type that will be exposed will depend on the merchant's cart type selection. Meaning, 

- If the merchant has selected a drawer cart type from new cart settings – show the cart in drawer.
- If the merchant has selected a pop up notification – show the cart in pop up. 
- If the merchant has selected a page – direct them to the checkout page.

- [ ] Add "Enable quick buy button" to the product grid settings.
<img width="388" alt="product grid settings" src="https://user-images.githubusercontent.com/88160784/153310371-e2c5b37f-7ef0-4280-b0ee-add0546cc0bf.png">

**Button transition** – Here is the link to the [prototype](https://www.figma.com/proto/C7c5tmNp5qUNKyr11bAMHB/Quick-buy---button-transition?page-id=0%3A1&node-id=2%3A153&viewport=357%2C48%2C1&scaling=min-zoom).

**Full details** (desktop and mobile views, flows and all cart types) can be found in the [Figma file](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/?node-id=14203%3A99898).

**Comment by svinkle** [comment]
[A11y Annotations](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=14826%3A86941) are now available in the Figma file.

**Comment by notrealdev** [comment]
Hi, when will it be released?

**Comment by LucasLacerdaUX** [comment]
cc @duygukalaycioglu 

I have a few questions:

1. Add to Cart button becoming Sold out on error: is the expectation that this behaviour [applies to Product Pages](https://screenshot.click/10-24-ptjd3-0j8em.mp4) or can we restrict it to Quick Buy? 
    - If we apply to Product pages (and modal), [it may result in a weird user experience](https://screenshot.click/10-26-zl9z5-s76ie.mp4) when you're trying to add more than what is available but you haven't reached the maximum in your cart. Both "You have the maximum amount in your cart" and "You can't add more than X products" errors returns the same error code, so we can't really differentiate them.
    - If we apply to Quick Buy only, this isn't an issue as we're always adding a quantity of `1`. Are we okay with that?

2. The Add to Cart -> Added to Cart animation does not consider the loading spinner state that happens in-between. Do we want to use this same animation from the Figma prototype?

3. How long should the Added to cart success message stay visible? This issue mentions `5 milliseconds` but I'm pretty sure that value is wrong.
     - Does blocking the button while the success message is displayed feels good in the implemented result? I have mixed feelings. 
     - In product pages or modals, it almost feels like we are making the buying experience slower if this delay is too long (over 3 seconds). They also don't have any feedback that the button will return to the normal state after a timeout, so another reason to keep it short. 
     - But on the other hand, if it's too fast you may not be able to read what was just presented, especially because text is too similar (Add to Cart and Added to Cart).

4. Is it correct that we shouldn't be able to zoom in on Product Images inside the modal?

**Comment by nicklepine** [comment]
> Is it correct that we shouldn't be able to zoom in on Product Images inside the modal?
Aligned with not having zoom on the modal. cc: @duygukalaycioglu @LucasLacerdaUX

**Comment by bredowmax** [comment]
I noticed that if the theme is set to these settings, there is no padding to the right of this Quick-Add ATC

(Viewing on Mobile)
- 2 Columns on Mobile
- Swipe on Mobile
- Product Cards

![Screen Shot 2022-03-07 at 3 06 07 PM](https://user-images.githubusercontent.com/30573532/157109948-f32d87bd-7657-4175-9204-6dae02af1402.png)
![Screen Shot 2022-03-07 at 3 06 00 PM](https://user-images.githubusercontent.com/30573532/157109951-953e15a2-1a89-4083-a6a4-bccd8f9ab6c6.png)
