### ISSUE TITLE
Collection.filters is always limited 1000?

### ISSUE THREAD

**Issue by cupelapps** [Shopify/dawn#89]
**Describe the enhancement you'd like**
It seems that collection.filters always stops at 1000. Is it expected behavior?

**Describe alternatives you've considered**
It should filter based on the no of products in the store. or is there any plan to restrict collection.products size to 1000 max?

**Additional context/screenshots**
![1000limit](https://user-images.githubusercontent.com/20922495/124113552-320cb380-da89-11eb-9aa6-e8d4b5adadda.png)

**Comment by chrisberthe** [comment]
Hi @cupelapps, this is the expected behaviour. When filters are applied, only the first 1000 products by sort order are returned. While it's the current limitation, we're looking into future improvements to this.
