### ISSUE TITLE
New Section - "Tabs"

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#907]
**Describe the enhancement you'd like**
Add an accordion section (example use case: FAQs). Each collapsible tab in the accordion is a block.

**Describe alternatives you've considered**
Could reuse implementation from Product page's collapsible tabs

**Additional context/screenshots**
n/a

**Comment by Oliviammarcello** [comment]
We will be adding a new Tabs section which will work similarly to the accordion blocks on the product page. The Figma file can be [found here.](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=14147%3A97898)

**Section details**
- Each tab will be a block that will have the exact same settings and functionality as the accordion. 
- Merchants will be able to set both a secondary background colour as a background or row colour (similar to multicolumn) and use the colour scheme setting. The secondary background (4% opacity of text) will be treated as background 1. [Figma.](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=14353%3A83880)
- The image size and image position will work the same as the image with text section. The _adapt to content height_ setting will stretch the image height to fit the height of the tabs (when they are closed). The width of the image will be fixed. During the build, we can work to determine what a good max and min-height should be. [Figma.](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=14147%3A97981)
- Hover states: The current accordion blocks on the PDP don't have a hover state. The hover state used here should also apply to the accordion. The focus state can be repurposed from the accordion. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=14437%3A84209)
- All animations used in the accordion should be used here as well.

cc @sofiamatulis Feel free to ping me if you have any questions.

**Comment by pierre-oord** [comment]
On the product page, the accordion does not have support for most HTML, e.g. <li> elements cannot be used. On product pages this would be useful. Could you consider this as well?

**Comment by sofiamatulis** [comment]
👋  @pierre-oord , thanks for providing some feedback on the features we're adding to Dawn :) . 

In the collapsible tab on the product page, you could select a page instead under `Tab content from page`  that doesn't prevent any of the HTML formatting already. 

Are you hoping to be able to add HTML elements directly in the field `Tab content` ? I can create an issue so we can look more into this potential change and go over it with the rest of the team.

**Comment by pierre-oord** [comment]
Hi Sofia,

I'll look into the page content idea. However, that sounds very complicated for what we want to achieve: bullet lists and possibly a small image. We have now used "bullet points" that are not part of a list, but that does not align nicely. See below. I think many people would like to use bullet lists on the product page.

**Comment by sofiamatulis** [comment]
Hi @pierre-oord  :)!  Thanks for providing more insight to this. Would you mind maybe creating an issue with the details you provided in your comment ?

If we were to add those options on the settings we would then need to provide more settings for styling the list, the image and image sizing, etc. These are options that are present in the page editor and it offers all the potential customization you'd want.

It most likely won't be set as a high priority over some of the other issues/bugs/features we're working on but it would be good to have it there for visibility.

**Comment by ludoboludo** [comment]
Since this PR https://github.com/Shopify/dawn/pull/956 was merged, I will close this issue.
