### ISSUE TITLE
Add new settings to image email sign up banner

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#915]
**Describe the enhancement you'd like**
Add the following section level settings to `Image Email Signup Banner`:
- `Text alignment`
- `Desktop text position`

**Describe alternatives you've considered**
n/a

**Additional context/screenshots**
![Screen Shot 2021-11-15 at 3 13 21 PM](https://user-images.githubusercontent.com/3710548/141847517-41a6a888-a59a-4dcd-8555-58449df53397.png)

**Comment by martinamarien** [comment]
Closing this issue as it was addressed in #916
