### ISSUE TITLE
Dawn does not render menus for some 404 pages

### ISSUE THREAD

**Issue by MikeParkin** [Shopify/dawn#919]
We discovered this with a client website we have recently released on Shopify Storefront 2.0 / Dawn. 

I expect this is actually a platform issue and nothing related to the theme, but I've had two support requests closed by Shopify support, so I'm raising it here in the hopes that a core developer can alert someone internally and get this sorted.

**Describe the current behavior**
For some 404 pages, the menus in the Dawn theme are not rendered.

**Describe the expected behavior**
I expect menus to render on all 404 pages, regardless of the URL.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Additional context/screenshots**
Menu's are not rendered on some Shopify Dawn 404 pages. 

The same issue can be seen on the default Dawn theme as the Studio Nicholson website;

The below URLs are just two random URLs that are supposed to 404. 

For some reason /a does not render the menus but /ab does

No menu's rendered;
https://dawn-theme-default.myshopify.com/a 

<img width="709" alt="Screenshot 2021-11-19 at 16 14 02" src="https://user-images.githubusercontent.com/106529/142655283-3dddaafc-8fe5-4d12-9d16-f6e1cd313243.png">

Menu's rendered:
https://dawn-theme-default.myshopify.com/ab

<img width="719" alt="Screenshot 2021-11-19 at 16 14 05" src="https://user-images.githubusercontent.com/106529/142655293-8c645af1-cdf6-438c-8d09-baad50857004.png">

Comparing the code, the one that renders the menu is rendered by “storefront-renderer” whilst the one that fails is being rendered by “core” - so I am guessing that for some 404 pages rather than rendering the page with the separate storefront renderer, it's failing back to the core monolith and there is a bug or an incomplete feature and the menu's do not render. 

Would be great to know why and get this fixed, because it must be happening for all customers using Dawn.

**Comment by ludoboludo** [comment]
Hi @MikeParkin 👋 , thanks for bringing this up. We've had some report of this as well and it's an issue with how the 404 template is rendered. Not a theme issue but something we brought up to another team that's looking into it 👍 

We had a bit of a conversation here if you want to catch up/see a potential fix you can apply locally for the time being: https://github.com/Shopify/dawn/issues/873

In the mean time, I will close this issue and keep the one linked above open. 

Thanks for taking the time to bring this up to us! And all the details is much appreciated 🤗
