### ISSUE TITLE
Custom Sections not showing up in Theme Editor

### ISSUE THREAD

**Issue by iliquifysnacks** [Shopify/dawn#92]
I'm creating a new type of section for my store so that users can add it to a page in the editor. I would expect, that when I create a new liquid file in the /sections directory and tag it "section" it shows up in the list of sections a user can add to a page. 

See schema for the section below. If I include the section implicitly in the theme.liquid, it shows up without problems. 

Am I missing something or is this behaviour intended and new sections can't be added?

<img width="919" alt="Screenshot 2021-07-02 at 14 25 19" src="https://user-images.githubusercontent.com/46820607/124274296-60e66080-db41-11eb-84ac-f8dcd96c4d45.png">
<img width="687" alt="Screenshot 2021-07-02 at 14 25 33" src="https://user-images.githubusercontent.com/46820607/124274303-6348ba80-db41-11eb-942a-69e6b385224f.png">

**Comment by chrisberthe** [comment]
Hi @iliquifysnacks, in this case I don't think `default` is what you want. I believe you want `"presets"`: https://shopify.dev/themes/architecture/sections/section-schema#presets. Something like:
```json
"presets": {
  "name": "Pre-header",
  "blocks": [
    {
      "type": "pre-header"
    }
  ]
}
```

This is what populates the "Add section" dropdown within the theme editor. Can you give this a try?

**Comment by iliquifysnacks** [comment]
Thank you very much for the clarification! This works and now the section shows up without a problem 👍
