### ISSUE TITLE
[Global settings] Layout

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#925]
### Settings reference
- [Internal Figma link](https://www.figma.com/file/9FOEO0DFKgNDjiqxMakiLB/Design-Settings-Components?node-id=141%3A10944)

### Some considerations

**Vertical spacing between sections**
   - [x] Increase range max - Meli to test
   - Minimum value 0
      - [x] Rich text [Background 1 color scheme should behave](https://screenshot.click/21-11-xg6ow-omnf4.png) like the other scheme and have some top and bottom padding
      - [x] Featured collection View all button to have a bottom spacing to [avoid content hug like this](https://screenshot.click/21-11-23jj5-74pba.png)
      - [x] To consider testing sections when they don't have a heading displayed

**Switching to from PX to REM**
- ~We should make is to have a true representation of what's being changed for anything related to spacing, margins, padding.~ To be discussed on this issue https://github.com/Shopify/dawn/issues/984

**Scaling values across devices**
-  ~Adjust the values applied to be reduced on smaller screens since they won't need the same value to accomplish the same aesthetic.~ _No longer relevant if we have a device specific setting available. - Meli_

**Comment by KaichenWang** [comment]
While working on vertical spacing between sections, I've noticed that there are many factors which may contribute to a given section's perceived vertical spacing in relation to other sections. 

I've documented these factors here:
https://docs.google.com/document/d/1ZIsFqqPPQ-El9K-hH8MKxhsu1gc4ydMvgVnBEUstza8/edit?usp=sharing

What does this document help achieve?
1. Help with identifying repeating patterns between different sections (DRY/code reduction)
2. Ensure implementation of `Vertical spacing between sections` setting is consistent and truly compatible with all sections
3. Provides a checklist for what needs to be tested

**Comment by melissaperreault** [comment]
### Other observations

**Shadow offset**
- [ ] HMW adjust the spacing if shadows are applied on other components? Can we consider adapting the value so that visually we always display the intended spacing and [consider the shadows offset as well](https://screenshot.click/21-11-09i4v-xcw0i.png)?

**Comment by tyleralsbury** [comment]
> ### Other observations
> **Shadow offset**
> 
> * [ ]  HMW adjust the spacing if shadows are applied on other components? Can we consider adapting the value so that visually we always display the intended spacing and [consider the shadows offset as well](https://screenshot.click/21-11-09i4v-xcw0i.png)?

If we do consider doing this, I would probably put it into its own issue so that we can outline all of the spots in which we want this to happen.  Original discussion was just around buttons that appear together (image banner, add to cart, checkout buttons).

**Comment by melissaperreault** [comment]
> If we do consider doing this, I would probably put it into its own issue so that we can outline all of the spots in which we want this to happen. Original discussion was just around buttons that appear together (image banner, add to cart, checkout buttons).

Great point! This observation is no longer aligned with the latest feedback and direction. Merchants could rely on adjusting the grid vertical spacing to meet a good aesthetic outcome instead. Adding an edit to my comment for clarity!

**Comment by KaichenWang** [comment]
- [ ] TODO: Fix vertical spacing in Feature Collection between product cards and CTA caused by desktop grid vertical spacing setting. Padding is applied even though there is only 1 row of cards

**Comment by melissaperreault** [comment]
## Update

We will no longer rely on mobile specific settings for the settings inside Layout category. We'll rely on a ratio scale to determine the values for smaller screens instead.

- [ ] [New internal Figma reference](https://www.figma.com/file/9FOEO0DFKgNDjiqxMakiLB/Design-Settings-Components?node-id=141%3A10944)
- [ ] For the `Vertical space between sections`, please follow the same ratio logic as explained here by Olivia https://github.com/Shopify/dawn/pull/1006#issuecomment-995049798
- [ ] For the Grid ranges, mobile will be 0.5 times the value, as it is already today.
