### ISSUE TITLE
[Global settings] Buttons and inputs

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#926]
### Settings reference
- [Buttons: Internal Figma link](https://www.figma.com/file/9FOEO0DFKgNDjiqxMakiLB/Design-Settings-Components?node-id=141%3A10670)
- [Inputs: Internal Figma link](https://www.figma.com/file/9FOEO0DFKgNDjiqxMakiLB/Design-Settings-Components?node-id=141%3A10766)

### Observations

**General for all**
**_Shadow_**
- [x] Make the shadow [appear below components](https://screenshot.click/21-12-4sygy-h8xhu.png)

**Margins**
- [x] Add both Horizontal and Vertical margins setting to those components. This is to help achieve spacing out elements when the shadow is strong and need more space.

**Buttons**
**_Corner radius_**
- [x] ~As we increase the corner radius, [more space is required](https://screenshot.click/21-11-zgvyy-lbzqr.png) to have a cleaner well balanced CTA. Button padding is not kept on one of the version I tested.~ _Edit Dec 2: Increase the button left and right padding to have a successful outcome for when there is an extreme corner radius or not._
- [x] [Adjust left and right padding](https://screenshot.click/21-12-5m4ab-5uvyj.png) in buttons to have good spacing when edges are round. + Pair to talk about min size.

**Inputs**
**_Corner radius_**
- [x] ~As we increase the corner radius, adjust the alignment of [the input label and the text](https://screenshot.click/21-11-g4n0r-eggdi.png) to balance padding negative space of the component.~ _Edit Dec 2: Increase the button left and right padding to have a successful outcome for when there is an extreme corner radius or not._
- [x] [Adjust left and right padding](https://screenshot.click/21-12-pqsf4-stb0v.png) for inputs to improve sharp and round edges output.

**Comment by tyleralsbury** [comment]
> As we increase the corner radius, more space is required to have a cleaner well balanced CTA. Button padding is not kept on one of the version I tested.

It will be hard to implement this consistently.  There will be issues as the numbers scale as well.

A few issues I see, right off the bat:

1. If we make the padding == the corner radius, a button with no corner radius would have no padding.
2. If we do any sort of addition to a base padding, the padding won't line up the way you indicated in the image.  
3. There may be corner radius values that don't change anything in the sense that the button will be smaller than the maximum of the corner radius setting.  So the difference between a corner radius of 44px and 50px will not change.  If the padding is based on the corner radius, though, that will continue to increase the padding, pushing it further out of line.

I'm not sure why the padding is not there in the screenshot, but I think it would be safer for it to always be the same, regardless of the corner radius setting.

We will run into very similar issues with the input as well.

A solution to both of these might be an upper and lower limit on the values for the padding to ensure a minimum padding is maintained and a maximum padding stops things from getting too extreme.  However, the upper limit will be hard to apply consistently, and it's getting into magic territory if sometimes changing the value changes the padding and sometimes it doesn't.

Also, from the principled perspective of "each setting represents a CSS property", it is breaking that as well.

**Comment by melissaperreault** [comment]
Great input Tyler, thanks! I am revisiting the bullet description to match the most recent feedback and alignment. We can increase the default to be successful on all instances instead of being unpredictable. 👌  I am aligned!
