### ISSUE TITLE
[Global settings] Cards

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#929]
### Settings reference
- [Internal Figma link](https://www.figma.com/file/9FOEO0DFKgNDjiqxMakiLB/Design-Settings-Components?node-id=141%3A11236)

### Observations

**Featured collection**
- [x] When the style is set to `Card`, the height needs to be fixed and follow the tallest card to avoid various rectangle sizes. ~Same thing if you add a border or shadow to the `Standard` style.~
   - [ ] Have the quick buy button always snap at the bottom too (Only relevant once we ship this feature.)

**Blog posts section/template**
- [x] They are [not receiving any styles](https://screenshot.click/21-12-9klon-6s4jp.png) yet

**Collection list**
- [ ] Some images in the cards [don’t align with the border](https://screenshot.click/21-12-6wya5-gnefx.png)

**Collage section**
   - [x] Card style `Standard`: Product block and [is not styled like expected](https://screenshot.click/21-12-krpli-aj8va.png). We are left with a sharp edge border all around.
   - [x] Card style `Card`:  Product block has [a double border applied](https://screenshot.click/21-12-5k42g-15oi7.png), to be removed.

 **Very low priority**
- [ ] #1049

### For testing reference purposes

| Settings |  Current location | New location |
| ------------- | ------------- | ------------- |
| Image Padding on Product Cards | All sections that include product cards: | Card: Image Padding |
| | - Featured Collection | |
| | - Product Recommendation | |
| | - Collage | |
| | - Search Result | |
| Show Image Border | All sections that include product cards: | Card: Border settings |
| | - Featured Collection | |
| | - Product Recommendation | |
| | - Collage | |
| | - Search Result | |

Closing this issue to tackle the remaining items in separate issues instead.

**Comment by nicklepine** [comment]
To look into: 
- [ ] If a merchant adds a gradient to one of their color, when picking a card color scheme that includes a gradient, should we add the gradient to the card? My assumption would be yes. [(recording) ](https://screenshot.click/21-16-rc9rw-x9cpq.mp4)

**Comment by KaichenWang** [comment]
> Blog posts section/template
> - [ ] They are not receiving any styles yet

@kmeleta cards for articles should be compatible with the markup in `main-search.liquid` under `{%- when 'article' -%}`

**Comment by kmeleta** [comment]
An update on some items in here..

> - [ ] Some images in the cards don’t align with the border

We believe this is a chrome visual bug around borders of certain non-integer pixel values. A first attempt at preventing the bug was unsuccessful with the usual tricks. Will have to revisit.


> - [ ] Featured collection: When it resizes into 2 column widths, cards are losing grid spacing. Only when swipe on mobile is turned on

Currently this is a small fix I tagged onto the slider shadow fixes commit mentioned above. If that PR gets held up I'll split it out.


> - [ ] [blog cards] They are not receiving any styles yet

This is being addressed in another open PR


> - [ ] When the style is set to Card, the height needs to be fixed and follow the tallest card to avoid various rectangle sizes.

This is currently included in the blog cards PR


> - [ ] Same thing if you add a border or shadow to the Standard style.

I could use confirmation on this one @melissaperreault. Is [this](https://screenshot.click/17-11-2rwrr-za2ob.png) what we're expecting? But _only_ if some border and/or shadow is added? I'll play with it but I'm not actually certain if we'll be able to easily achieve this or not.

**Comment by melissaperreault** [comment]
> I could use confirmation on this one @melissaperreault. Is this what we're expecting? But only if some border and/or shadow is added? I'll play with it but I'm not actually certain if we'll be able to easily achieve this or not.

@kmeleta I think this is a mistake and misleading, sorry! `Standard` style looks fine with the global settings, just the `Card` style needed to account for the details! I'll remove that mention to avoid confusions! 🙏
