### ISSUE TITLE
Let merchants add more static sections

### ISSUE THREAD

**Issue by valeriegohier** [Shopify/dawn#951]
We hear anecdotally that some merchants might benefit from being able to add different types of static sections (surfacing on all pages) i.e. a larger "Black Friday Sale" notice

This ticket will consist of an exploration on: 
- Different use-cases where this could create value for merchants
- Ways to achieve this, implementation-wise.

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
