### ISSUE TITLE
Audit: property `gap` in the theme

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#964]
Original comment by @KaichenWang: https://github.com/Shopify/dawn/pull/900#discussion_r751679171

_We may need to use margin instead, since flex gap isn't supported in all latest (and latest -1) browser versions. Although the previous implementation already uses this property_

https://github.com/Shopify/dawn/pull/900#discussion_r751678147

cc @ludoboludo

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
