### ISSUE TITLE
Adjusting quantity of item in /cart fails on local dev

### ISSUE THREAD

**Issue by savraj** [Shopify/dawn#968]
**Describe the current behavior**
1) fork the current dawn repo
2) run with `shopify theme serve`, visit `localhost:9292`
3) add some items to your cart, go to /cart, then adjust quantities
4) you'll see the error message "There was an error while updating your cart. Please try again."

**Describe the expected behavior**
No error message and quantities adjust.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.4.0
- Chrome Version 96.0.4664.55 (Official Build) (x86_64)
- macOS Version 12.0.1

**Possible solution**
What's happening is the section rendering API is returning NULL in the response object -- no sections are being returned from the POST to `/cart/change` 
You can see this by logging out the returned parsed state - add `console.log(parsedState);` on line 74 of `cart.js` -- the parsed state `sections:  null`

**Comment by jonpennington** [comment]
Not perfect solution but I did a find/replace for:

`${routes`
`${window.shopUrl}${routes`

It at least allows for usage for both local and store origin. Should be 4 files: 
- cart.js
- global.js
- predictive-search.js
- product-form.js

**Comment by Mit01** [comment]
Can not get section data in production. too!
