### ISSUE TITLE
[Global settings] Adjust shadow to display behind components

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#979]
### Observation

Look for any instances, here are examples:

- [ ] Variant pills: Make the shadow [appear behind components](https://screenshot.click/21-12-4sygy-h8xhu.png)
- [ ] Cards: Have the [shadow](https://screenshot.click/21-12-dyw1d-do7u1.png) appear below all elements of a section

**Comment by kmeleta** [comment]
Also an issue with product media

**Comment by kmeleta** [comment]
Image with text shadows will be addressed here https://github.com/Shopify/dawn/pull/1003

**Comment by kmeleta** [comment]
Also need multicolumn text boxes..

**Comment by kmeleta** [comment]
FYI, I'm currently looking at pill shadows along with some possibly related issues in https://github.com/Shopify/dawn/issues/1021. I don't think it's worth pushing a quick fix for just the shadow overlap issue without considering the other related changes or we could end up reworking it twice.

**Comment by kmeleta** [comment]
These areas have been addressed. I'm not currently aware of any others, besides buttons, which are being handled separately.

- [x] Product cards
- [x] Blog cards
- [x] Variants pills
- [x] Product media
- [x] Multicolumn cards
- [x] Image with text
