### ISSUE TITLE
[Global settings] Adjust left and right padding on multiple components

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#981]
### Observation

Padding left and right to change inside components so it looks nicer for when sharp or round edges is set. It provides more breathing space for the text. This is applicable for:
  - [x] [Buttons](https://screenshot.click/21-12-lj6lf-wlodt.png)
  - [ ] [Inputs](https://screenshot.click/21-12-w9quo-ltwpm.png)
  - [x] Badges, I believe we are ok but to test further if it needs an adjustment
  - [x] Variant pills, I believe we are ok but to test further if it needs an adjustment

**Comment by tyleralsbury** [comment]
> @tyleralsbury The values are described in the screenshots for each component! 🙏

Super, thanks Meli.
