### ISSUE TITLE
[Global settings] Using rem units on range instead of px

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#984]
### Expectation
- [ ] Smallest scope change that we could make is to have a true representation of what's being changed - so, show `rem` rather than `px` for any ranges tackling spacing, margins or padding. Sounds like we could fairly safely make that change, but that any additional enhancement would require some exploration.

**Questions:**
 - Are decimals displayed for range units?

### Context
> We've decided, for the sake of proper scaling throughout the theme, that many of the settings that currently are using `px` values should instead use `rem` values.  As a result, the unit of `px` being shown in the admin for those settings can easily become untrue - if the merchant changes the body font scaling, the `px` value will no longer match up.
> So we've come up with two options for what to do...
> 1. We show the `rem` unit instead.  The upside of this is full transparency, exposing the merchant to what is actually being changed when that setting is adjusted.  The downside is that `rem` is a less well known and harder to understand unit than `px` and thus might be scary to merchants.
> 2. We show **no** unit.  Given default font settings, `2` will still correspond to the `rem` equivalent of `2px`, but we completely omit the unit.  The upsides here are that the merchant doesn't need to worry about the implementation details and that it gives us a bit of room to do some magic here and there where providing a unit makes the exceptional cases where we do need to use magic somewhat of a "lie".

**Comment by KaichenWang** [comment]
> Changing the units to rem is pretty simple, but I haven't done it in this PR. I know we've had some team discussions on the topic already, but after some thought, I have some hesitation towards changing to rem because:
> 
> - rem is a relative unit, so without knowing the root font size, the value has no real meaning
> - If we provided the root font size as a note, we still don't have empirical data to support the fact that rem units are widely understood by merchants

From https://github.com/Shopify/dawn/pull/976#issuecomment-988980688

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
