### ISSUE TITLE
[Global setting] Email signup input background to be transparent

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#991]
### Observation 

- [ ] Email sign up: input field [should be transparent](https://screenshot.click/21-12-0qa29-ken4s.png)
- [ ] Test Contact form section as well

**Comment by Stephanie-Chou** [comment]
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps
