### ISSUE TITLE
[Global settings] Miscellaneous bugs around global styles and filter / sort

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#992]
### Observations

- [x] Remove background color [from `Sort` dropdown](https://screenshot.click/21-12-n20e6-rdog4.png) 
- [x] [Sort dropdown](https://screenshot.click/21-21-6xj2f-vgwxp.png) should not adopt dropdown&inputs settings (corner radius, shadow, etc).  [Screenshot 2](https://screenshot.click/21-30-c6c31-ytgg2.png)
when filters are collapsed
- [x] Applied filter pills should not leverage the global styles
![image](https://user-images.githubusercontent.com/8127145/145883712-76f53e36-4184-4acb-952c-2bbd086deced.png)

**Comment by ludoboludo** [comment]
I believe none of those are issues anymore already. On the latest `all-global-settings` branch settings I couldn't replicate the issues listed above. If you want and give it a try to confirm, test on this store: 
- [storefront](https://os2-demo.myshopify.com/?preview_theme_id=127056510998)
- [theme editor](https://os2-demo.myshopify.com/admin/themes/127056510998/editor)

**Comment by melissaperreault** [comment]
Thanks @ludoboludo I think some are still relevant:

- To prevent any future gap, let's ensure there is no color background applied on the Sort select [like shown in the Video here](https://screenshot.click/22-01-ic9sg-29o5s.mp4), if feasible
- NEW! The focus is not consistent still on all elements ([Video](https://screenshot.click/22-01-fafxk-vg2vx.mp4))
- Mobile `Filter` drawer, [the shadow still display](https://screenshot.click/22-01-y99kz-ixkv8.png) on the `Sort` select
