### ISSUE TITLE
[Global settings] Inputs styling not applied consistently

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#993]
### Observation

- [x] Country/region and language selectors [don't receive the Inputs styling yet](https://screenshot.click/21-12-wyyxw-vxfph.png)
- [x] Stroke applied inside [instead of outside on Quantity input](https://screenshot.click/21-12-m4rwj-gy37a.png)
- [x] [Share block](https://screenshot.click/21-12-1dox2-a7oep.png) on Product template [isn't styled properly](https://screenshot.click/21-12-05o3r-h88q6.mp4)
- [x] Enable cart note, the drag corner get's lost [when corner radius is on](https://screenshot.click/21-12-1mrvl-cxqnj.png)
    - [x] Let's remove the corner radius from the bottom-right

**Comment by sofiamatulis** [comment]
> [ ] Enable cart note, the drag corner get's lost [when corner radius is on](https://screenshot.click/21-12-1mrvl-cxqnj.png)
> * [ ]  Let's remove the corner radius from the bottom-right

@melissaperreault Good catch! Although when I remove the corner radius from bottom-right, this is what it looks like: https://screenshot.click/05-50-wqgpv-vn6wh.png
