### ISSUE TITLE
[Global setting] Add motion hover effect on Buttons

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#994]
### Settings reference
- [Internal Figma link](https://www.figma.com/file/9FOEO0DFKgNDjiqxMakiLB/Design-Settings-Components?node-id=678%3A13160)

### Expectation

- [ ] To offer a delightful experience to merchants' buyers, taking advantage of the added flexibility to have strong and deep shadows, [we want to add a new hover effect option](https://screenshot.click/21-12-6j2qs-nrmdk.mp4).
   - [ ] Enlarge (Current animation)
   - [ ] Pressed (Decrease by 1px on each side and reduce by half the shadow offset.)

**Comment by nicklepine** [comment]
Piece of feedback on button hover states to tackle at the same time: 
The hover effect on buttons is very light when the border opacity is light: https://screenshot.click/12-25-ylaa8-ntkec.mp4
