### ISSUE TITLE
[Global setting] Sort caret overlaps words

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#999]
- [ ] [Caret overlapping label](https://screenshot.click/21-12-ejzar-8tuuj.png)

**Comment by melissaperreault** [comment]
Thanks Ludo, please let's develop this as a progressive enhancement with JS and have the no JS version default to the screenshot example.

**Comment by KaichenWang** [comment]
I've [addressed](https://github.com/Shopify/dawn/pull/1150) what I consider to be most critical: Fix caret overlapping label.

As for setting dynamic width based on label length, I can look into that enhancement, but ideally as part of a standalone issue.
